// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { Metadata } from "next";
import { Guard, ViewPage } from "@/screens";
import { strings, texts } from "@/strings";
import { schema } from "./page.schema";

export const metadata: Metadata = { title: strings["member-view.title"] };

const routes = {
  "member-edit": "/members/{memberId}/edit",
};

export default async function Page({ params }: { readonly params: Promise<Record<string, string>> }) {
  const parameters = await params;
  const t = texts(schema);
  return (
    <Guard permission={schema.permission} texts={t}>
      <ViewPage schema={schema} texts={t} routes={routes} parameters={parameters} />
    </Guard>
  );
}
