// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_golden_missing: page directory has no golden scenario; add one under tests, for example directory-succeeds: { page: directory, scenario: golden, given: "any caller", when: "the page directory is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/directory]
// specarch-problem: warning: test_red_missing: page directory has no red scenario; add one under tests, for example directory-refused: { page: directory, scenario: red, given: "...", when: "...", then: "it is refused" } [test_red_missing@specarch.yaml#/pages/directory]
import type { Metadata } from "next";
import { DataPage } from "@acme/screens/data";
import { Guard } from "@/screens";
import { chosenLanguage } from "@/language";
import { stringOf, texts } from "@/strings";
import { schema } from "./page.schema";

export async function generateMetadata(): Promise<Metadata> {
  return { title: stringOf("directory.title", await chosenLanguage()) };
}

const routes = {
};

export default async function Page() {
  const t = texts(schema, await chosenLanguage());
  return (
    <Guard permission={schema.permission} texts={t}>
      <DataPage schema={schema} texts={t} routes={routes} />
    </Guard>
  );
}
