-- Generated by specarch-gen-sql from ../project/specarch.yaml, version 1.0.0; meta-model 0.1; postgresql through type-rendering 1.2.0. Do not edit this file: a change to the schema is a new migration.

CREATE TABLE members (
    id UUID NOT NULL,
    address_city VARCHAR(100) NOT NULL,
    address_location_latitude DOUBLE PRECISION,
    address_location_longitude DOUBLE PRECISION,
    address_postcode VARCHAR(20),
    address_street VARCHAR(200) NOT NULL,
    mailing_address_city VARCHAR(100),
    mailing_address_location_latitude DOUBLE PRECISION,
    mailing_address_location_longitude DOUBLE PRECISION,
    mailing_address_postcode VARCHAR(20),
    mailing_address_street VARCHAR(200),
    name VARCHAR(200) NOT NULL,
    phones JSONB,
    preferences JSONB,
    CONSTRAINT pk_members PRIMARY KEY (id),
    CONSTRAINT ck_members_address_location CHECK ((((address_location_latitude IS NULL) AND (address_location_longitude IS NULL)) OR ((address_location_latitude IS NOT NULL) AND (address_location_longitude IS NOT NULL)))),
    CONSTRAINT ck_members_mailing_address CHECK ((((((mailing_address_city IS NULL) AND (mailing_address_location_latitude IS NULL)) AND (mailing_address_location_longitude IS NULL)) AND ((mailing_address_postcode IS NULL) AND (mailing_address_street IS NULL))) OR ((mailing_address_city IS NOT NULL) AND (mailing_address_street IS NOT NULL)))),
    CONSTRAINT ck_members_mailing_address_location CHECK ((((mailing_address_location_latitude IS NULL) AND (mailing_address_location_longitude IS NULL)) OR ((mailing_address_location_latitude IS NOT NULL) AND (mailing_address_location_longitude IS NOT NULL))))
);
