// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
"use client";

import type { ComponentProps } from "react";
import { FormPage } from "@/screens";
import { lentOn } from "./page.hooks";

const hooks = { lentOn };

/** The form with the hooks of its fields, which run in the browser. */
export function HookedForm(props: Omit<ComponentProps<typeof FormPage>, "hooks">) {
  return <FormPage {...props} hooks={hooks} />;
}
