// Package genopenapi writes the OpenAPI 3.1 document of a specification:
// the logic of the specarch-gen-openapi plug-in, in the standard dialect.
// The keywords are OpenAPI's and JSON Schema's own, so the document is the
// design field for field; what SpecArch adds is carried as x-specarch-
// extensions, the problem catalogue becomes the error responses, and a
// list is expanded through the paginated-list idiom.
package genopenapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"go.yaml.in/yaml/v3"
)

// Request is what specarch writes on a plug-in's standard input.
type Request struct {
	Specarch        string           `json:"specarch"`
	Target          string           `json:"target"`
	Root            string           `json:"root"`
	Specification   map[string]any   `json:"specification"`
	Implementations []Implementation `json:"implementations"`
	Output          string           `json:"output"`
}

// Implementation is one implementation file in the request.
type Implementation struct {
	File     string         `json:"file"`
	Content  map[string]any `json:"content"`
	Settings map[string]any `json:"settings,omitempty"`
	Idioms   []Idiom        `json:"idioms"`
}

// Idiom is one idiom an implementation file uses.
type Idiom struct {
	Name     string         `json:"name"`
	Version  string         `json:"version"`
	As       string         `json:"as"`
	Content  map[string]any `json:"content,omitempty"`
	Override map[string]any `json:"override,omitempty"`
}

// File is one file the plug-in answers with.
type File struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// Diagnostic is one problem the plug-in reports, in the validator's fields.
type Diagnostic struct {
	File     string `json:"file"`
	Line     int    `json:"line"`
	Severity string `json:"severity"`
	Path     string `json:"path"`
	Rule     string `json:"rule"`
	Message  string `json:"message"`
}

// Response is what the plug-in writes on its standard output.
type Response struct {
	Files       []File       `json:"files"`
	Diagnostics []Diagnostic `json:"diagnostics"`
}

// FileName is the one file the plug-in writes in the target's folder.
const FileName = "openapi.yaml"

// Decode reads a request, keeping numbers as their text.
func Decode(data []byte) (*Request, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var r Request
	if err := dec.Decode(&r); err != nil {
		return nil, err
	}
	return &r, nil
}

// maxSafe is 2^53 - 1, the largest integer every JSON reader holds exactly.
const maxSafe = "9007199254740991"

// auditFields are the fields an audited entity carries, set by the system.
var auditFields = []struct{ name, format, description string }{
	{"createdAt", "date-time", "When the record was created; set by the system."},
	{"createdBy", "", "Who created the record; set by the system."},
	{"lastModifiedAt", "date-time", "When the record was last changed; set by the system."},
	{"lastModifiedBy", "", "Who last changed the record; set by the system."},
}

type gen struct {
	spec      map[string]any
	settings  map[string]any
	idioms    []Idiom
	diags     []Diagnostic
	root      string
	scheme    string // the security scheme's name, or ""
	paramName map[string]string
	envName   map[string]string
}

// Generate writes the OpenAPI document of a request.
func Generate(r *Request) Response {
	g := &gen{spec: r.Specification, root: r.Root}
	for _, impl := range r.Implementations {
		if g.settings == nil && impl.Settings != nil {
			g.settings = impl.Settings
		}
		if g.idioms == nil && len(impl.Idioms) > 0 {
			g.idioms = impl.Idioms
		}
	}
	for _, impl := range r.Implementations {
		if text(obj(obj(impl.Content["targets"])[r.Target])["dialect"]) == "dxlib" {
			return g.generateDxlib(r)
		}
	}
	doc := mapping()
	add(doc, "openapi", str("3.1.0"))
	info := mapping()
	specInfo := obj(g.spec["info"])
	add(info, "title", str(text(specInfo["title"])))
	add(info, "version", str(text(specInfo["version"])))
	if d := text(specInfo["description"]); d != "" {
		add(info, "description", str(d))
	}
	add(doc, "info", info)
	if paths := g.paths(); len(paths.Content) > 0 {
		add(doc, "paths", paths)
	}
	add(doc, "components", g.components())
	if len(g.diags) > 0 {
		return Response{Files: []File{}, Diagnostics: g.diags}
	}
	var b bytes.Buffer
	info2 := obj(g.spec["info"])
	fmt.Fprintf(&b, "# Generated by specarch-gen-openapi from %s, version %s; meta-model %s. Do not edit this file: change the YAML and generate again.\n", relRoot(r.Root, r.Output), text(info2["version"]), r.Specarch)
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return Response{Files: []File{}, Diagnostics: []Diagnostic{g.problem("/", "the document cannot be written as YAML (%v); this is a bug in specarch-gen-openapi", err)}}
	}
	return Response{Files: []File{{Path: FileName, Content: b.String()}}, Diagnostics: []Diagnostic{}}
}

func (g *gen) problem(path, format string, args ...any) Diagnostic {
	return Diagnostic{File: g.root, Line: 1, Severity: "error", Path: path, Rule: "generator", Message: fmt.Sprintf(format, args...)}
}

// relRoot is the root file's path as seen from the output folder.
func relRoot(root, output string) string {
	absRoot, err1 := filepath.Abs(filepath.FromSlash(root))
	absOut, err2 := filepath.Abs(filepath.FromSlash(output))
	if err1 != nil || err2 != nil {
		return root
	}
	rel, err := filepath.Rel(absOut, absRoot)
	if err != nil {
		return root
	}
	return filepath.ToSlash(rel)
}

// paths writes every path item and its operations.
func (g *gen) paths() *yaml.Node {
	out := mapping()
	paths := obj(g.spec["paths"])
	for _, p := range sortedKeys(paths) {
		item := obj(paths[p])
		node := mapping()
		if params := list(item["parameters"]); len(params) > 0 {
			add(node, "parameters", g.parameters(params))
		}
		for _, method := range []string{"get", "put", "post", "delete", "patch"} {
			if op, ok := item[method].(map[string]any); ok {
				add(node, method, g.operation(p, method, op))
			}
		}
		add(out, p, node)
	}
	return out
}

// operation writes one operation.
func (g *gen) operation(path, method string, op map[string]any) *yaml.Node {
	n := mapping()
	for _, k := range []string{"operationId", "summary", "description"} {
		if v := text(op[k]); v != "" {
			add(n, k, str(v))
		}
	}
	params := g.parameters(list(op["parameters"]))
	body := g.requestBody(obj(op["requestBody"]))
	responses := g.responses(obj(op["responses"]))
	if l, ok := op["listOf"].(map[string]any); ok {
		g.expandList(path, method, l, params, &body, responses)
	}
	if len(params.Content) > 0 {
		add(n, "parameters", params)
	}
	if body != nil {
		add(n, "requestBody", body)
	}
	add(n, "responses", responses)
	if op["deprecated"] == true {
		add(n, "deprecated", boolean(true))
	}
	perm := text(op["permission"])
	if g.securityScheme() != "" {
		sec := sequence()
		if perm != "public" {
			req := mapping()
			add(req, g.scheme, sequence())
			sec.Content = append(sec.Content, req)
		}
		add(n, "security", sec)
	}
	if perm != "" {
		add(n, "x-specarch-permission", str(perm))
	}
	if l, ok := op["limits"].(map[string]any); ok {
		add(n, "x-specarch-limits", plain(l))
	}
	if e := list(op["emits"]); len(e) > 0 {
		add(n, "x-specarch-emits", plain(e))
	}
	if s := list(op["satisfies"]); len(s) > 0 {
		add(n, "x-specarch-satisfies", plain(s))
	}
	return n
}

func (g *gen) parameters(params []any) *yaml.Node {
	out := sequence()
	for _, p := range params {
		pm := obj(p)
		n := mapping()
		for _, k := range []string{"name", "in", "description"} {
			if v := text(pm[k]); v != "" {
				add(n, k, str(v))
			}
		}
		if pm["required"] == true {
			add(n, "required", boolean(true))
		}
		if pm["deprecated"] == true {
			add(n, "deprecated", boolean(true))
		}
		if s, ok := pm["schema"].(map[string]any); ok {
			add(n, "schema", g.schema(s))
		}
		out.Content = append(out.Content, n)
	}
	return out
}

func (g *gen) requestBody(rb map[string]any) *yaml.Node {
	if rb == nil {
		return nil
	}
	n := mapping()
	if d := text(rb["description"]); d != "" {
		add(n, "description", str(d))
	}
	if rb["required"] == true {
		add(n, "required", boolean(true))
	}
	add(n, "content", g.content(obj(rb["content"])))
	return n
}

func (g *gen) content(c map[string]any) *yaml.Node {
	out := mapping()
	for _, mt := range sortedKeys(c) {
		m := mapping()
		if s, ok := obj(c[mt])["schema"].(map[string]any); ok {
			add(m, "schema", g.schema(s))
		}
		add(out, mt, m)
	}
	return out
}

// responses writes the responses; one that names a problem type answers an
// RFC 9457 problem document of that type.
func (g *gen) responses(rs map[string]any) *yaml.Node {
	out := mapping()
	for _, code := range sortedKeys(rs) {
		r := obj(rs[code])
		n := mapping()
		add(n, "description", str(text(r["description"])))
		if p := text(r["problem"]); p != "" {
			c := mapping()
			m := mapping()
			add(m, "schema", ref("#/components/schemas/Problem"))
			add(c, "application/problem+json", m)
			add(n, "content", c)
			add(n, "x-specarch-problem", str(p))
		} else if c, ok := r["content"].(map[string]any); ok {
			add(n, "content", g.content(c))
		}
		add(out, code, n)
	}
	return out
}

// schemaKeys are the JSON Schema keywords a field carries over, in the
// order they are written.
var schemaKeys = []string{"type", "format", "description", "enum", "const", "default", "examples",
	"minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "multipleOf",
	"minLength", "maxLength", "pattern", "minItems", "maxItems", "uniqueItems", "readOnly", "writeOnly", "deprecated"}

// extensionKeys are SpecArch's own field keywords, carried as x-specarch-.
var extensionKeys = []string{"precision", "scale", "sensitivity", "atRest", "lookup"}

// schema writes a field: JSON Schema's keywords as they are, a $ref into
// the components, and SpecArch's own keywords as extensions. Rationale and
// test hints (why, cites, origin, mistakes) are not interface and are left
// out.
func (g *gen) schema(s map[string]any) *yaml.Node {
	if r := text(s["$ref"]); r != "" {
		if i := strings.LastIndex(r, "/"); i >= 0 {
			return ref("#/components/schemas/" + r[i+1:])
		}
	}
	n := mapping()
	for _, k := range schemaKeys {
		if v, ok := s[k]; ok {
			add(n, k, plain(v))
		}
		if k == "uniqueItems" {
			if items, ok := s["items"].(map[string]any); ok {
				add(n, "items", g.schema(items))
			}
			if props, ok := s["properties"].(map[string]any); ok {
				pn := mapping()
				for _, p := range sortedKeys(props) {
					add(pn, p, g.schema(obj(props[p])))
				}
				add(n, "properties", pn)
			}
			if req := list(s["required"]); len(req) > 0 {
				add(n, "required", plain(req))
			}
		}
	}
	for _, k := range extensionKeys {
		if v, ok := s[k]; ok {
			add(n, "x-specarch-"+k, plain(v))
		}
	}
	return n
}

// components writes the entities and enums as schemas, the problem
// document, the problem catalogue, and the security scheme.
func (g *gen) components() *yaml.Node {
	out := mapping()
	schemas := mapping()
	enums := obj(g.spec["enums"])
	entities := obj(g.spec["entities"])
	var names []string
	for k := range enums {
		names = append(names, k)
	}
	for k := range entities {
		names = append(names, k)
	}
	views := obj(g.spec["views"])
	for k := range views {
		names = append(names, k)
	}
	sort.Strings(names)
	for _, name := range names {
		if e, ok := enums[name].(map[string]any); ok {
			n := mapping()
			t := text(e["type"])
			if t == "" {
				t = "string"
			}
			add(n, "type", str(t))
			if d := text(e["description"]); d != "" {
				add(n, "description", str(d))
			}
			add(n, "enum", plain(e["enum"]))
			if vd, ok := e["valueDescriptions"].(map[string]any); ok {
				add(n, "x-specarch-valueDescriptions", plain(vd))
			}
			add(schemas, name, n)
			continue
		}
		e := obj(entities[name])
		description := text(e["description"])
		ps := obj(e["properties"])
		var added []any
		if v, ok := views[name].(map[string]any); ok {
			// A view is its entity's fields and the fields it adds.
			e = obj(entities[text(v["from"])])
			description = text(v["description"])
			extra, names := g.viewAdded(name)
			all := map[string]any{}
			for k, f := range obj(e["properties"]) {
				all[k] = f
			}
			for k, f := range extra {
				all[k] = f
			}
			ps, added = all, names
		}
		n := mapping()
		add(n, "type", str("object"))
		if description != "" {
			add(n, "description", str(description))
		}
		props := mapping()
		for _, p := range sortedKeys(ps) {
			add(props, p, g.schema(obj(ps[p])))
		}
		if e["audited"] == true {
			for _, f := range auditFields {
				fn := mapping()
				add(fn, "type", str("string"))
				if f.format != "" {
					add(fn, "format", str(f.format))
				}
				add(fn, "description", str(f.description))
				add(fn, "readOnly", boolean(true))
				add(props, f.name, fn)
			}
		}
		add(n, "properties", props)
		if req := append(append([]any{}, list(e["required"])...), added...); len(req) > 0 {
			add(n, "required", plain(req))
		}
		if v, ok := views[name].(map[string]any); ok {
			add(n, "readOnly", boolean(true))
			add(n, "x-specarch-view", plain(map[string]any{"from": v["from"]}))
		}
		if e["audited"] == true {
			add(n, "x-specarch-audited", boolean(true))
		}
		if d := text(e["deletion"]); d != "" {
			add(n, "x-specarch-deletion", str(d))
		}
		add(schemas, name, n)
	}
	if errs := obj(g.spec["errors"]); len(errs) > 0 {
		add(schemas, "Problem", problemSchema())
	}
	if len(schemas.Content) > 0 {
		add(out, "schemas", schemas)
	}
	if name := g.securityScheme(); name != "" {
		ss := mapping()
		scheme := mapping()
		def := obj(g.settings["securityScheme"])
		for _, k := range sortedKeys(def) {
			if k != "name" {
				add(scheme, k, plain(def[k]))
			}
		}
		add(ss, name, scheme)
		add(out, "securitySchemes", ss)
	}
	if errs := obj(g.spec["errors"]); len(errs) > 0 {
		cat := mapping()
		for _, name := range sortedKeys(errs) {
			e := obj(errs[name])
			n := mapping()
			for _, k := range []string{"status", "title", "condition", "type"} {
				if v, ok := e[k]; ok {
					add(n, k, plain(v))
				}
			}
			add(cat, name, n)
		}
		add(out, "x-specarch-problems", cat)
	}
	return out
}

// securityScheme is the name of the scheme the target's settings give, or
// "": which scheme a service uses is the implementation's choice.
func (g *gen) securityScheme() string {
	g.scheme = text(obj(g.settings["securityScheme"])["name"])
	return g.scheme
}

// problemSchema is RFC 9457's problem details object.
func problemSchema() *yaml.Node {
	n := mapping()
	add(n, "type", str("object"))
	add(n, "description", str("A problem details object, RFC 9457."))
	props := mapping()
	for _, f := range []struct{ name, typ, format, desc string }{
		{"type", "string", "uri-reference", "The problem type; about:blank when it has none of its own."},
		{"title", "string", "", "A short summary of the problem type, the same for every occurrence."},
		{"status", "integer", "int32", "The HTTP status code."},
		{"detail", "string", "", "An explanation of this occurrence."},
		{"instance", "string", "uri-reference", "This occurrence."},
	} {
		fn := mapping()
		add(fn, "type", str(f.typ))
		if f.format != "" {
			add(fn, "format", str(f.format))
		}
		add(fn, "description", str(f.desc))
		add(props, f.name, fn)
	}
	add(n, "properties", props)
	return n
}

// expandList adds a list's search, filter, sort and page to the request, by
// the names of the paginated-list idiom, and wraps the answer in its
// envelope.
func (g *gen) expandList(path, method string, l map[string]any, params *yaml.Node, body **yaml.Node, responses *yaml.Node) {
	at := "/paths/" + strings.NewReplacer("~", "~0", "/", "~1").Replace(path) + "/" + method + "/listOf"
	if !g.listNames() {
		g.diags = append(g.diags, g.problem(at, "the operation lists %s, but the implementation file excludes the paginated-list idiom, and the standard dialect has no other way to page; keep the idiom, or override it", subjectName(l)))
		return
	}
	_, fields, _ := g.listSubject(l)
	parts := []struct {
		name   string
		schema *yaml.Node
		query  *yaml.Node // extra parameter keys, for a query
	}{}
	if len(list(l["searchable"])) > 0 {
		s := mapping()
		add(s, "type", str("string"))
		add(s, "description", str("Free text, matched against "+joinList(list(l["searchable"]))+"."))
		parts = append(parts, struct {
			name   string
			schema *yaml.Node
			query  *yaml.Node
		}{g.paramName["search"], s, nil})
	}
	if f := list(l["filterable"]); len(f) > 0 {
		s := mapping()
		add(s, "type", str("object"))
		props := mapping()
		for _, name := range f {
			add(props, text(name), g.schema(obj(fields[text(name)])))
		}
		add(s, "properties", props)
		add(s, "additionalProperties", boolean(false))
		q := mapping()
		add(q, "style", str("deepObject"))
		add(q, "explode", boolean(true))
		parts = append(parts, struct {
			name   string
			schema *yaml.Node
			query  *yaml.Node
		}{g.paramName["filter"], s, q})
	}
	if f := list(l["sortable"]); len(f) > 0 {
		s := mapping()
		add(s, "type", str("string"))
		var values []any
		for _, name := range f {
			values = append(values, text(name), "-"+text(name))
		}
		add(s, "enum", plain(values))
		parts = append(parts, struct {
			name   string
			schema *yaml.Node
			query  *yaml.Node
		}{g.paramName["sort"], s, nil})
	}
	page := mapping()
	add(page, "type", str("integer"))
	add(page, "format", str("int32"))
	add(page, "minimum", number("1"))
	add(page, "default", number("1"))
	size := obj(l["pageSize"])
	pageSize := mapping()
	add(pageSize, "type", str("integer"))
	add(pageSize, "format", str("int32"))
	add(pageSize, "minimum", number("1"))
	add(pageSize, "maximum", number(text(size["maximum"])))
	if d := text(size["default"]); d != "" {
		add(pageSize, "default", number(d))
	}
	parts = append(parts, struct {
		name   string
		schema *yaml.Node
		query  *yaml.Node
	}{g.paramName["page"], page, nil}, struct {
		name   string
		schema *yaml.Node
		query  *yaml.Node
	}{g.paramName["pageSize"], pageSize, nil})

	if method == "get" {
		for _, p := range parts {
			n := mapping()
			add(n, "name", str(p.name))
			add(n, "in", str("query"))
			if p.query != nil {
				n.Content = append(n.Content, p.query.Content...)
			}
			add(n, "schema", p.schema)
			params.Content = append(params.Content, n)
		}
	} else {
		var props *yaml.Node
		if *body == nil {
			b := mapping()
			c := mapping()
			m := mapping()
			s := mapping()
			add(s, "type", str("object"))
			props = mapping()
			add(s, "properties", props)
			add(m, "schema", s)
			add(c, "application/json", m)
			add(b, "content", c)
			*body = b
		} else {
			// The paging goes into the first media type's schema.
			var s *yaml.Node
			if mts := pairsOf(child(*body, "content")); len(mts) > 0 {
				s = child(mts[0].value, "schema")
			}
			if s == nil || child(s, "$ref") != nil || child(s, "properties") == nil {
				g.diags = append(g.diags, g.problem(at, "the operation lists %s by %s, so its paging goes in the request body, which is not an inline object with properties; make the body an object, or list by GET", subjectName(l), strings.ToUpper(method)))
				return
			}
			props = child(s, "properties")
		}
		for _, p := range parts {
			add(props, p.name, p.schema)
		}
	}

	for _, r := range pairsOf(responses) {
		if !strings.HasPrefix(r.key, "2") {
			continue
		}
		for _, mt := range pairsOf(child(r.value, "content")) {
			orig := child(mt.value, "schema")
			if orig == nil || child(orig, "items") == nil {
				continue
			}
			env := mapping()
			add(env, "type", str("object"))
			props := mapping()
			add(props, g.envName["items"], orig)
			for _, k := range []string{"totalItems", "totalPages"} {
				t := mapping()
				add(t, "type", str("integer"))
				add(t, "format", str("int64"))
				add(t, "minimum", number("0"))
				add(t, "maximum", number(maxSafe))
				add(props, g.envName[k], t)
			}
			add(env, "properties", props)
			add(env, "required", plain([]any{g.envName["items"], g.envName["totalItems"], g.envName["totalPages"]}))
			setChild(mt.value, "schema", env)
		}
	}
}

// listNames reads the wire names of the paginated-list idiom that applies,
// by the lookup order: the override's part, the shipped part, under any.
// It reports false when the idiom does not apply.
func (g *gen) listNames() bool {
	if g.paramName != nil {
		return true
	}
	for _, i := range g.idioms {
		if i.Name != "paginated-list" || i.As == "excluded" || i.Content == nil {
			continue
		}
		g.paramName = names(i, "parameters")
		g.envName = names(i, "envelope")
		return true
	}
	return false
}

func names(i Idiom, part string) map[string]string {
	out := map[string]string{}
	pick := func(idiom map[string]any) map[string]any {
		return obj(obj(obj(obj(obj(idiom["parts"])[part])["stack"])["any"])["names"])
	}
	src := pick(i.Content)
	if i.Override != nil {
		ov := obj(i.Override["overrides"])
		replaces := ov["whole"] == true
		for _, p := range list(ov["parts"]) {
			replaces = replaces || text(p) == part
		}
		if o := pick(i.Override); replaces && len(o) > 0 {
			src = o
		}
	}
	for k, v := range src {
		out[k] = text(v)
	}
	return out
}

// The YAML node helpers.

func mapping() *yaml.Node  { return &yaml.Node{Kind: yaml.MappingNode} }
func sequence() *yaml.Node { return &yaml.Node{Kind: yaml.SequenceNode} }
func str(s string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s}
}
func number(s string) *yaml.Node {
	tag := "!!int"
	if strings.ContainsAny(s, ".eE") {
		tag = "!!float"
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: tag, Value: s}
}
func boolean(b bool) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: fmt.Sprint(b)}
}
func ref(target string) *yaml.Node {
	n := mapping()
	add(n, "$ref", str(target))
	return n
}
func add(m *yaml.Node, key string, v *yaml.Node) {
	m.Content = append(m.Content, str(key), v)
}

type pair struct {
	key   string
	value *yaml.Node
}

func pairsOf(m *yaml.Node) []pair {
	var out []pair
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		out = append(out, pair{m.Content[i].Value, m.Content[i+1]})
	}
	return out
}

func child(m *yaml.Node, key string) *yaml.Node {
	for _, p := range pairsOf(m) {
		if p.key == key {
			return p.value
		}
	}
	return nil
}

func setChild(m *yaml.Node, key string, v *yaml.Node) {
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			m.Content[i+1] = v
			return
		}
	}
	add(m, key, v)
}

// plain writes a plain value: maps with sorted keys, lists, and scalars of
// their own type.
func plain(v any) *yaml.Node {
	switch x := v.(type) {
	case map[string]any:
		n := mapping()
		for _, k := range sortedKeys(x) {
			add(n, k, plain(x[k]))
		}
		return n
	case []any:
		n := sequence()
		for _, item := range x {
			n.Content = append(n.Content, plain(item))
		}
		return n
	case json.Number:
		return number(x.String())
	case bool:
		return boolean(x)
	case nil:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!null", Value: "null"}
	}
	return str(text(v))
}

func obj(v any) map[string]any {
	m, _ := v.(map[string]any)
	return m
}

func list(v any) []any {
	l, _ := v.([]any)
	return l
}

func text(v any) string {
	switch x := v.(type) {
	case nil:
		return ""
	case string:
		return x
	case json.Number:
		return x.String()
	case bool:
		return fmt.Sprint(x)
	}
	return fmt.Sprint(v)
}

func joinList(items []any) string {
	var s []string
	for _, i := range items {
		s = append(s, text(i))
	}
	switch len(s) {
	case 0:
		return ""
	case 1:
		return s[0]
	}
	return strings.Join(s[:len(s)-1], ", ") + " and " + s[len(s)-1]
}

func sortedKeys(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
