// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import { forward } from "@/server/forward";
import { server } from "@/server/settings";

/** recordVisits: POST /members/{memberId}/visits, forwarded to the service with the session's token. */
export function POST(request: Request): Promise<Response> {
  return forward(request, server);
}
