// Code generated by specarch-gen-tests-go from ../project/specarch.yaml, version 1.0.0, meta-model 0.1. DO NOT EDIT.

// Package members runs the design tests and worked examples of Members through
// the Harness the project gives them in newHarness.
package members

import (
	"math/big"
	"testing"
)

// Value is a value of the design with its type, as the specification
// writes it: Text is the value's text, Kind its type in the expression
// language (int, uint, double, decimal, string, bool, enum, date,
// timestamp, duration, time, bytes, object, list or null). An object, such
// as a value object, has its parts in Parts and a list its items in Items,
// each with its own type; Text is then the value as JSON.
type Value struct {
	Kind  string
	Text  string
	Parts Record
	Items []Value
}

// Record is a record or an input: values by field or parameter name.
type Record map[string]Value

// Response is what an operation or a page answers.
type Response struct {
	Status int
	Body   Record
}

// Result is what a command run gives.
type Result struct {
	Exit   int
	Output []string
}

// Harness is what the project gives the generated tests, in a file of its
// own beside this one, through func newHarness(t *testing.T) Harness: how
// a caller signs in, how a record is stored and read back, how an operation is
// called, a command run, a page opened and an algorithm computed. Each
// name it takes is the mapping the implementation file gives the element,
// or the element's own name when it gives none. Request gets the path as
// the specification writes it, such as /loans/{loanId}/return; the harness
// fills its parameters from the input record.
type Harness interface {
	SignIn(t *testing.T, role string)
	Insert(t *testing.T, mapping string, r Record)
	Records(t *testing.T, mapping string) []Record
	Request(t *testing.T, mapping, method, path string, in Record) Response
	Run(t *testing.T, mapping, command string, arguments map[string][]Value, options Record) Result
	Open(t *testing.T, mapping, page, route string, in Record) Response
	Emitted(t *testing.T) []string
	Compute(t *testing.T, mapping string, in Record) Value
}

// same reports whether a value got is the value wanted, in its type:
// decimals and numbers by value, an object when it holds every part wanted,
// a list item by item, everything else by text.
func same(a, b Value) bool {
	switch a.Kind {
	case "decimal", "int", "uint", "double":
		x, okx := new(big.Rat).SetString(a.Text)
		y, oky := new(big.Rat).SetString(b.Text)
		return okx && oky && x.Cmp(y) == 0
	case "object":
		return b.Kind == "object" && holds(a.Parts, b.Parts)
	case "list":
		if b.Kind != "list" || len(a.Items) != len(b.Items) {
			return false
		}
		for i := range a.Items {
			if !same(a.Items[i], b.Items[i]) {
				return false
			}
		}
		return true
	}
	return a.Kind == b.Kind && a.Text == b.Text
}

// holds reports whether a record has every value of want.
func holds(r, want Record) bool {
	for k, v := range want {
		if got, ok := r[k]; !ok || !same(got, v) {
			return false
		}
	}
	return true
}

func expectStatus(t *testing.T, r Response, status int) {
	t.Helper()
	if r.Status != status {
		t.Errorf("status %d, want %d", r.Status, status)
	}
}

func expectBody(t *testing.T, r Response, want Record) {
	t.Helper()
	if !holds(r.Body, want) {
		t.Errorf("body %v does not hold %v", r.Body, want)
	}
}

func expectExit(t *testing.T, r Result, exit int) {
	t.Helper()
	if r.Exit != exit {
		t.Errorf("exit %d, want %d", r.Exit, exit)
	}
}

func expectOutput(t *testing.T, r Result, lines []string) {
	t.Helper()
	if len(r.Output) != len(lines) {
		t.Errorf("output %q, want %q", r.Output, lines)
		return
	}
	for i := range lines {
		if r.Output[i] != lines[i] {
			t.Errorf("output %q, want %q", r.Output, lines)
			return
		}
	}
}

func expectState(t *testing.T, h Harness, mapping string, want Record) {
	t.Helper()
	for _, r := range h.Records(t, mapping) {
		if holds(r, want) {
			return
		}
	}
	t.Errorf("no record of %s holds %v", mapping, want)
}

func expectEmitted(t *testing.T, h Harness, messages ...string) {
	t.Helper()
	got := h.Emitted(t)
	for _, m := range messages {
		found := false
		for _, g := range got {
			found = found || g == m
		}
		if !found {
			t.Errorf("%s was not published; published: %v", m, got)
		}
	}
	if len(messages) == 0 && len(got) > 0 {
		t.Errorf("nothing should be published; published: %v", got)
	}
}

func expectValue(t *testing.T, got, want Value) {
	t.Helper()
	if !same(got, want) {
		t.Errorf("got %s %s, want %s %s", got.Kind, got.Text, want.Kind, want.Text)
	}
}

// TestCreateMemberMissingAddressStreet: operation createMember, red scenario.
func TestCreateMemberMissingAddressStreet(t *testing.T) {
	// Given a clerk
	// When createMember is called with an address without its street
	// Then it is refused
	h := newHarness(t)
	h.SignIn(t, "clerk")
	h.Insert(t, "members", Record{"address": Value{Kind: "object", Text: "{\"city\":\"Leeds\",\"location\":{\"latitude\":53.8,\"longitude\":-1.55},\"street\":\"1 High Street\"}", Parts: Record{"city": Value{Kind: "string", Text: "Leeds"}, "location": Value{Kind: "object", Text: "{\"latitude\":53.8,\"longitude\":-1.55}", Parts: Record{"latitude": Value{Kind: "double", Text: "53.8"}, "longitude": Value{Kind: "double", Text: "-1.55"}}}, "street": Value{Kind: "string", Text: "1 High Street"}}}, "id": Value{Kind: "string", Text: "2b1c6f0e-8f5d-4c41-9a7e-1d2f3a4b5c6d"}, "name": Value{Kind: "string", Text: "Ann"}, "phones": Value{Kind: "list", Text: "[{\"number\":\"0113 496 0000\"}]", Items: []Value{Value{Kind: "object", Text: "{\"number\":\"0113 496 0000\"}", Parts: Record{"number": Value{Kind: "string", Text: "0113 496 0000"}}}}}})
	got := h.Request(t, "createMember", "POST", "/members", Record{"address": Value{Kind: "object", Text: "{\"city\":\"Leeds\"}", Parts: Record{"city": Value{Kind: "string", Text: "Leeds"}}}, "name": Value{Kind: "string", Text: "Bob"}})
	expectStatus(t, got, 422)
}

// TestCreateMemberSucceeds: operation createMember, golden scenario.
func TestCreateMemberSucceeds(t *testing.T) {
	// Given a clerk
	// When createMember is called
	// Then it answers 201
	h := newHarness(t)
	h.SignIn(t, "clerk")
	got := h.Request(t, "createMember", "POST", "/members", Record{"address": Value{Kind: "object", Text: "{\"city\":\"York\",\"street\":\"2 Low Lane\"}", Parts: Record{"city": Value{Kind: "string", Text: "York"}, "street": Value{Kind: "string", Text: "2 Low Lane"}}}, "name": Value{Kind: "string", Text: "Bob"}, "phones": Value{Kind: "list", Text: "[{\"number\":\"01904 000000\"}]", Items: []Value{Value{Kind: "object", Text: "{\"number\":\"01904 000000\"}", Parts: Record{"number": Value{Kind: "string", Text: "01904 000000"}}}}}})
	expectStatus(t, got, 201)
	expectBody(t, got, Record{"address": Value{Kind: "object", Text: "{\"city\":\"York\",\"street\":\"2 Low Lane\"}", Parts: Record{"city": Value{Kind: "string", Text: "York"}, "street": Value{Kind: "string", Text: "2 Low Lane"}}}, "name": Value{Kind: "string", Text: "Bob"}})
}
