// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
"use client";

import {
  Button,
  ButtonSet,
  Form,
  FormGroup,
  InlineLoading,
  InlineNotification,
  ProgressIndicator,
  ProgressStep,
  Stack,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
} from "@carbon/react";
import { useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { ChildRows, rowProblems, rowsSent, startRows, type RowsState } from "./ChildRows";
import { Field } from "./Field";
import { leave } from "./Notice";
import { againOf, formProblems, hidden, locked, recordOf, typed, type Fields, type Values } from "./rules";
import type { EventSchema, FailureSchema, FieldSchema, FormFieldSchema, FormPageSchema, SectionSchema } from "./schema";
import { body, segment, service } from "./service";
import { say, type Texts } from "./texts";
import { ValueField } from "./ValueField";
import { firstProblem, holdsValue, scalars, sentValue, startValue, valueProblems } from "./values";

/** The value a field starts with, worked out from the record the form loaded, or from none on a form that creates one. */
export type FieldHook = (record: Fields) => string;

export interface FormPageProps {
  readonly schema: FormPageSchema;
  readonly texts: Texts;
  readonly routes: Readonly<Record<string, string>>;
  /** The page's route parameters. */
  readonly parameters?: Readonly<Record<string, string>>;
  /** The hooks of the fields the schema marks, by field. */
  readonly hooks?: Readonly<Record<string, FieldHook>>;
}

/** A path with its parameters taken from values by name. */
function fill(path: string, values: Fields): string {
  return path.replace(/\{([^}]+)\}/g, (_, name: string) => segment(String(values[name] ?? "")));
}

/** A field's value as the form holds it: text, with a boolean as "true" or "false". */
function held(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }
  return String(value);
}

function refusal(failed: readonly FailureSchema[], status: number): FailureSchema | undefined {
  return failed.find((f) => f.status === status) ?? failed.find((f) => f.status === undefined);
}

function fieldsOf(sections: readonly SectionSchema<FormFieldSchema>[]): readonly FormFieldSchema[] {
  return sections.flatMap((section) => section.fields);
}

/** The rows of each child relation a form starts with, by the relation's name. */
function startAll(schema: FormPageSchema, record: Fields): Readonly<Record<string, RowsState>> {
  return Object.fromEntries(schema.rows.map((rows) => [rows.name, startRows(rows, record)]));
}

/** The values a form starts with: the loaded record's, then each hook's; a value's parts and a list's items by their paths. */
function start(fields: readonly FormFieldSchema[], record: Fields, hooks: Readonly<Record<string, FieldHook>>): Values {
  const values: Record<string, string> = {};
  for (const field of fields) {
    if (holdsValue(field)) {
      startValue(field, record[field.name], field.name, values);
      continue;
    }
    const hook = field.hook === true ? hooks[field.name] : undefined;
    values[field.name] = hook !== undefined ? hook(record) : field.type === "checkbox" ? held(record[field.name] ?? false) : held(record[field.name]);
    if (field.twice !== undefined) {
      values[againOf(field)] = values[field.name] ?? "";
    }
  }
  return values;
}

/**
 * A form that creates a record, or loads one from its source and changes
 * it: its sections on one page, as tabs or as steps, each field checked by
 * its keywords and the page's checks before the request is sent, and each
 * success leading where its event says.
 */
export function FormPage({ schema, texts, routes, parameters, hooks }: FormPageProps) {
  const router = useRouter();
  const fields = fieldsOf(schema.sections);
  const [loaded, setLoaded] = useState<Fields | undefined>(() => (schema.source === undefined ? {} : undefined));
  const [loadFailed, setLoadFailed] = useState<string | undefined>(undefined);
  const [values, setValues] = useState<Values>(() => (schema.source === undefined ? start(fieldsOf(schema.sections), {}, hooks ?? {}) : {}));
  const [rows, setRows] = useState<Readonly<Record<string, RowsState>>>(() => (schema.source === undefined ? startAll(schema, {}) : {}));
  const [problems, setProblems] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  const [step, setStep] = useState(0);
  const [key, setKey] = useState(() => crypto.randomUUID());

  useEffect(() => {
    if (schema.source === undefined) {
      return;
    }
    const source = schema.source;
    let current = true;
    fetch(service + fill(source.path, parameters ?? {}), { credentials: "include", headers: { Accept: "application/json" } })
      .then(async (response) => {
        const answer = response.ok ? await body(response) : undefined;
        if (!current) {
          return;
        }
        if (typeof answer !== "object" || answer === null) {
          setLoadFailed(say(texts, refusal(source.failed, response.status)?.message ?? "screens.failed"));
          return;
        }
        const record = answer as Fields;
        setLoaded(record);
        setValues(start(fieldsOf(schema.sections), record, hooks ?? {}));
        setRows(startAll(schema, record));
      })
      .catch(() => {
        if (current) {
          setLoadFailed(say(texts, "screens.failed"));
        }
      });
    return () => {
      current = false;
    };
  }, [schema, parameters, hooks, texts]);

  if (loadFailed !== undefined) {
    return <InlineNotification kind="error" role="alert" lowContrast hideCloseButton title={loadFailed} />;
  }
  if (loaded === undefined) {
    return <InlineLoading description={say(texts, "screens.loading")} />;
  }
  const record: Fields = {
    ...recordOf(scalars(fields), values, loaded),
    ...Object.fromEntries(fields.filter(holdsValue).map((field) => [field.name, sentValue(field, values, field.name)])),
  };

  /** Whether a problem was found under a field: its own, its second entry's, or a part's of its value. */
  function holds(field: FormFieldSchema, found: Readonly<Record<string, string>>): boolean {
    return firstProblem(field, found) !== undefined;
  }

  function check(only: readonly FormFieldSchema[]): Record<string, string> {
    const found = formProblems(scalars(only), only === fields ? schema.checks : [], values, record, texts);
    for (const field of only.filter(holdsValue)) {
      if (!hidden(field, record) && !locked(field, record)) {
        valueProblems(field, values, field.name, texts, found);
      }
    }
    const inRows: Record<string, string> = {};
    if (only === fields) {
      for (const child of schema.rows) {
        Object.assign(inRows, rowProblems(child, rows[child.name] ?? { loaded: [], added: [] }, texts));
      }
    }
    setProblems({ ...inRows, ...found });
    const first = only.map((field) => firstProblem(field, found)).find((key) => key !== undefined);
    if (first !== undefined) {
      document.getElementById(first)?.focus();
    } else {
      const firstRow = Object.keys(inRows)[0];
      if (firstRow !== undefined) {
        document.getElementById(firstRow)?.focus();
      }
    }
    return { ...inRows, ...found };
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (schema.layout === "steps" && step < schema.sections.length - 1) {
      if (Object.keys(check(schema.sections[step]?.fields ?? [])).length === 0) {
        setStep(step + 1);
      }
      return;
    }
    const found = check(fields);
    if (Object.keys(found).length > 0) {
      const at = schema.sections.findIndex((section) => section.fields.some((field) => holds(field, found)));
      if (at >= 0) {
        setStep(at);
      } else if (schema.layout === "steps") {
        setStep(schema.sections.length - 1); // the rows are on the last step
      }
      return;
    }
    setBusy(true);
    const sent: Record<string, unknown> = {};
    for (const field of fields) {
      const value = holdsValue(field) ? sentValue(field, values, field.name) : typed(field, values[field.name] ?? "");
      if (schema.submit.fields.includes(field.name) && !hidden(field, record) && value !== null) {
        sent[field.name] = value;
      }
    }
    for (const child of schema.rows) {
      sent[child.name] = rowsSent(child, rows[child.name] ?? { loaded: [], added: [] });
    }
    const headers: Record<string, string> = { "Content-Type": "application/json", Accept: "application/json, application/problem+json" };
    if (schema.submit.idempotencyKey !== undefined) {
      headers[schema.submit.idempotencyKey] = key;
    }
    let response: Response;
    try {
      response = await fetch(service + fill(schema.submit.path, { ...loaded, ...parameters }), {
        method: schema.submit.method,
        headers,
        credentials: "include",
        body: JSON.stringify(sent),
      });
    } catch {
      setBusy(false);
      setProblems({ "": say(texts, "screens.failed") });
      return;
    }
    // An answer came, so the key is used: a request sent with it again is
    // answered as this one was, so the next is a new request with a new key.
    // A request that got no answer keeps it, and its retry is safe.
    setKey(crypto.randomUUID());
    if (response.ok) {
      const success: EventSchema =
        schema.events.find((candidate) => candidate.status === response.status) ??
        schema.events.find((candidate) => candidate.status === undefined) ??
        {};
      const answer = await body(response);
      const from: Fields = { ...loaded, ...parameters, ...(typeof answer === "object" && answer !== null ? (answer as Fields) : {}) };
      const route =
        success.navigate === undefined
          ? undefined
          : (routes[success.navigate] ?? "/").replace(/\{([^}]+)\}/g, (_, name: string) => segment(String(from[success.with?.[name] ?? name] ?? "")));
      if (success.message !== undefined) {
        leave(say(texts, success.message), (route ?? window.location.pathname).split(/[?#]/)[0]);
      }
      if (route !== undefined) {
        router.push(route);
        return;
      }
      setBusy(false);
      return;
    }
    setBusy(false);
    const failure = refusal(schema.failed, response.status);
    if (failure === undefined) {
      setProblems({ "": say(texts, "screens.failed") });
    } else {
      setProblems({ [failure.field ?? ""]: say(texts, failure.message) });
      if (failure.field !== undefined) {
        document.getElementById(failure.field)?.focus();
      }
    }
  }

  function change(name: string, value: string) {
    setValues((current) => ({ ...current, [name]: value }));
  }

  function pick(field: FieldSchema, picked: Fields) {
    if (field.type !== "lookup") {
      return;
    }
    setValues((current) => {
      const next: Record<string, string> = { ...current };
      for (const [into, from] of Object.entries(field.fills)) {
        next[into] = held(picked[from]);
      }
      return next;
    });
  }

  function drawn(section: SectionSchema<FormFieldSchema>): ReactNode {
    const shown = section.fields.filter((field) => !hidden(field, record));
    const group = (
      <Stack gap={6}>
        {shown.map((field) =>
          holdsValue(field) ? (
            <ValueField
              key={field.name}
              field={field}
              path={field.name}
              values={values}
              problems={problems}
              texts={texts}
              readOnly={locked(field, record)}
              onValues={(change) => setValues(change)}
            />
          ) : (
            drawnField(field)
          ),
        )}
      </Stack>
    );
    return section.title === undefined ? group : <FormGroup legendText={say(texts, section.title)}>{group}</FormGroup>;
  }

  function drawnField(field: FieldSchema): ReactNode {
    return [
      <Field
        key={field.name}
        field={field}
        value={values[field.name] ?? ""}
        problem={problems[field.name]}
        texts={texts}
        readOnly={locked(field, record)}
        onChange={(value) => change(field.name, value)}
        onPick={(picked) => pick(field, picked)}
      />,
      field.twice !== undefined && !locked(field, record) ? (
        <Field
          key={againOf(field)}
          field={field}
          value={values[againOf(field)] ?? ""}
          problem={problems[againOf(field)]}
          texts={texts}
          again={{ id: againOf(field), label: say(texts, field.twice) }}
          onChange={(value) => change(againOf(field), value)}
        />
      ) : null,
    ];
  }

  const last = schema.layout !== "steps" || step === schema.sections.length - 1;
  const children = schema.rows.map((child) => (
    <ChildRows
      key={child.name}
      rows={child}
      state={rows[child.name] ?? { loaded: [], added: [] }}
      problems={problems}
      texts={texts}
      onChange={(added) => setRows((current) => ({ ...current, [child.name]: { loaded: current[child.name]?.loaded ?? [], added } }))}
    />
  ));
  let content: ReactNode;
  switch (schema.layout) {
    case "tabs":
      content = (
        <Tabs selectedIndex={step} onChange={({ selectedIndex }) => setStep(selectedIndex)}>
          <TabList aria-label={say(texts, schema.title)}>
            {schema.sections.map((section, index) => (
              <Tab key={index}>{section.title === undefined ? String(index + 1) : say(texts, section.title)}</Tab>
            ))}
          </TabList>
          <TabPanels>
            {schema.sections.map((section, index) => (
              <TabPanel key={index}>{drawn(section)}</TabPanel>
            ))}
          </TabPanels>
        </Tabs>
      );
      break;
    case "steps":
      content = (
        <Stack gap={6}>
          <ProgressIndicator currentIndex={step}>
            {schema.sections.map((section, index) => (
              <ProgressStep key={index} label={section.title === undefined ? String(index + 1) : say(texts, section.title)} complete={index < step} />
            ))}
          </ProgressIndicator>
          {drawn(schema.sections[step] ?? { fields: [] })}
        </Stack>
      );
      break;
    case "page":
      content = <Stack gap={7}>{schema.sections.map((section, index) => <div key={index}>{drawn(section)}</div>)}</Stack>;
      break;
  }

  return (
    <section className="screens-form">
      <h1>{say(texts, schema.title)}</h1>
      <Form noValidate onSubmit={submit}>
        <Stack gap={6}>
          {problems[""] !== undefined && <InlineNotification kind="error" role="alert" lowContrast hideCloseButton title={problems[""]} />}
          {content}
          {last && children}
          <ButtonSet>
            {schema.layout === "steps" && step > 0 && (
              <Button kind="secondary" type="button" onClick={() => setStep(step - 1)}>
                {say(texts, "screens.back")}
              </Button>
            )}
            <Button type="submit" disabled={busy}>
              {last ? say(texts, schema.title) : say(texts, "screens.next")}
            </Button>
          </ButtonSet>
        </Stack>
      </Form>
    </section>
  );
}
