// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
"use client";

import { Button, Form, InlineNotification, Stack } from "@carbon/react";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { Field } from "./Field";
import { leave } from "./Notice";
import { problemsOf, type Values } from "./rules";
import type { EventSchema, TaskPageSchema } from "./schema";
import { say, type Texts } from "./texts";

/** Where the service is, empty when it answers on the page's own origin. */
const service = process.env.NEXT_PUBLIC_API_URL ?? "";

export interface TaskPageProps {
  readonly schema: TaskPageSchema;
  readonly texts: Texts;
  readonly routes: Readonly<Record<string, string>>;
  readonly returnTo?: string;
}

/** A path on this site, never another origin. */
function local(path: string | undefined): path is string {
  return path !== undefined && path.startsWith("/") && !path.startsWith("//") && !path.startsWith("/\\");
}

function destination(event: EventSchema, routes: Readonly<Record<string, string>>, body: unknown, returnTo?: string): string | undefined {
  if (event.navigate === undefined) {
    return undefined;
  }
  if (!event.keepsReturnTo && local(returnTo)) {
    return returnTo;
  }
  const answer = typeof body === "object" && body !== null ? (body as Record<string, unknown>) : {};
  let route = (routes[event.navigate] ?? "/").replace(/\{([^}]+)\}/g, (_, name: string) =>
    encodeURIComponent(String(answer[event.with?.[name] ?? name] ?? "")),
  );
  if (event.keepsReturnTo && local(returnTo)) {
    route += "?returnTo=" + encodeURIComponent(returnTo);
  }
  return route;
}

/**
 * A form that sends its fields to an operation without loading a record,
 * and goes where the answer leads.
 */
export function TaskPage({ schema, texts, routes, returnTo }: TaskPageProps) {
  const router = useRouter();
  const [values, setValues] = useState<Values>(() => Object.fromEntries(schema.fields.map((field) => [field.name, ""])));
  const [problems, setProblems] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const found = problemsOf(schema, values, texts);
    setProblems(found);
    const first = schema.fields.find((field) => found[field.name] !== undefined);
    if (first !== undefined) {
      document.getElementById(first.name)?.focus();
    }
    if (Object.keys(found).length > 0) {
      return;
    }
    setBusy(true);
    const body = Object.fromEntries(Object.entries(values).filter(([, value]) => value !== ""));
    let response: Response;
    try {
      response = await fetch(service + schema.submit.path, {
        method: schema.submit.method,
        headers: { "Content-Type": "application/json", Accept: "application/json, application/problem+json" },
        credentials: "include",
        body: JSON.stringify(body),
      });
    } catch {
      setBusy(false);
      setProblems({ "": say(texts, "screens.failed") });
      return;
    }
    const success = response.ok ? schema.events.find((candidate) => candidate.status === response.status) : undefined;
    if (success !== undefined) {
      const answer: unknown = success.with === undefined ? null : await response.json().catch(() => null);
      const route = destination(success, routes, answer, returnTo);
      if (success.message !== undefined) {
        leave(say(texts, success.message), (route ?? window.location.pathname).split(/[?#]/)[0]);
      }
      if (route !== undefined) {
        router.push(route);
        return;
      }
      setBusy(false);
      setValues(Object.fromEntries(schema.fields.map((field) => [field.name, ""])));
      return;
    }
    setBusy(false);
    const failure = schema.failed.find((candidate) => candidate.status === response.status);
    if (failure === undefined) {
      setProblems({ "": say(texts, "screens.failed") });
    } else {
      setProblems({ [failure.field ?? ""]: say(texts, failure.message) });
      if (failure.field !== undefined) {
        document.getElementById(failure.field)?.focus();
      }
    }
  }

  return (
    <section className="screens-task">
      <h1>{say(texts, schema.title)}</h1>
      <Form noValidate onSubmit={submit}>
        <Stack gap={6}>
          {problems[""] !== undefined && (
            <InlineNotification kind="error" role="alert" lowContrast hideCloseButton title={problems[""]} />
          )}
          {schema.fields.map((field) => (
            <Field
              key={field.name}
              field={field}
              value={values[field.name] ?? ""}
              problem={problems[field.name]}
              texts={texts}
              onChange={(value) => setValues((current) => ({ ...current, [field.name]: value }))}
            />
          ))}
          <Button type="submit" disabled={busy}>
            {say(texts, schema.title)}
          </Button>
        </Stack>
      </Form>
    </section>
  );
}
