// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
"use client";

import {
  Button,
  ButtonSet,
  InlineLoading,
  InlineNotification,
  Stack,
  StructuredListBody,
  StructuredListCell,
  StructuredListRow,
  StructuredListWrapper,
} from "@carbon/react";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { decide } from "./access";
import { Confirm, runAction } from "./Confirm";
import { leave } from "./Notice";
import { evaluate, hidden, type Fields } from "./rules";
import type { FailureSchema, RowActionSchema, ViewPageSchema } from "./schema";
import { body, segment, service } from "./service";
import { useSession } from "./session";
import { say, type Texts } from "./texts";

export interface ViewPageProps {
  readonly schema: ViewPageSchema;
  readonly texts: Texts;
  readonly routes: Readonly<Record<string, string>>;
  /** The page's route parameters. */
  readonly parameters?: Readonly<Record<string, string>>;
}

function fill(path: string, values: Fields): string {
  return path.replace(/\{([^}]+)\}/g, (_, name: string) => segment(String(values[name] ?? "")));
}

function refusal(failed: readonly FailureSchema[], status: number): FailureSchema | undefined {
  return failed.find((f) => f.status === status) ?? failed.find((f) => f.status === undefined);
}

function shown(value: unknown, texts: Texts): string {
  if (value === null || value === undefined || value === "") {
    return say(texts, "screens.none");
  }
  if (typeof value === "boolean") {
    return say(texts, value ? "screens.yes" : "screens.no");
  }
  return String(value);
}

/**
 * One record read from the view's source, its sections shown read-only,
 * with the actions that open a page offered to whoever holds their
 * permission, and those that run an operation on the record offered while
 * their rule holds for it too; a success reads the record again.
 */
export function ViewPage({ schema, texts, routes, parameters }: ViewPageProps) {
  const router = useRouter();
  const pathname = usePathname();
  const session = useSession();
  const [record, setRecord] = useState<Fields | undefined>(undefined);
  const [failed, setFailed] = useState<string | undefined>(undefined);
  const [reload, setReload] = useState(0);
  const [confirming, setConfirming] = useState<RowActionSchema | undefined>(undefined);
  const [reason, setReason] = useState("");
  const [running, setRunning] = useState(false);
  const [refused, setRefused] = useState("");

  useEffect(() => {
    let current = true;
    fetch(service + fill(schema.source.path, parameters ?? {}), { credentials: "include", headers: { Accept: "application/json" } })
      .then(async (response) => {
        const answer = response.ok ? await body(response) : undefined;
        if (!current) {
          return;
        }
        if (typeof answer === "object" && answer !== null) {
          setRecord(answer as Fields);
        } else {
          setFailed(say(texts, refusal(schema.source.failed, response.status)?.message ?? "screens.failed"));
        }
      })
      .catch(() => {
        if (current) {
          setFailed(say(texts, "screens.failed"));
        }
      });
    return () => {
      current = false;
    };
  }, [schema, parameters, texts, reload]);

  if (failed !== undefined) {
    return <InlineNotification kind="error" role="alert" lowContrast hideCloseButton title={failed} />;
  }
  if (record === undefined) {
    return <InlineLoading description={say(texts, "screens.loading")} />;
  }
  const holds = (permission: string) => session !== undefined && session !== null && decide(permission, session) === "allowed";
  const offered = schema.actions.filter((action) => holds(action.permission));
  const runs = schema.operations.filter((action) => holds(action.permission) && (action.when === undefined || evaluate(action.when, record) === true));

  async function run(action: RowActionSchema) {
    if (action.reason !== undefined && reason.trim() === "") {
      return;
    }
    setRunning(true);
    const answer = await runAction(action, { ...parameters, ...record }, reason, texts);
    if (answer === undefined) {
      setRefused("");
      if (action.message !== undefined) {
        leave(say(texts, action.message), pathname);
      }
      setReload((n) => n + 1);
    } else {
      setRefused(answer);
    }
    setRunning(false);
    setConfirming(undefined);
    setReason("");
  }

  function start(action: RowActionSchema) {
    setReason("");
    if (action.confirm === undefined) {
      void run(action);
    } else {
      setConfirming(action);
    }
  }

  return (
    <section className="screens-view">
      <h1>{say(texts, schema.title)}</h1>
      {refused !== "" && <InlineNotification kind="error" role="alert" lowContrast title={refused} onClose={() => setRefused("")} />}
      <Stack gap={7}>
        {schema.sections.map((section, index) => (
          <div key={index}>
            {section.title !== undefined && <h2>{say(texts, section.title)}</h2>}
            <StructuredListWrapper isCondensed aria-label={section.title === undefined ? say(texts, schema.title) : say(texts, section.title)}>
              <StructuredListBody>
                {section.fields
                  .filter((field) => !hidden(field, record))
                  .map((field) => (
                    <StructuredListRow key={field.name}>
                      <StructuredListCell>{say(texts, field.label)}</StructuredListCell>
                      <StructuredListCell>{shown(record[field.name], texts)}</StructuredListCell>
                    </StructuredListRow>
                  ))}
              </StructuredListBody>
            </StructuredListWrapper>
          </div>
        ))}
        {offered.length + runs.length > 0 && (
          <ButtonSet>
            {offered.map((action) => (
              <Button
                key={action.navigate}
                kind="secondary"
                onClick={() => router.push(fill(routes[action.navigate] ?? "/", { ...parameters, ...record }))}
              >
                {say(texts, action.label)}
              </Button>
            ))}
            {runs.map((action) => (
              <Button key={action.operation} kind={action.confirm === undefined ? "secondary" : "danger"} disabled={running} onClick={() => start(action)}>
                {say(texts, action.label)}
              </Button>
            ))}
          </ButtonSet>
        )}
      </Stack>
      {confirming?.confirm !== undefined && (
        <Confirm
          action={{ ...confirming, confirm: confirming.confirm }}
          texts={texts}
          reason={reason}
          running={running}
          onReason={setReason}
          onConfirm={() => void run(confirming)}
          onClose={() => setConfirming(undefined)}
        />
      )}
    </section>
  );
}
