// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/0.1.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: generator: the picker of bookId reads listBooks, which searches no field, so it offers the first 100 records and finds among them only [generator@design/pages/loan-form.yaml#/pages/loan-form/pickers/bookId/source]
import type { Metadata } from "next";
import { Guard } from "@/screens";
import { chosenLanguage } from "@/language";
import { stringOf, texts } from "@/strings";
import { HookedForm } from "./page.client";
import { schema } from "./page.schema";

export async function generateMetadata(): Promise<Metadata> {
  return { title: stringOf("loan-form.title", await chosenLanguage()) };
}

const routes = {
  "member-view": "/members/{memberId}",
};

export default async function Page() {
  const t = texts(schema, await chosenLanguage());
  return (
    <Guard permission={schema.permission} texts={t}>
      <HookedForm schema={schema} texts={t} routes={routes} />
    </Guard>
  );
}
