// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/0.1.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: generator: the picker of bookId reads listBooks, which searches no field, so it offers the first 100 records and finds among them only [generator@design/pages/loan-form.yaml#/pages/loan-form/pickers/bookId/source]
"use client";

import type { ComponentProps } from "react";
import { FormPage } from "@/screens";
import { lentOn } from "./page.hooks";

const hooks = { lentOn };

/** The form with the hooks of its fields, which run in the browser. */
export function HookedForm(props: Omit<ComponentProps<typeof FormPage>, "hooks">) {
  return <FormPage {...props} hooks={hooks} />;
}
