// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { Metadata } from "next";
import { Guard } from "@/screens";
import { strings, texts } from "@/strings";
import { HookedForm } from "./page.client";
import { schema } from "./page.schema";

export const metadata: Metadata = { title: strings["loan-form.title"] };

const routes = {
  "member-view": "/members/{memberId}",
};

export default function Page() {
  const t = texts(schema);
  return (
    <Guard permission={schema.permission} texts={t}>
      <HookedForm schema={schema} texts={t} routes={routes} />
    </Guard>
  );
}
