// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import assert from "node:assert/strict";
import { test } from "node:test";
import { decide } from "../screens/access.ts";
import { schema } from "../app/members/[memberId]/edit/page.schema.ts";

test("member-edit is refused to someone signed in without members.write", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: [] }), "refused");
});

test("member-edit sends someone signed out to sign in", () => {
  assert.equal(decide(schema.permission, { signedIn: false, permissions: [] }), "sign-in");
});

test("member-edit opens to someone who holds members.write", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: ["members.write"] }), "allowed");
});
