// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page member-form has no red scenario for "violates notes-not-the-name"; add under tests member-form-violates-notes-not-the-name: { page: member-form, scenario: red, covers: [violates notes-not-the-name], given: "...", when: "the form is submitted breaking it", then: "it is not sent: The notes repeat the name." } [test_case_missing.1ee0813c@specarch.yaml#/pages/member-form]
// specarch-problem: warning: test_case_missing: page member-form has no red scenario for "denied with expired session"; add under tests member-form-denied-with-expired-session: { page: member-form, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page member-form is opened", then: "it is refused as not signed in" } [test_case_missing.4453c8b5@specarch.yaml#/pages/member-form]
// specarch-problem: warning: test_case_missing: page member-form has no red scenario for "pin entered twice differently"; add under tests member-form-pin-entered-twice-differently: { page: member-form, scenario: red, covers: [pin entered twice differently], given: "...", when: "the form is submitted with two different entries of pin", then: "it is not sent, and says the two entries differ" } [test_case_missing.48e7da62@specarch.yaml#/pages/member-form]
// specarch-problem: warning: test_case_missing: page member-form has no red scenario for "denied without members.write"; add under tests member-form-denied-without-members-write: { page: member-form, scenario: red, covers: [denied without members.write], given: "a caller without members.write", when: "the page member-form is opened", then: "it is refused as not allowed" } [test_case_missing.c6088d4e@specarch.yaml#/pages/member-form]
// specarch-problem: warning: test_golden_missing: page member-form has no golden scenario; add one under tests, for example member-form-succeeds: { page: member-form, scenario: golden, given: "a caller with members.write", when: "the page member-form is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/member-form]
import assert from "node:assert/strict";
import { test } from "node:test";
import { decide } from "../screens/access.ts";
import { schema } from "../app/members/new/page.schema.ts";

test("member-form is refused to someone signed in without members.write", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: [] }), "refused");
});

test("member-form sends someone signed out to sign in", () => {
  assert.equal(decide(schema.permission, { signedIn: false, permissions: [] }), "sign-in");
});

test("member-form opens to someone who holds members.write", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: ["members.write"] }), "allowed");
});
