// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page member-view has no red scenario for "denied with expired session"; add under tests member-view-denied-with-expired-session: { page: member-view, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page member-view is opened", then: "it is refused as not signed in" } [test_case_missing.266f9d87@specarch.yaml#/pages/member-view]
// specarch-problem: warning: test_case_missing: page member-view has no red scenario for "denied without members.read"; add under tests member-view-denied-without-members-read: { page: member-view, scenario: red, covers: [denied without members.read], given: "a caller without members.read", when: "the page member-view is opened", then: "it is refused as not allowed" } [test_case_missing.55e4f79c@specarch.yaml#/pages/member-view]
// specarch-problem: warning: test_case_missing: page member-view has no red scenario for "Suspend without a reason"; add under tests member-view-suspend-without-a-reason: { page: member-view, scenario: red, covers: [Suspend without a reason], given: "...", when: "the action Suspend is confirmed with no why", then: "it is not sent, and the why is asked for" } [test_case_missing.8c60283d@specarch.yaml#/pages/member-view]
// specarch-problem: warning: test_case_missing: page member-view has no red scenario for "not found memberId"; add under tests member-view-not-found-member-id: { page: member-view, scenario: red, covers: [not found memberId], given: "no record has that memberId", when: "the page member-view is opened for that memberId", then: "it says the record was not found" } [test_case_missing.9ca0c671@specarch.yaml#/pages/member-view]
// specarch-problem: warning: test_golden_missing: page member-view has no golden scenario; add one under tests, for example member-view-succeeds: { page: member-view, scenario: golden, given: "a caller with members.read", when: "the page member-view is opened for a record that exists", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/member-view]
import assert from "node:assert/strict";
import { test } from "node:test";
import { decide } from "../screens/access.ts";
import { schema } from "../app/members/[memberId]/page.schema.ts";

test("member-view is refused to someone signed in without members.read", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: [] }), "refused");
});

test("member-view sends someone signed out to sign in", () => {
  assert.equal(decide(schema.permission, { signedIn: false, permissions: [] }), "sign-in");
});

test("member-view opens to someone who holds members.read", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: ["members.read"] }), "allowed");
});
