// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page removals-inbox has no red scenario for "denied with expired session"; add under tests removals-inbox-denied-with-expired-session: { page: removals-inbox, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page removals-inbox is opened", then: "it is refused as not signed in" } [test_case_missing.2799a001@specarch.yaml#/pages/removals-inbox]
// specarch-problem: warning: test_case_missing: page removals-inbox has no red scenario for "denied without members.approve"; add under tests removals-inbox-denied-without-members-approve: { page: removals-inbox, scenario: red, covers: [denied without members.approve], given: "a caller without members.approve", when: "the page removals-inbox is opened", then: "it is refused as not allowed" } [test_case_missing.d817f24c@specarch.yaml#/pages/removals-inbox]
// specarch-problem: warning: test_golden_missing: page removals-inbox has no golden scenario; add one under tests, for example removals-inbox-succeeds: { page: removals-inbox, scenario: golden, given: "a caller with members.approve", when: "the page removals-inbox is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/removals-inbox]
import assert from "node:assert/strict";
import { test } from "node:test";
import { decide } from "../screens/access.ts";
import { schema } from "../app/removals/page.schema.ts";

test("removals-inbox is refused to someone signed in without members.approve", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: [] }), "refused");
});

test("removals-inbox sends someone signed out to sign in", () => {
  assert.equal(decide(schema.permission, { signedIn: false, permissions: [] }), "sign-in");
});

test("removals-inbox opens to someone who holds members.approve", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: ["members.approve"] }), "allowed");
});
