// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { FormPageSchema } from "@/screens";

export const schema = {
  title: "member-edit.title",
  permission: "members.write",
  source: {
    operation: "getMember",
    path: "/members/{memberId}",
    failed: [{ status: 404, problem: "member-gone", message: "member-edit.failed.member-gone" }],
  },
  submit: { operation: "updateMember", method: "PUT", path: "/members/{memberId}", fields: ["name", "status"] },
  layout: "page",
  sections: [
    {
      fields: [
        { type: "date", name: "joinedOn", label: "member-edit.fields.joinedOn", required: false, readOnly: true },
        {
          type: "text",
          name: "name",
          label: "member-edit.fields.name",
          required: true,
          minLength: 1,
          maxLength: 100,
          readOnlyWhen: ["==", ["field", "status"], ["value", "inactive"]],
        },
        { type: "select", name: "status", label: "member-edit.fields.status", required: true, options: ["active", "inactive"] },
      ],
    },
  ],
  checks: [],
  failed: [{ status: 404, problem: "member-gone", message: "member-edit.failed.member-gone" }],
  events: [{ navigate: "member-view", with: { memberId: "id" }, message: "member-edit.onSubmitted" }],
} satisfies FormPageSchema;
