// Generated by specarch-gen-ui-typescript from ../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { TaskPageSchema } from "@/screens";

export const schema = {
  title: "reset-password.title",
  submit: { operation: "resetPassword", method: "POST", path: "/password-resets" },
  fields: [
    { type: "text", name: "code", label: "reset-password.fields.code", required: true, minLength: 1, maxLength: 200 },
    {
      type: "password",
      name: "newPassword",
      label: "reset-password.fields.newPassword",
      required: true,
      minLength: 8,
      maxLength: 200,
      rules: [
        { text: "screens.minLength", count: 8 },
        { text: "screens.maxLength", count: 200 },
      ],
    },
    {
      type: "password",
      name: "confirmPassword",
      label: "reset-password.fields.confirmPassword",
      required: true,
      minLength: 8,
      maxLength: 200,
      rules: [
        { text: "screens.minLength", count: 8 },
        { text: "screens.maxLength", count: 200 },
      ],
    },
  ],
  checks: [
    {
      name: "confirmation-matches",
      rule: ["==", ["field", "confirmPassword"], ["field", "newPassword"]],
      message: "reset-password.checks.confirmation-matches",
      field: "confirmPassword",
    },
  ],
  failed: [{ status: 409, problem: "reset-code-refused", message: "reset-password.failed.reset-code-refused", field: "code" }],
  events: [{ status: 204, navigate: "sign-in", message: "reset-password.onSubmitted.204", keepsReturnTo: true }],
} satisfies TaskPageSchema;
