// Generated by specarch-gen-ui-typescript from ../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { Metadata } from "next";
import { TaskPage } from "@/screens";
import { strings, texts } from "@/strings";
import { schema } from "./page.schema";

export const metadata: Metadata = { title: strings["reset-password.title"] };

const routes = {
  "sign-in": "/sign-in",
};

export default async function Page({ searchParams }: { readonly searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { returnTo } = await searchParams;
  return <TaskPage schema={schema} texts={texts(schema)} routes={routes} returnTo={typeof returnTo === "string" ? returnTo : undefined} />;
}
