// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
/**
 * Every text the screens show, by string key: in the specification's
 * language, en, and in each translation, read from its file beside this one.
 */
export const languages = ["en"] as const;

export type Language = (typeof languages)[number];

/** The cookie that keeps the language a person chose, across sessions. */
export const languageCookie = "language";

export const strings = {
  "directory.columns.name": "Name",
  "directory.empty": "No member yet.",
  "directory.filteredEmpty": "Nothing matches these filters.",
  "directory.title": "Directory",
  "invitation.checks.not-the-invitation": "Choose a password of your own.",
  "invitation.checks.repeated": "The two passwords differ.",
  "invitation.failed.invitation-used": "This invitation was used before.",
  "invitation.fields.invitation": "Invitation",
  "invitation.fields.nickname": "nickname",
  "invitation.fields.password": "Password",
  "invitation.fields.repeat": "Password again",
  "invitation.onSubmitted.204": "Your account is ready. Sign in.",
  "invitation.title": "Accept your invitation",
  "member-edit.failed.member-gone": "That member is gone.",
  "member-edit.fields.joinedOn": "Joined on",
  "member-edit.fields.name": "Name",
  "member-edit.fields.status": "Status",
  "member-edit.onSubmitted": "The member is changed.",
  "member-edit.title": "Change a member",
  "member-form.checks.notes-not-the-name": "The notes repeat the name.",
  "member-form.fields.homeBranchId": "Home branch",
  "member-form.fields.joinedOn": "Joined on",
  "member-form.fields.name": "Name",
  "member-form.fields.newsletter": "Newsletter",
  "member-form.fields.notes": "Notes",
  "member-form.fields.pin": "PIN",
  "member-form.fields.pin.again": "PIN again",
  "member-form.fields.status": "Status",
  "member-form.fields.visits": "Visits",
  "member-form.onSubmitted": "The member is registered.",
  "member-form.sections.0": "Who",
  "member-form.sections.1": "More",
  "member-form.title": "Register a member",
  "member-view.actions.member-edit": "Change",
  "member-view.actions.suspendMember.confirm": "Suspend this member?",
  "member-view.actions.suspendMember.label": "Suspend",
  "member-view.actions.suspendMember.message": "The member is suspended.",
  "member-view.actions.suspendMember.reason": "Why",
  "member-view.failed.member-gone": "That member is gone.",
  "member-view.fields.joinedOn": "Joined on",
  "member-view.fields.name": "Name",
  "member-view.title": "Member",
  "members-list.actions.invitation": "Invite",
  "members-list.actions.suspendMember.confirm": "Suspend this member?",
  "members-list.actions.suspendMember.label": "Suspend",
  "members-list.actions.suspendMember.message": "The member is suspended.",
  "members-list.actions.suspendMember.reason": "Why",
  "members-list.columns.joinedOn": "Joined on",
  "members-list.columns.name": "Name",
  "members-list.columns.status": "Status",
  "members-list.empty": "No member yet.",
  "members-list.failed.default": "The members cannot be shown now.",
  "members-list.failed.member-gone": "That member is gone.",
  "members-list.filteredEmpty": "No member matches.",
  "members-list.filters.joinedOn": "Joined on",
  "members-list.filters.status": "Status",
  "members-list.title": "Members",
  "menu.admin.items.members": "Members",
  "menu.admin.title": "Administration",
  "menu.people.items.all": "All members",
  "menu.people.items.invite": "Invite someone",
  "menu.people.items.removals": "Removals to approve",
  "menu.people.title": "People",
  "removal-form.fields.why": "Why",
  "removal-form.onSubmitted": "Sent for approval. A supervisor answers within two days.",
  "removal-form.title": "Ask to remove a member",
  "removals-inbox.actions.approveRemoval.confirm": "Approve this removal?",
  "removals-inbox.actions.approveRemoval.label": "Approve",
  "removals-inbox.actions.approveRemoval.message": "The member is removed.",
  "removals-inbox.columns.memberId": "Member",
  "removals-inbox.columns.why": "Why",
  "removals-inbox.empty": "There is nothing here yet.",
  "removals-inbox.filteredEmpty": "Nothing matches these filters.",
  "removals-inbox.title": "Removals to approve",
  "screens.actions": "Actions",
  "screens.addItem": "Add an item",
  "screens.addRow": "Add a row",
  "screens.again": "The two entries differ.",
  "screens.any": "Any",
  "screens.back": "Back",
  "screens.cancel": "Cancel",
  "screens.columns": "Columns",
  "screens.date": "Type a day as yyyy-mm-dd.",
  "screens.email": "Type an email address, such as name@example.org.",
  "screens.failed": "This cannot be done right now. Try again in a moment.",
  "screens.filter": "Filter",
  "screens.itemsAtLeast": "Add at least {count} items.",
  "screens.itemsAtMost": "Keep to {count} items at most.",
  "screens.language": "Language",
  "screens.loading": "Loading",
  "screens.maxLength": "Use at most {count} characters.",
  "screens.maximum": "Use {count} or less.",
  "screens.menu": "Menu",
  "screens.minLength": "Use at least {count} characters.",
  "screens.minimum": "Use {count} or more.",
  "screens.next": "Next",
  "screens.no": "No",
  "screens.none": "None",
  "screens.nothingMatches": "Nothing matches.",
  "screens.number": "Type a number.",
  "screens.pattern": "This is not in the form asked for.",
  "screens.reason": "Give a reason.",
  "screens.refresh": "Refresh",
  "screens.refused": "You do not hold the permission this page needs.",
  "screens.removeItem": "Remove this item",
  "screens.removeRow": "Remove this row",
  "screens.required": "Fill this in.",
  "screens.rowsAtLeast": "Add at least {count} rows.",
  "screens.rowsAtMost": "Keep to {count} rows at most.",
  "screens.rule.pattern": "It matches {pattern}.",
  "screens.search": "Search",
  "screens.step": "Use a multiple of {count}.",
  "screens.yes": "Yes",
  "sign-in.failed.default": "Signing in does not work right now. Try again later.",
  "sign-in.failed.sign-in-refused": "The email address or the password is wrong.",
  "sign-in.fields.email": "Email address",
  "sign-in.fields.password": "Password",
  "sign-in.onSubmitted.200": "You are signed in.",
  "sign-in.title": "Sign in",
  "visits-form.failed.member-gone": "That member is gone.",
  "visits-form.fields.name": "Name",
  "visits-form.onSubmitted": "The visits are recorded.",
  "visits-form.rows.visitLog": "Visits",
  "visits-form.rows.visitLog.fields.id": "Visit",
  "visits-form.rows.visitLog.fields.note": "Note",
  "visits-form.rows.visitLog.fields.visitedOn": "Visited on",
  "visits-form.title": "Record visits",
} as const;

export type StringKey = keyof typeof strings;

/** The texts in each other language, an entry for every key. */
const translations: { readonly [L in Exclude<Language, "en">]: Readonly<Record<StringKey, string>> } = {};

/** The texts of a language. */
function textsOf(language: Language): Readonly<Record<StringKey, string>> {
  return language === "en" ? strings : translations[language];
}

/** The text of a key in a language. */
export function stringOf(key: StringKey, language: Language): string {
  return textsOf(language)[key];
}

function collect(value: unknown, from: Readonly<Record<StringKey, string>>, into: Record<string, string>): void {
  if (typeof value === "string") {
    if (Object.hasOwn(strings, value)) {
      into[value] = from[value as StringKey];
    }
  } else if (Array.isArray(value)) {
    value.forEach((item) => collect(item, from, into));
  } else if (typeof value === "object" && value !== null) {
    Object.values(value).forEach((item) => collect(item, from, into));
  }
}

/** The texts a page's schema names, with the screens' own, in a language. */
export function texts(schema: unknown, language: Language): Readonly<Record<string, string>> {
  const from = textsOf(language);
  const into: Record<string, string> = {};
  for (const key of Object.keys(strings) as StringKey[]) {
    if (key.startsWith("screens.")) {
      into[key] = from[key];
    }
  }
  collect(schema, from, into);
  return into;
}
