// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { ViewPageSchema } from "@/screens";

export const schema = {
  title: "member-view.title",
  permission: "members.read",
  source: {
    operation: "getMember",
    path: "/members/{memberId}",
    failed: [{ status: 404, problem: "member-not-found", message: "member-view.failed.member-not-found" }],
  },
  sections: [
    {
      title: "member-view.sections.0",
      fields: [
        { name: "cardNumber", label: "member-view.fields.cardNumber" },
        { name: "fullName", label: "member-view.fields.fullName" },
        { name: "email", label: "member-view.fields.email" },
        { name: "tier", label: "member-view.fields.tier" },
      ],
    },
    {
      title: "member-view.sections.1",
      fields: [
        { name: "joinedOn", label: "member-view.fields.joinedOn" },
        { name: "membershipEndsOn", label: "member-view.fields.membershipEndsOn" },
        { name: "outstandingFees", label: "member-view.fields.outstandingFees" },
      ],
    },
  ],
  actions: [{ label: "member-view.actions.loan-form", navigate: "loan-form", permission: "loans.create" }],
} satisfies ViewPageSchema;
