// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
"use client";

import { Modal, TextArea } from "@carbon/react";
import type { Fields } from "./rules";
import type { FailureSchema, RowActionSchema } from "./schema";
import { segment, service } from "./service";
import { say, type Texts } from "./texts";

function refusal(failed: readonly FailureSchema[], status: number): FailureSchema | undefined {
  return failed.find((f) => f.status === status) ?? failed.find((f) => f.status === undefined);
}

/**
 * Runs an action on a record: its path's parameters each from a field of
 * the record, and the reason, when it asks for one, as the property of the
 * body it names. It answers undefined on a success, or the message of the
 * refusal.
 */
export async function runAction(action: RowActionSchema, record: Fields, reason: string, texts: Texts): Promise<string | undefined> {
  const path = action.path.replace(/\{([^}]+)\}/g, (_, name: string) => segment(String(record[action.parameters[name] ?? name] ?? "")));
  try {
    const response = await fetch(service + path, {
      method: action.method,
      credentials: "include",
      headers: { Accept: "application/json", ...(action.reason ? { "Content-Type": "application/json" } : {}) },
      body: action.reason ? JSON.stringify({ [action.reason.property]: reason.trim() }) : undefined,
    });
    if (response.ok) {
      return undefined;
    }
    return say(texts, refusal(action.failed, response.status)?.message ?? "screens.failed");
  } catch {
    return say(texts, "screens.failed");
  }
}

export interface ConfirmProps {
  readonly action: RowActionSchema & { readonly confirm: NonNullable<RowActionSchema["confirm"]> };
  readonly texts: Texts;
  readonly reason: string;
  readonly running: boolean;
  readonly onReason: (reason: string) => void;
  readonly onConfirm: () => void;
  readonly onClose: () => void;
}

/**
 * The question an action asks before it runs, in a Modal, with the reason
 * it requires typed in a TextArea; it is not confirmed while the reason is
 * empty.
 */
export function Confirm({ action, texts, reason, running, onReason, onConfirm, onClose }: ConfirmProps) {
  const missing = action.reason !== undefined && reason.trim() === "";
  return (
    <Modal
      open
      danger
      modalHeading={say(texts, action.confirm)}
      primaryButtonText={say(texts, action.label)}
      secondaryButtonText={say(texts, "screens.cancel")}
      primaryButtonDisabled={running || missing}
      onRequestSubmit={onConfirm}
      onRequestClose={onClose}
    >
      {action.reason !== undefined && (
        <TextArea
          id="screens-reason"
          labelText={say(texts, action.reason.label)}
          helperText={say(texts, "screens.reason")}
          value={reason}
          aria-required
          maxCount={action.reason.maxLength}
          enableCounter={action.reason.maxLength !== undefined}
          onChange={(event) => onReason(event.target.value)}
        />
      )}
    </Modal>
  );
}
