// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
"use client";

import { Checkbox, DatePicker, DatePickerInput, NumberInput, PasswordInput, Select, SelectItem, TextArea, TextInput } from "@carbon/react";
import type { ChangeEvent } from "react";
import { Lookup } from "./Lookup";
import type { Fields } from "./rules";
import type { FieldSchema } from "./schema";
import { say, type Texts } from "./texts";

export interface FieldProps {
  readonly field: FieldSchema;
  readonly value: string;
  readonly problem?: string;
  readonly texts: Texts;
  readonly onChange: (value: string) => void;
  /** Shown and not changed, while the field's own rule holds. */
  readonly readOnly?: boolean;
  /** The id and label of a second entry of the field, in place of its own. */
  readonly again?: { readonly id: string; readonly label: string };
  /** The record a lookup picked, for the fields it fills. */
  readonly onPick?: (record: Fields) => void;
}

/** One field of a page, drawn by the Carbon control its type takes. */
export function Field({ field, value, problem, texts, onChange, readOnly = false, again, onPick }: FieldProps) {
  const id = again?.id ?? field.name;
  const labelText = again?.label ?? say(texts, field.label);
  const invalid = problem !== undefined;
  const props = {
    id,
    name: id,
    labelText,
    value,
    invalid,
    invalidText: problem,
    readOnly,
    "aria-required": field.required,
    onChange: (event: ChangeEvent<HTMLInputElement>) => onChange(event.target.value),
  };
  switch (field.type) {
    case "password":
      return <PasswordInput {...props} helperText={field.rules.map((rule) => say(texts, rule)).join(" ")} />;
    case "email":
      return <TextInput {...props} type="email" />;
    case "text":
      return <TextInput {...props} />;
    case "textArea":
      return (
        <TextArea
          id={id}
          name={id}
          labelText={labelText}
          value={value}
          invalid={invalid}
          invalidText={problem}
          readOnly={readOnly}
          aria-required={field.required}
          onChange={(event: ChangeEvent<HTMLTextAreaElement>) => onChange(event.target.value)}
        />
      );
    case "number":
      return (
        <NumberInput
          id={id}
          label={labelText}
          value={value}
          allowEmpty
          hideSteppers={readOnly}
          min={field.min}
          max={field.max}
          step={field.step}
          invalid={invalid}
          invalidText={problem}
          readOnly={readOnly}
          aria-required={field.required}
          onChange={(_, state) => onChange(state.value === "" ? "" : String(state.value))}
        />
      );
    case "date":
      return (
        <DatePicker
          datePickerType="single"
          dateFormat="Y-m-d"
          value={value}
          readOnly={readOnly}
          invalid={invalid}
          onChange={(_, text) => onChange(text)}
        >
          <DatePickerInput
            id={id}
            labelText={labelText}
            placeholder="yyyy-mm-dd"
            invalid={invalid}
            invalidText={problem}
            readOnly={readOnly}
            aria-required={field.required}
            onChange={(event: ChangeEvent<HTMLInputElement>) => onChange(event.target.value)}
          />
        </DatePicker>
      );
    case "select":
      return (
        <Select
          id={id}
          labelText={labelText}
          value={value}
          invalid={invalid}
          invalidText={problem}
          readOnly={readOnly}
          aria-required={field.required}
          onChange={(event: ChangeEvent<HTMLSelectElement>) => onChange(event.target.value)}
        >
          <SelectItem value="" text="" />
          {field.options.map((option) => (
            <SelectItem key={option} value={option} text={option} />
          ))}
        </Select>
      );
    case "checkbox":
      return (
        <Checkbox
          id={id}
          labelText={labelText}
          checked={value === "true"}
          readOnly={readOnly}
          invalid={invalid}
          invalidText={problem}
          onChange={(_, { checked }) => onChange(String(checked))}
        />
      );
    case "lookup":
      return (
        <Lookup
          field={field}
          label={labelText}
          value={value}
          problem={problem}
          texts={texts}
          readOnly={readOnly}
          onPick={(record) => {
            onChange(record === undefined ? "" : String(record[field.value] ?? ""));
            if (record !== undefined) {
              onPick?.(record);
            }
          }}
        />
      );
  }
}
