// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { Metadata } from "next";
import { Guard, ViewPage } from "@/screens";
import { chosenLanguage } from "@/language";
import { stringOf, texts } from "@/strings";
import { schema } from "./page.schema";

export async function generateMetadata(): Promise<Metadata> {
  return { title: stringOf("member-view.title", await chosenLanguage()) };
}

const routes = {
  "loan-form": "/loans/new",
  "member-loans": "/members/{memberId}/loans",
};

export default async function Page({ params }: { readonly params: Promise<Record<string, string>> }) {
  const parameters = await params;
  const t = texts(schema, await chosenLanguage());
  return (
    <Guard permission={schema.permission} texts={t}>
      <ViewPage schema={schema} texts={t} routes={routes} parameters={parameters} />
    </Guard>
  );
}
