// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_golden_missing: page sign-in has no golden scenario; add one under tests, for example page-sign-in-succeeds: { page: sign-in, scenario: golden, given: "any caller", when: "the page sign-in is submitted with every field valid", then: "it is answered 200 and leads to the page member-view, saying: You are signed in." } [test_golden_missing@specarch.yaml#/pages/sign-in]
import type { TaskPageSchema } from "@/screens";

export const schema = {
  title: "sign-in.title",
  submit: { operation: "signIn", method: "POST", path: "/sessions" },
  fields: [
    { type: "email", name: "email", label: "sign-in.fields.email", required: true, maxLength: 254 },
    {
      type: "password",
      name: "password",
      label: "sign-in.fields.password",
      required: true,
      minLength: 12,
      maxLength: 128,
      pattern: "[0-9]",
      rules: [
        { text: "screens.minLength", count: 12 },
        { text: "screens.maxLength", count: 128 },
        { text: "screens.rule.pattern", pattern: "[0-9]" },
      ],
    },
  ],
  checks: [],
  failed: [
    { problem: "default", message: "sign-in.failed.default" },
    { status: 401, problem: "sign-in-refused", message: "sign-in.failed.sign-in-refused" },
  ],
  events: [{ status: 200, navigate: "member-view", with: { memberId: "memberId" }, message: "sign-in.onSubmitted.200" }],
} satisfies TaskPageSchema;
