// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page visits-form has no red scenario for "denied with expired session"; add under tests visits-form-denied-with-expired-session: { page: visits-form, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page visits-form is opened", then: "it is refused as not signed in" } [test_case_missing.1dd6c421@specarch.yaml#/pages/visits-form]
// specarch-problem: warning: test_case_missing: page visits-form has no red scenario for "not found memberId"; add under tests visits-form-not-found-member-id: { page: visits-form, scenario: red, covers: [not found memberId], given: "no record has that memberId", when: "the page visits-form is opened for that memberId", then: "it says the record was not found" } [test_case_missing.7dd5f0fd@specarch.yaml#/pages/visits-form]
// specarch-problem: warning: test_case_missing: page visits-form has no red scenario for "denied without members.write"; add under tests visits-form-denied-without-members-write: { page: visits-form, scenario: red, covers: [denied without members.write], given: "a caller without members.write", when: "the page visits-form is opened", then: "it is refused as not allowed" } [test_case_missing.f143c3a6@specarch.yaml#/pages/visits-form]
// specarch-problem: warning: test_golden_missing: page visits-form has no golden scenario; add one under tests, for example visits-form-succeeds: { page: visits-form, scenario: golden, given: "a caller with members.write", when: "the page visits-form is opened for a record that exists", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/visits-form]
import type { FormPageSchema } from "@/screens";

export const schema = {
  title: "visits-form.title",
  permission: "members.write",
  source: {
    operation: "getMember",
    path: "/members/{memberId}",
    failed: [{ status: 404, problem: "member-gone", message: "visits-form.failed.member-gone" }],
  },
  submit: { operation: "recordVisits", method: "POST", path: "/members/{memberId}/visits", fields: [] },
  layout: "page",
  sections: [
    {
      fields: [
        { type: "text", name: "name", label: "visits-form.fields.name", required: false, minLength: 1, maxLength: 100, readOnly: true },
      ],
    },
  ],
  rows: [
    {
      name: "visitLog",
      loaded: "visitLog",
      title: "visits-form.rows.visitLog",
      fields: [
        { type: "date", name: "visitedOn", label: "visits-form.rows.visitLog.fields.visitedOn", required: true },
        { type: "text", name: "note", label: "visits-form.rows.visitLog.fields.note", required: false, maxLength: 100 },
        { type: "text", name: "id", label: "visits-form.rows.visitLog.fields.id", required: false, readOnly: true },
      ],
      sent: ["visitedOn", "note"],
      maximum: 5,
      minimum: 1,
      lockLoaded: true,
    },
  ],
  checks: [],
  failed: [{ status: 404, problem: "member-gone", message: "visits-form.failed.member-gone" }],
  events: [{ navigate: "member-view", with: { memberId: "id" }, message: "visits-form.onSubmitted" }],
} satisfies FormPageSchema;
