-- Generated by specarch-gen-sql from ../spec/specarch.yaml, version 0.1.0; meta-model 0.1; postgresql through type-rendering 1.2.0. Do not edit this file: a change to the schema is a new migration.

CREATE TABLE fee_waiver_request (
    id UUID NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    loan_id UUID NOT NULL,
    reason VARCHAR(500) NOT NULL,
    CONSTRAINT pk_fee_waiver_request PRIMARY KEY (id)
);

ALTER TABLE fee_waiver_request ADD CONSTRAINT fk_fee_waiver_request_loan_id FOREIGN KEY (loan_id) REFERENCES loans (id) ON DELETE RESTRICT;
