-- Generated by specarch-gen-sql from ../spec/specarch.yaml, version 0.1.0; meta-model 0.1; postgresql through type-rendering 1.2.0. Do not edit this file: a change to the schema is a new migration.

ALTER TABLE members ADD COLUMN address_city VARCHAR(100);

ALTER TABLE members ADD COLUMN address_postcode VARCHAR(12);

ALTER TABLE members ADD COLUMN address_street VARCHAR(200);

ALTER TABLE members ADD COLUMN phones JSONB;

ALTER TABLE members ADD CONSTRAINT ck_members_address CHECK (((((address_city IS NULL) AND (address_postcode IS NULL)) AND (address_street IS NULL)) OR ((address_city IS NOT NULL) AND (address_street IS NOT NULL))));
