// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page members-list has no red scenario for "denied without members.read"; add under tests members-list-denied-without-members-read: { page: members-list, scenario: red, covers: [denied without members.read], given: "a caller without members.read", when: "the page members-list is opened", then: "it is refused as not allowed" } [test_case_missing.228a8842@specarch.yaml#/pages/members-list]
// specarch-problem: warning: test_case_missing: page members-list has no red scenario for "denied with expired session"; add under tests members-list-denied-with-expired-session: { page: members-list, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page members-list is opened", then: "it is refused as not signed in" } [test_case_missing.7e8e6ef1@specarch.yaml#/pages/members-list]
// specarch-problem: warning: test_case_missing: page members-list has no red scenario for "Suspend without a reason"; add under tests members-list-suspend-without-a-reason: { page: members-list, scenario: red, covers: [Suspend without a reason], given: "...", when: "the action Suspend is confirmed with no why", then: "it is not sent, and the why is asked for" } [test_case_missing.9744cf4d@specarch.yaml#/pages/members-list]
// specarch-problem: warning: test_golden_missing: page members-list has no golden scenario; add one under tests, for example members-list-succeeds: { page: members-list, scenario: golden, given: "a caller with members.read", when: "the page members-list is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/members-list]
import type { Metadata } from "next";
import { Guard, ListPage } from "@/screens";
import { chosenLanguage } from "@/language";
import { stringOf, texts } from "@/strings";
import { schema } from "./page.schema";

export async function generateMetadata(): Promise<Metadata> {
  return { title: stringOf("members-list.title", await chosenLanguage()) };
}

const routes = {
  invitation: "/invitations",
  "member-view": "/members/{memberId}",
};

export default async function Page() {
  const t = texts(schema, await chosenLanguage());
  return (
    <Guard permission={schema.permission} texts={t}>
      <ListPage schema={schema} texts={t} routes={routes} />
    </Guard>
  );
}
