// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page members-list has no red scenario for "denied without members.read"; add under tests members-list-denied-without-members-read: { page: members-list, scenario: red, covers: [denied without members.read], given: "a caller without members.read", when: "the page members-list is opened", then: "it is refused as not allowed" } [test_case_missing.228a8842@specarch.yaml#/pages/members-list]
// specarch-problem: warning: test_case_missing: page members-list has no red scenario for "denied with expired session"; add under tests members-list-denied-with-expired-session: { page: members-list, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page members-list is opened", then: "it is refused as not signed in" } [test_case_missing.7e8e6ef1@specarch.yaml#/pages/members-list]
// specarch-problem: warning: test_case_missing: page members-list has no red scenario for "Suspend without a reason"; add under tests members-list-suspend-without-a-reason: { page: members-list, scenario: red, covers: [Suspend without a reason], given: "...", when: "the action Suspend is confirmed with no why", then: "it is not sent, and the why is asked for" } [test_case_missing.9744cf4d@specarch.yaml#/pages/members-list]
// specarch-problem: warning: test_golden_missing: page members-list has no golden scenario; add one under tests, for example members-list-succeeds: { page: members-list, scenario: golden, given: "a caller with members.read", when: "the page members-list is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/members-list]
import type { ListPageSchema } from "@/screens";

export const schema = {
  title: "members-list.title",
  permission: "members.read",
  source: { operation: "listMembers", path: "/members" },
  columns: [
    { field: "name", title: "members-list.columns.name", sortable: true, compact: true },
    { field: "status", title: "members-list.columns.status", sortable: false, compact: false },
    { field: "joinedOn", title: "members-list.columns.joinedOn", sortable: true, compact: false },
  ],
  filters: [
    { field: "status", query: "status", title: "members-list.filters.status", options: ["active", "inactive"] },
    { field: "joinedOn", query: "filter[joinedOn]", title: "members-list.filters.joinedOn", date: true },
  ],
  search: true,
  pageSize: 25,
  pageSizes: [10, 20, 25, 50],
  actions: [{ label: "members-list.actions.invitation", navigate: "invitation", permission: "members.read" }],
  rowActions: [
    {
      label: "members-list.actions.suspendMember.label",
      operation: "suspendMember",
      method: "POST",
      path: "/members/{memberId}/suspend",
      parameters: { memberId: "id" },
      permission: "members.write",
      when: ["==", ["field", "status"], ["value", "active"]],
      confirm: "members-list.actions.suspendMember.confirm",
      reason: { property: "why", label: "members-list.actions.suspendMember.reason", maxLength: 200 },
      message: "members-list.actions.suspendMember.message",
      failed: [
        { status: 404, problem: "member-gone", message: "members-list.failed.member-gone" },
        { problem: "default", message: "members-list.failed.default" },
      ],
    },
  ],
  select: { navigate: "member-view", with: { memberId: "id" } },
  empty: "members-list.empty",
  filteredEmpty: "members-list.filteredEmpty",
  failed: [{ problem: "default", message: "members-list.failed.default" }],
  wire: {
    page: "page",
    pageSize: "pageSize",
    sort: "sort",
    search: "search",
    items: "items",
    totalItems: "totalItems",
    totalPages: "totalPages",
  },
} satisfies ListPageSchema;
