// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/0.1.0.yaml beside the specification; this file is not the approved output.
import { cookies } from "next/headers";
import { languageCookie, languages, type Language } from "./strings";

/** The language the person chose, kept in its cookie across sessions, or the specification's. */
export async function chosenLanguage(): Promise<Language> {
  const chosen = (await cookies()).get(languageCookie)?.value;
  return languages.find((language) => language === chosen) ?? languages[0];
}
