// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
/**
 * Every text the screens show, by string key, in the specification's
 * language, en.
 */
export const strings = {
  "loans-list.actions.reportLost.confirm": "Charge the replacement cost and close this loan?",
  "loans-list.actions.reportLost.label": "Lost",
  "loans-list.actions.reportLost.message": "The loan is closed and the replacement cost charged.",
  "loans-list.actions.returnLoan.confirm": "Record this copy as returned?",
  "loans-list.actions.returnLoan.label": "Return",
  "loans-list.actions.returnLoan.message": "The copy is recorded as returned.",
  "loans-list.columns.bookId": "Book",
  "loans-list.columns.dueOn": "Due on",
  "loans-list.columns.lateFee": "Late fee",
  "loans-list.columns.loanedAt": "Lent at",
  "loans-list.columns.memberId": "Member",
  "loans-list.columns.status": "Status",
  "loans-list.empty": "No loans yet. A loan is made from a member's record.",
  "loans-list.failed.default": "The loans cannot be shown or changed right now. Try again in a moment.",
  "loans-list.failed.loan-closed": "This loan was already closed, so nothing changed.",
  "loans-list.filteredEmpty": "No loan matches these filters.",
  "loans-list.filters.memberId": "Member",
  "loans-list.filters.status": "Status",
  "loans-list.title": "Loans",
  "members-list.actions.deactivateMember.confirm": "Deactivate this member? They will borrow nothing more.",
  "members-list.actions.deactivateMember.label": "Deactivate",
  "members-list.actions.deactivateMember.message": "The member is deactivated.",
  "members-list.actions.deactivateMember.reason": "Reason",
  "members-list.actions.member-form": "New member",
  "members-list.columns.cardNumber": "Card number",
  "members-list.columns.email": "Email address",
  "members-list.columns.fullName": "Full name",
  "members-list.columns.outstandingFees": "Outstanding fees",
  "members-list.columns.status": "Status",
  "members-list.columns.tier": "Tier",
  "members-list.empty": "No members yet. Register the first one.",
  "members-list.failed.member-not-found": "This member is no longer on record, so nothing changed.",
  "members-list.filteredEmpty": "No member is in this tier.",
  "members-list.filters.tier": "Tier",
  "members-list.title": "Members",
  "menu.loans.items.list": "All loans",
  "menu.loans.title": "Loans",
  "menu.members.items.list": "All members",
  "menu.members.title": "Members",
  "reset-password.checks.confirmation-matches": "The two passwords are not the same.",
  "reset-password.failed.reset-code-refused": "The reset code is wrong, used or expired. Ask for a new one.",
  "reset-password.fields.code": "Reset code",
  "reset-password.fields.confirmPassword": "New password again",
  "reset-password.fields.newPassword": "New password",
  "reset-password.onSubmitted.204": "Your password is set. Sign in with it.",
  "reset-password.title": "Set a new password",
  "screens.actions": "Actions",
  "screens.any": "Any",
  "screens.cancel": "Cancel",
  "screens.columns": "Columns",
  "screens.email": "Type an email address, such as name@example.org.",
  "screens.failed": "This cannot be done right now. Try again in a moment.",
  "screens.filter": "Filter",
  "screens.loading": "Loading",
  "screens.maxLength": "Use at most {count} characters.",
  "screens.menu": "Menu",
  "screens.minLength": "Use at least {count} characters.",
  "screens.pattern": "This is not in the form asked for.",
  "screens.refresh": "Refresh",
  "screens.refused": "You do not hold the permission this page needs.",
  "screens.required": "Fill this in.",
  "screens.rule.pattern": "It matches {pattern}.",
  "screens.search": "Search",
  "second-factor.failed.second-factor-refused": "The code is wrong, or it came too late. Type the code the app shows now, or sign in again.",
  "second-factor.fields.code": "Code from the authenticator app",
  "second-factor.onSubmitted.200": "You are signed in.",
  "second-factor.title": "Confirm it is you",
  "sign-in.failed.sign-in-refused": "The email address or the password is wrong.",
  "sign-in.fields.email": "Email address",
  "sign-in.fields.password": "Password",
  "sign-in.onSubmitted.200": "You are signed in.",
  "sign-in.title": "Sign in",
} as const;

export type StringKey = keyof typeof strings;

function collect(value: unknown, into: Record<string, string>): void {
  if (typeof value === "string") {
    if (Object.hasOwn(strings, value)) {
      into[value] = strings[value as StringKey];
    }
  } else if (Array.isArray(value)) {
    value.forEach((item) => collect(item, into));
  } else if (typeof value === "object" && value !== null) {
    Object.values(value).forEach((item) => collect(item, into));
  }
}

/** The texts a page's schema names, with the screens' own. */
export function texts(schema: unknown): Readonly<Record<string, string>> {
  const into: Record<string, string> = {};
  for (const [key, text] of Object.entries(strings)) {
    if (key.startsWith("screens.")) {
      into[key] = text;
    }
  }
  collect(schema, into);
  return into;
}
