-- Generated by specarch-gen-sql from ../project/specarch.yaml, version 1.0.0; meta-model 0.1; postgresql through type-rendering 1.2.0. Do not edit this file: a change to the schema is a new migration.

ALTER TABLE books ADD COLUMN subtitle VARCHAR(200);
