// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { FormPageSchema } from "@/screens";

export const schema = {
  title: "member-form.title",
  permission: "members.write",
  submit: {
    operation: "createMember",
    method: "POST",
    path: "/members",
    fields: ["name", "status", "joinedOn", "homeBranchId", "visits", "newsletter", "notes", "pin"],
    idempotencyKey: "Idempotency-Key",
  },
  layout: "steps",
  sections: [
    {
      title: "member-form.sections.0",
      fields: [
        { type: "text", name: "name", label: "member-form.fields.name", required: true, minLength: 1, maxLength: 100 },
        { type: "select", name: "status", label: "member-form.fields.status", required: true, options: ["active", "inactive"] },
        { type: "date", name: "joinedOn", label: "member-form.fields.joinedOn", required: true, hook: true },
      ],
    },
    {
      title: "member-form.sections.1",
      fields: [
        {
          type: "lookup",
          name: "homeBranchId",
          label: "member-form.fields.homeBranchId",
          required: false,
          source: {
            operation: "listBranches",
            path: "/branches",
            items: "items",
            pageSize: { name: "pageSize", value: 50 },
            search: "search",
          },
          value: "id",
          text: ["name"],
          fills: {},
        },
        {
          type: "number",
          name: "visits",
          label: "member-form.fields.visits",
          required: false,
          min: 0,
          max: 1000,
          step: 1,
          readOnlyWhen: ["==", ["field", "status"], ["value", "inactive"]],
        },
        { type: "checkbox", name: "newsletter", label: "member-form.fields.newsletter", required: false },
        { type: "textArea", name: "notes", label: "member-form.fields.notes", required: false, hiddenWhen: ["!", ["field", "newsletter"]] },
        {
          type: "text",
          name: "pin",
          label: "member-form.fields.pin",
          required: false,
          maxLength: 4,
          pattern: "^[0-9]{4}$",
          twice: "member-form.fields.pin.again",
        },
      ],
    },
  ],
  rows: [],
  checks: [
    {
      name: "notes-not-the-name",
      rule: ["!=", ["field", "notes"], ["field", "name"]],
      message: "member-form.checks.notes-not-the-name",
      field: "notes",
    },
  ],
  failed: [],
  events: [{ navigate: "member-view", with: { memberId: "id" }, message: "member-form.onSubmitted" }],
} satisfies FormPageSchema;
