// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { StringKey } from "@/strings";

/** A text to show: a string key, and the values its placeholders take. */
export interface Message {
  readonly text: StringKey;
  readonly count?: number;
  readonly pattern?: string;
}

/**
 * A rule over the values of a page, from an expression of the
 * specification: a field's value, a constant, or an operator and its
 * operands.
 */
export type Rule =
  | readonly ["field", string]
  | readonly ["value", string | number | boolean | null]
  | readonly ["!", Rule]
  | readonly ["size", Rule]
  | readonly ["==" | "!=" | "<" | "<=" | ">" | ">=" | "&&" | "||", Rule, Rule];

interface FieldBase {
  readonly name: string;
  readonly label: StringKey;
  readonly required: boolean;
  /** Shown and never changed by the person: the field's own, or the page's. */
  readonly readOnly?: boolean;
  /** Read-only while this rule holds for the values. */
  readonly readOnlyWhen?: Rule;
  /** Not shown, checked or sent while this rule holds for the values. */
  readonly hiddenWhen?: Rule;
  /** The value it starts with comes from the page's hook of its name. */
  readonly hook?: boolean;
  /** Typed a second time, the second entry compared and never sent. */
  readonly twice?: StringKey;
}

/** A field of type string with no format the other field types take. */
export interface TextFieldSchema extends FieldBase {
  readonly type: "text";
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly pattern?: string;
}

/** A field of format email. */
export interface EmailFieldSchema extends FieldBase {
  readonly type: "email";
  readonly maxLength?: number;
}

/** A field of format password, its rules shown under it. */
export interface PasswordFieldSchema extends FieldBase {
  readonly type: "password";
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly pattern?: string;
  readonly rules: readonly Message[];
}

/** A field of type string wider than one line holds. */
export interface TextAreaFieldSchema extends FieldBase {
  readonly type: "textArea";
  readonly maxLength?: number;
}

/** A field of type integer or number. */
export interface NumberFieldSchema extends FieldBase {
  readonly type: "number";
  readonly min?: number;
  readonly max?: number;
  readonly step?: number;
}

/** A field of format date, its value written yyyy-mm-dd. */
export interface DateFieldSchema extends FieldBase {
  readonly type: "date";
}

/** A field whose values are an enum. */
export interface SelectFieldSchema extends FieldBase {
  readonly type: "select";
  readonly options: readonly string[];
}

/** A field of type boolean. */
export interface CheckboxFieldSchema extends FieldBase {
  readonly type: "checkbox";
}

/**
 * Where a lookup reads the records to pick from: a list operation read a
 * page at a time through the paginated-list idiom's names, searched by the
 * service when it names search, and otherwise one page searched here.
 */
export interface LookupSourceSchema {
  readonly operation: string;
  readonly path: string;
  readonly items: string;
  readonly pageSize: { readonly name: string; readonly value: number };
  readonly search?: string;
}

/**
 * A field that holds the key of another record, picked from a list: the
 * record's field the key is, the fields shown to choose by, and the fields
 * of the page the chosen record fills, each from one of its own.
 */
export interface LookupFieldSchema extends FieldBase {
  readonly type: "lookup";
  readonly source: LookupSourceSchema;
  readonly value: string;
  readonly text: readonly string[];
  readonly fills: Readonly<Record<string, string>>;
}

export type FieldSchema =
  | TextFieldSchema
  | TextAreaFieldSchema
  | EmailFieldSchema
  | PasswordFieldSchema
  | NumberFieldSchema
  | DateFieldSchema
  | SelectFieldSchema
  | CheckboxFieldSchema
  | LookupFieldSchema;

/**
 * A field holding a value of a schema, its parts drawn in a section of
 * their own under its label, each by its own field part. An optional value
 * is left out while none of its parts is given, and has its required parts
 * required once one is.
 */
export interface ValueFieldSchema {
  readonly type: "value";
  readonly name: string;
  readonly label: StringKey;
  readonly required: boolean;
  readonly parts: readonly FormFieldSchema[];
  readonly readOnly?: boolean;
  readonly readOnlyWhen?: Rule;
  readonly hiddenWhen?: Rule;
}

/**
 * A field holding a list of values of a schema, drawn as a repeating group:
 * an item per value with the schema's parts, added and removed, at least
 * minimum and at most maximum of them, sent as an array of the items.
 */
export interface ValueListFieldSchema {
  readonly type: "valueList";
  readonly name: string;
  readonly label: StringKey;
  readonly required: boolean;
  readonly parts: readonly FormFieldSchema[];
  readonly minimum?: number;
  readonly maximum?: number;
  readonly readOnly?: boolean;
  readonly readOnlyWhen?: Rule;
  readonly hiddenWhen?: Rule;
}

/** A field of a form's sections: one value, or a value of a schema or a list of them. */
export type FormFieldSchema = FieldSchema | ValueFieldSchema | ValueListFieldSchema;

/** A rule across the fields, checked before the page is sent. */
export interface CheckSchema {
  readonly name: string;
  readonly rule: Rule;
  readonly message: StringKey;
  readonly field?: string;
}

/**
 * A problem the operation answers, and where the page shows it; with no
 * status, every problem the page names no message for.
 */
export interface FailureSchema {
  readonly status?: number;
  readonly problem: string;
  readonly message: StringKey;
  readonly field?: string;
}

/**
 * What a success the operation answers leads to: a page by its name, the
 * route parameters taken from the answer's body, or on a form that loads
 * its record from that record, and a message. On a form that starts an
 * approval, the event of status 202 is the pending state. A page that
 * keeps returnTo hands on the page sign-in was asked for from; any other
 * page gives way to it.
 */
export interface EventSchema {
  /** With none, every success the operation answers. */
  readonly status?: number;
  readonly navigate?: string;
  readonly with?: Readonly<Record<string, string>>;
  readonly message?: StringKey;
  readonly keepsReturnTo?: boolean;
}

/** The operation a page sends its fields to. */
export interface SubmitSchema {
  readonly operation: string;
  readonly method: "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
}

/** A form that submits to an operation without loading a record. */
export interface TaskPageSchema {
  readonly title: StringKey;
  readonly submit: SubmitSchema;
  readonly fields: readonly FieldSchema[];
  readonly checks: readonly CheckSchema[];
  readonly failed: readonly FailureSchema[];
  readonly events: readonly EventSchema[];
}

/** A column of a list: the row's field, its title, and whether it sorts and stays on a compact screen. */
export interface ColumnSchema {
  readonly field: string;
  readonly title: StringKey;
  readonly sortable: boolean;
  readonly compact: boolean;
}

/** A filter of a list: the field, its name in the query, its title, and its values when they are a list. */
export interface FilterSchema {
  readonly field: string;
  readonly query: string;
  readonly title: StringKey;
  readonly options?: readonly string[];
  readonly date?: boolean;
}

/** An action of a list's toolbar that opens a page. */
export interface PageActionSchema {
  readonly label: StringKey;
  readonly navigate: string;
  readonly permission: string;
}

/** The reason a confirmation asks for, sent as a property of the request's body. */
export interface ReasonSchema {
  readonly property: string;
  readonly label: StringKey;
  readonly maxLength?: number;
}

/**
 * An action on a row, or on the record a view shows: the operation, its
 * path with the route parameters each taken from a field of the record, who may run it and while what holds,
 * its confirmation, the reason it asks for, its message and its refusals.
 */
export interface RowActionSchema {
  readonly label: StringKey;
  readonly operation: string;
  readonly method: "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly parameters: Readonly<Record<string, string>>;
  readonly permission: string;
  readonly when?: Rule;
  readonly confirm?: StringKey;
  readonly reason?: ReasonSchema;
  readonly message?: StringKey;
  readonly failed: readonly FailureSchema[];
}

/** Where selecting a row leads: a page, its route parameters each from a field of the row. */
export interface SelectSchema {
  readonly navigate: string;
  readonly with: Readonly<Record<string, string>>;
}

/** The names of a list's request and answer on the wire, the paginated-list idiom's. */
export interface WireSchema {
  readonly page: string;
  readonly pageSize: string;
  readonly sort: string;
  readonly search: string;
  readonly items: string;
  readonly totalItems: string;
  readonly totalPages: string;
}

/** A list read a page at a time from an operation. */
export interface ListPageSchema {
  readonly title: StringKey;
  readonly permission: string;
  readonly source: { readonly operation: string; readonly path: string };
  readonly columns: readonly ColumnSchema[];
  readonly filters: readonly FilterSchema[];
  readonly search: boolean;
  readonly pageSize: number;
  readonly pageSizes: readonly number[];
  readonly actions: readonly PageActionSchema[];
  readonly rowActions: readonly RowActionSchema[];
  readonly select?: SelectSchema;
  readonly empty: StringKey;
  readonly filteredEmpty: StringKey;
  readonly failed: readonly FailureSchema[];
  readonly wire: WireSchema;
}

/** A group of a form's or a view's fields, in focus order, with its title when it has one. */
export interface SectionSchema<F> {
  readonly title?: StringKey;
  readonly fields: readonly F[];
}

/** How a form's sections sit: on one page, as tabs, or as steps taken in order. */
export type Layout = "page" | "tabs" | "steps";

/**
 * The operation a form loads its record from: the page's route parameters
 * fill its path, and its refusals are the page's failed states it answers.
 */
export interface LoadSchema {
  readonly operation: string;
  readonly path: string;
  readonly failed: readonly FailureSchema[];
}

/**
 * The operation a form sends its fields to, and the fields its request
 * body takes; the path's parameters come from the page's route, or from
 * the loaded record. idempotencyKey names the header the key is sent in,
 * kept while a request goes unanswered and chosen anew after an answer.
 */
export interface FormSubmitSchema extends SubmitSchema {
  readonly fields: readonly string[];
  readonly idempotencyKey?: string;
}

/**
 * The records of a relation edited as rows under a form: the array of the
 * request body they are sent in, the property of the loaded record that
 * holds the loaded ones, each row's fields, and the fields its items take.
 * A field not sent is shown read-only. The maximum counts loaded and added
 * rows together; the minimum is of the rows sent. Loaded rows are locked
 * and never sent.
 */
export interface ChildRowsSchema {
  readonly name: string;
  readonly loaded?: string;
  readonly title: StringKey;
  readonly fields: readonly FieldSchema[];
  readonly sent: readonly string[];
  readonly maximum?: number;
  readonly minimum?: number;
  readonly lockLoaded: boolean;
}

/**
 * A form that creates a record, or with source loads one and changes it:
 * its sections and child rows, checked by their keywords and the page's
 * checks before the request is sent, its refusals and where each success
 * leads.
 */
export interface FormPageSchema {
  readonly title: StringKey;
  readonly permission: string;
  readonly source?: LoadSchema;
  readonly submit: FormSubmitSchema;
  readonly layout: Layout;
  readonly sections: readonly SectionSchema<FormFieldSchema>[];
  readonly rows: readonly ChildRowsSchema[];
  readonly checks: readonly CheckSchema[];
  readonly failed: readonly FailureSchema[];
  readonly events: readonly EventSchema[];
}

/**
 * A field a view shows, hidden while its rule holds for the record; with
 * parts, it holds a value of a schema, shown part by part, or with list a
 * list of them, shown as a table of its items.
 */
export interface ViewFieldSchema {
  readonly name: string;
  readonly label: StringKey;
  readonly hiddenWhen?: Rule;
  readonly parts?: readonly ViewFieldSchema[];
  readonly list?: boolean;
}

/**
 * An action of a view that opens a page: its route parameters are taken
 * from the record's fields of their names, or from the view's own route.
 */
export interface ViewActionSchema {
  readonly label: StringKey;
  readonly navigate: string;
  readonly permission: string;
}

/**
 * One record read from an operation, its sections shown read-only, with
 * the actions that open a page and those that run an operation on it.
 */
export interface ViewPageSchema {
  readonly title: StringKey;
  readonly permission: string;
  readonly source: LoadSchema;
  readonly sections: readonly SectionSchema<ViewFieldSchema>[];
  readonly actions: readonly ViewActionSchema[];
  readonly operations: readonly RowActionSchema[];
}
