// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import { fieldProblem, typed, type Fields, type Values } from "./rules";
import type { FieldSchema, FormFieldSchema, ValueFieldSchema, ValueListFieldSchema } from "./schema";
import { say, type Texts } from "./texts";

/**
 * A form holds every value as text under the path to it: a field by its
 * name, a part of a value as address.street, and a part of a list's item
 * as phones.0.number, with the number of items under phones#items.
 */

/** A field holding a value of a schema or a list of them. */
export type HeldValue = ValueFieldSchema | ValueListFieldSchema;

/** Whether a field holds a value of a schema or a list of them. */
export function holdsValue(field: FormFieldSchema): field is HeldValue {
  return field.type === "value" || field.type === "valueList";
}

/** The key a list keeps its number of items under. */
export function itemsOf(path: string): string {
  return path + "#items";
}

/** The number of items a list at path holds. */
export function countOf(values: Values, path: string): number {
  return Number(values[itemsOf(path)] ?? "0");
}

function isRecord(value: unknown): value is Fields {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * The text a field starts with from what the record holds, written into
 * out by path: a value part by part, a list item by item, or on a form
 * that creates one as many empty items as its minimum.
 */
export function startValue(field: FormFieldSchema, held: unknown, path: string, out: Record<string, string>): void {
  switch (field.type) {
    case "value": {
      const value = isRecord(held) ? held : {};
      for (const part of field.parts) {
        startValue(part, value[part.name], path + "." + part.name, out);
      }
      return;
    }
    case "valueList": {
      const items = Array.isArray(held) ? (held as readonly unknown[]) : undefined;
      const count = items?.length ?? field.minimum ?? 0;
      out[itemsOf(path)] = String(count);
      for (let index = 0; index < count; index++) {
        const item = items?.[index];
        for (const part of field.parts) {
          startValue(part, isRecord(item) ? item[part.name] : undefined, path + "." + index + "." + part.name, out);
        }
      }
      return;
    }
    case "checkbox":
      out[path] = String(held ?? false);
      return;
    default:
      out[path] = held === null || held === undefined ? "" : String(held);
  }
}

/** Whether a person gave any part of the value at path: a text typed, a box ticked or an item added. */
export function given(field: FormFieldSchema, values: Values, path: string): boolean {
  switch (field.type) {
    case "value":
      return field.parts.some((part) => given(part, values, path + "." + part.name));
    case "valueList":
      return countOf(values, path) > 0;
    case "checkbox":
      return values[path] === "true";
    default:
      return (values[path] ?? "") !== "";
  }
}

/**
 * A field's value as the service takes it: a value as an object of the
 * parts given, null while an optional one has none; a list as an array of
 * its items; anything else typed as the field is.
 */
export function sentValue(field: FormFieldSchema, values: Values, path: string): unknown {
  switch (field.type) {
    case "value": {
      if (!field.required && !given(field, values, path)) {
        return null;
      }
      return partsSent(field.parts, values, path);
    }
    case "valueList":
      return Array.from({ length: countOf(values, path) }, (_, index) => partsSent(field.parts, values, path + "." + index));
    default:
      return typed(field, values[path] ?? "");
  }
}

function partsSent(parts: readonly FormFieldSchema[], values: Values, path: string): Record<string, unknown> {
  const value: Record<string, unknown> = {};
  for (const part of parts) {
    const sent = sentValue(part, values, path + "." + part.name);
    if (sent !== null) {
      value[part.name] = sent;
    }
  }
  return value;
}

/**
 * What stops a value being sent, by path: each part by its keywords, its
 * required parts once an optional value has one given, and a list's
 * number of items.
 */
export function valueProblems(field: FormFieldSchema, values: Values, path: string, texts: Texts, problems: Record<string, string>): void {
  switch (field.type) {
    case "value":
      if (field.required || given(field, values, path)) {
        for (const part of field.parts) {
          valueProblems(part, values, path + "." + part.name, texts, problems);
        }
      }
      return;
    case "valueList": {
      const count = countOf(values, path);
      if (field.minimum !== undefined && count < field.minimum) {
        problems[path] = say(texts, { text: "screens.itemsAtLeast", count: field.minimum });
      } else if (field.maximum !== undefined && count > field.maximum) {
        problems[path] = say(texts, { text: "screens.itemsAtMost", count: field.maximum });
      }
      for (let index = 0; index < count; index++) {
        for (const part of field.parts) {
          valueProblems(part, values, path + "." + index + "." + part.name, texts, problems);
        }
      }
      return;
    }
    default: {
      if (field.readOnly === true) {
        return;
      }
      const problem = fieldProblem(field, values[path] ?? "", texts);
      if (problem !== undefined) {
        problems[path] = problem;
      }
    }
  }
}

/** The values with an empty item added at the end of the list at path. */
export function addItem(field: ValueListFieldSchema, values: Values, path: string): Values {
  const count = countOf(values, path);
  const next: Record<string, string> = { ...values, [itemsOf(path)]: String(count + 1) };
  for (const part of field.parts) {
    startValue(part, undefined, path + "." + count + "." + part.name, next);
  }
  return next;
}

/** The values with the item at index taken out of the list at path, the later items moved up. */
export function removeItem(values: Values, path: string, index: number): Values {
  const prefix = path + ".";
  const next: Record<string, string> = {};
  for (const [key, value] of Object.entries(values)) {
    const at = key.startsWith(prefix) ? /^(\d+)([.#].*)$/.exec(key.slice(prefix.length)) : null;
    if (at === null) {
      next[key] = value;
      continue;
    }
    const item = Number(at[1]);
    if (item !== index) {
      next[prefix + (item > index ? item - 1 : item) + at[2]] = value;
    }
  }
  next[itemsOf(path)] = String(Math.max(0, countOf(values, path) - 1));
  return next;
}

/** The first path under a field that has a problem, to focus; undefined when none has. */
export function firstProblem(field: FormFieldSchema, problems: Readonly<Record<string, string>>): string | undefined {
  return Object.keys(problems).find((key) => key === field.name || key.startsWith(field.name + ".") || key.startsWith(field.name + "#"));
}

/** The scalar fields of a list of form fields. */
export function scalars(fields: readonly FormFieldSchema[]): readonly FieldSchema[] {
  return fields.filter((field): field is FieldSchema => !holdsValue(field));
}
