// Code generated by specarch-gen-tests-swift from ../../project/specarch.yaml, version 1.0.0, meta-model 0.1. DO NOT EDIT.

// The design tests and worked examples of Stockroom, run through the
// SpecArch.Harness the project gives them in makeHarness().

import Foundation
import Testing

/// The values, the harness and the checks the generated tests use.
enum SpecArch {
    /// A value of the design with its type, as the specification writes
    /// it: text is the value's text, kind its type in the expression
    /// language (int, uint, double, decimal, string, bool, enum, date,
    /// timestamp, duration, time, bytes or null).
    struct Value: Sendable, CustomStringConvertible {
        var kind: String
        var text: String

        static let null = Value(kind: "null", text: "")

        var description: String { kind == "null" ? "null" : "\(kind) \(text)" }
    }

    /// A record or an input: values by field or parameter name.
    typealias Record = [String: Value]

    /// What an operation or a page answers.
    struct Response: Sendable {
        var status: Int
        var body: Record
    }

    /// What a command run gives.
    struct CommandResult: Sendable {
        var exit: Int
        var output: [String]
    }

    /// What the project gives the generated tests, in a file of its own
    /// beside this one, through func makeHarness() async throws -> any
    /// SpecArch.Harness: how a caller signs in, how a record is stored and
    /// read back, how an operation is called, a command run, a page opened
    /// and an algorithm computed. Each name it takes is the mapping the
    /// implementation file gives the element, or the element's own name
    /// when it gives none. request gets the path as the specification
    /// writes it, such as /loans/{loanId}/return; the harness fills its
    /// parameters from the input record.
    protocol Harness {
        func signIn(role: String) async throws
        func insert(_ mapping: String, _ record: Record) async throws
        func records(_ mapping: String) async throws -> [Record]
        func request(_ mapping: String, method: String, path: String, input: Record) async throws -> Response
        func run(_ mapping: String, command: String, arguments: [String: [Value]], options: Record) async throws -> CommandResult
        func open(_ mapping: String, page: String, route: String, input: Record) async throws -> Response
        func emitted() async throws -> [String]
        func compute(_ mapping: String, input: Record) async throws -> Value
    }

    /// Whether two values are equal in their type: decimals and numbers by
    /// value, everything else by text.
    static func same(_ a: Value, _ b: Value) -> Bool {
        switch a.kind {
        case "decimal", "int", "uint", "double":
            guard let x = number(a.text), let y = number(b.text) else {
                return false
            }
            return x == y
        default:
            return a.kind == b.kind && a.text == b.text
        }
    }

    /// A number's text in one form, digits and a power of ten with no
    /// zero at either end of the digits, so that numbers compare exactly
    /// whatever their length; nil when the whole text is not a number.
    static func number(_ s: String) -> String? {
        guard s.range(of: #"^[+-]?([0-9]+\.?[0-9]*|\.[0-9]+)([eE][+-]?[0-9]+)?$"#, options: .regularExpression) != nil else {
            return nil
        }
        var t = Substring(s)
        var negative = false
        if let sign = t.first, sign == "+" || sign == "-" {
            negative = sign == "-"
            t = t.dropFirst()
        }
        var exponent = 0
        if let e = t.firstIndex(where: { $0 == "e" || $0 == "E" }) {
            guard let n = Int(t[t.index(after: e)...]) else {
                return nil
            }
            exponent = n
            t = t[..<e]
        }
        let parts = t.split(separator: ".", omittingEmptySubsequences: false)
        let fraction = parts.count > 1 ? parts[1] : ""
        var digits = Array(parts[0] + fraction)
        exponent -= fraction.count
        while digits.first == "0" {
            digits.removeFirst()
        }
        if digits.isEmpty {
            return "0"
        }
        while digits.last == "0" {
            digits.removeLast()
            exponent += 1
        }
        return (negative ? "-" : "") + String(digits) + "e" + String(exponent)
    }

    /// Whether a record has every value of want.
    static func holds(_ r: Record, _ want: Record) -> Bool {
        want.allSatisfy { k, v in r[k].map { same($0, v) } ?? false }
    }

    static func expectStatus(_ r: Response, _ status: Int, sourceLocation: SourceLocation = #_sourceLocation) {
        if r.status != status {
            Issue.record("status \(r.status), want \(status)", sourceLocation: sourceLocation)
        }
    }

    static func expectBody(_ r: Response, _ want: Record, sourceLocation: SourceLocation = #_sourceLocation) {
        if !holds(r.body, want) {
            Issue.record("body \(r.body) does not hold \(want)", sourceLocation: sourceLocation)
        }
    }

    static func expectExit(_ r: CommandResult, _ exit: Int, sourceLocation: SourceLocation = #_sourceLocation) {
        if r.exit != exit {
            Issue.record("exit \(r.exit), want \(exit)", sourceLocation: sourceLocation)
        }
    }

    static func expectOutput(_ r: CommandResult, _ lines: [String], sourceLocation: SourceLocation = #_sourceLocation) {
        if r.output != lines {
            Issue.record("output \(r.output), want \(lines)", sourceLocation: sourceLocation)
        }
    }

    static func expectState(_ h: any Harness, _ mapping: String, _ want: Record, sourceLocation: SourceLocation = #_sourceLocation) async throws {
        if try await !h.records(mapping).contains(where: { holds($0, want) }) {
            Issue.record("no record of \(mapping) holds \(want)", sourceLocation: sourceLocation)
        }
    }

    static func expectEmitted(_ h: any Harness, _ messages: [String], sourceLocation: SourceLocation = #_sourceLocation) async throws {
        let got = try await h.emitted()
        for m in messages where !got.contains(m) {
            Issue.record("\(m) was not published; published: \(got)", sourceLocation: sourceLocation)
        }
        if messages.isEmpty && !got.isEmpty {
            Issue.record("nothing should be published; published: \(got)", sourceLocation: sourceLocation)
        }
    }

    static func expectValue(_ got: Value, _ want: Value, example: String, sourceLocation: SourceLocation = #_sourceLocation) {
        if !same(got, want) {
            Issue.record("\(example): got \(got), want \(want)", sourceLocation: sourceLocation)
        }
    }
}

extension SpecArch {
    @Suite("Stockroom: design tests and worked examples")
    struct DesignTests {
        @Test("add-item: operation addItem, golden scenario")
        func testAddItem() async throws {
            // Given a clerk and a red lamp in stock
            // When addItem is called for a green lamp
            // Then it answers 201 with the item, both lamps are kept, and ItemAdded is published
            let h = try await makeHarness()
            try await h.signIn(role: "clerk")
            try await h.insert("items", ["colour": Value(kind: "enum", text: "red"), "name": Value(kind: "string", text: "red lamp"), "price": Value(kind: "decimal", text: "12.50"), "reserved": Value(kind: "int", text: "1"), "stock": Value(kind: "int", text: "2")])
            let got = try await h.request("addItem", method: "POST", path: "/items", input: ["colour": Value(kind: "enum", text: "green"), "name": Value(kind: "string", text: "green lamp"), "price": Value(kind: "decimal", text: "12.50"), "stock": Value(kind: "int", text: "1")])
            expectStatus(got, 201)
            expectBody(got, ["colour": Value(kind: "enum", text: "green"), "name": Value(kind: "string", text: "green lamp")])
            try await expectState(h, "items", ["name": Value(kind: "string", text: "red lamp")])
            try await expectState(h, "items", ["name": Value(kind: "string", text: "green lamp")])
            try await expectEmitted(h, ["items/ItemAdded"])
        }

        @Test("add-item-twice: operation addItem, red scenario")
        func testAddItemTwice() async throws {
            // Given a clerk and a lamp
            // When addItem is called for a lamp again
            // Then it answers 409 and publishes nothing
            let h = try await makeHarness()
            try await h.signIn(role: "clerk")
            try await h.insert("items", ["name": Value(kind: "string", text: "lamp")])
            let got = try await h.request("addItem", method: "POST", path: "/items", input: ["name": Value(kind: "string", text: "lamp")])
            expectStatus(got, 409)
            try await expectEmitted(h, [])
        }

        @Test("count-shelves: command count, golden scenario")
        func testCountShelves() async throws {
            // Given two shelves
            // When count is run on both for red
            // Then it prints the count
            let h = try await makeHarness()
            let got = try await h.run("count", command: "count", arguments: ["shelves": [Value(kind: "string", text: "a"), Value(kind: "string", text: "b")]], options: ["colour": Value(kind: "enum", text: "red")])
            expectExit(got, 0)
            expectOutput(got, ["2 items"])
        }

        @Test("item-reserved-within-stock: Item constraint reserved_within_stock, red scenario")
        func testItemReservedWithinStock() async throws {
            // Given an item with 1 in stock
            // When 2 are reserved
            // Then it is refused
            let h = try await makeHarness()
            try await bodyItemReservedWithinStock(h) // written by hand beside this file: the design gives no call to make
        }

        // item-view-offline is not applicable: The page is served with the API and has no offline mode.

        @Test("item-view-opened: page item-view, golden scenario")
        func testItemViewOpened() async throws {
            // Given an item
            // When the page opens
            // Then it shows the item
            let h = try await makeHarness()
            _ = try await h.open("item-view", page: "item-view", route: "/items/{itemId}", input: ["itemId": Value(kind: "string", text: "4f1c2a8e-3d4b-4c5a-9e7f-1a2b3c4d5e6f")])
        }

        @Test("algorithm restockCost: worked examples", arguments: [
            ("nothing missing", ["missing": Value(kind: "int", text: "0"), "unitPrice": Value(kind: "decimal", text: "2.50")] as Record, Value(kind: "decimal", text: "0.00")),
            ("three missing", ["missing": Value(kind: "int", text: "3"), "unitPrice": Value(kind: "decimal", text: "2.50")] as Record, Value(kind: "decimal", text: "7.50")),
        ])
        func testAlgorithmRestockCost(example: String, input: Record, expected: Value) async throws {
            let h = try await makeHarness()
            expectValue(try await h.compute("Stock.restockCost", input: input), expected, example: example)
        }
    }
}
