// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page removals-inbox has no red scenario for "denied with expired session"; add under tests removals-inbox-denied-with-expired-session: { page: removals-inbox, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page removals-inbox is opened", then: "it is refused as not signed in" } [test_case_missing.2799a001@specarch.yaml#/pages/removals-inbox]
// specarch-problem: warning: test_case_missing: page removals-inbox has no red scenario for "denied without members.approve"; add under tests removals-inbox-denied-without-members-approve: { page: removals-inbox, scenario: red, covers: [denied without members.approve], given: "a caller without members.approve", when: "the page removals-inbox is opened", then: "it is refused as not allowed" } [test_case_missing.d817f24c@specarch.yaml#/pages/removals-inbox]
// specarch-problem: warning: test_golden_missing: page removals-inbox has no golden scenario; add one under tests, for example removals-inbox-succeeds: { page: removals-inbox, scenario: golden, given: "a caller with members.approve", when: "the page removals-inbox is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/removals-inbox]
import type { DataPageSchema } from "@acme/screens/data";

export const schema = {
  title: "removals-inbox.title",
  permission: "members.approve",
  source: { operation: "listRemovals", path: "/removals" },
  columnDefs: [
    { field: "memberId", title: "removals-inbox.columns.memberId", sortable: false, compact: true },
    { field: "why", title: "removals-inbox.columns.why", sortable: false, compact: true },
  ],
  filters: [],
  search: false,
  pageSize: 20,
  pageSizes: [10, 20, 50],
  actions: [],
  rowActions: [
    {
      label: "removals-inbox.actions.approveRemoval.label",
      operation: "approveRemoval",
      method: "POST",
      path: "/removals/{removalId}/approve",
      parameters: { removalId: "id" },
      permission: "members.approve",
      confirm: "removals-inbox.actions.approveRemoval.confirm",
      message: "removals-inbox.actions.approveRemoval.message",
      failed: [],
    },
  ],
  empty: "removals-inbox.empty",
  filteredEmpty: "removals-inbox.filteredEmpty",
  failed: [],
  wire: {
    page: "page",
    pageSize: "pageSize",
    sort: "sort",
    search: "search",
    items: "items",
    totalItems: "totalItems",
    totalPages: "totalPages",
  },
} satisfies DataPageSchema;
