// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page removals-inbox has no red scenario for "denied with expired session"; add under tests removals-inbox-denied-with-expired-session: { page: removals-inbox, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page removals-inbox is opened", then: "it is refused as not signed in" } [test_case_missing.2799a001@specarch.yaml#/pages/removals-inbox]
// specarch-problem: warning: test_case_missing: page removals-inbox has no red scenario for "denied without members.approve"; add under tests removals-inbox-denied-without-members-approve: { page: removals-inbox, scenario: red, covers: [denied without members.approve], given: "a caller without members.approve", when: "the page removals-inbox is opened", then: "it is refused as not allowed" } [test_case_missing.d817f24c@specarch.yaml#/pages/removals-inbox]
// specarch-problem: warning: test_golden_missing: page removals-inbox has no golden scenario; add one under tests, for example removals-inbox-succeeds: { page: removals-inbox, scenario: golden, given: "a caller with members.approve", when: "the page removals-inbox is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/removals-inbox]
import type { Metadata } from "next";
import { DataPage } from "@acme/screens/data";
import { Guard } from "@/screens";
import { chosenLanguage } from "@/language";
import { stringOf, texts } from "@/strings";
import { schema } from "./page.schema";

export async function generateMetadata(): Promise<Metadata> {
  return { title: stringOf("removals-inbox.title", await chosenLanguage()) };
}

const routes = {
};

export default async function Page() {
  const t = texts(schema, await chosenLanguage());
  return (
    <Guard permission={schema.permission} texts={t}>
      <DataPage schema={schema} texts={t} routes={routes} />
    </Guard>
  );
}
