// Generated by specarch-gen-ui from ../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// The page members-list: Members. It lists members through listMembers,
// a page at a time.

import {
  on, emit,
  MEMBERS_LIST_FILTERED, MEMBERS_LIST_PAGED, MEMBERS_LIST_LOADED, MEMBERS_LIST_FAILED,
} from "./events.js";

const columns = ["cardNumber", "fullName", "email", "tier", "status", "outstandingFees"];
const pageSize = 20;

const messages = {
  empty: "No members yet. Register the first one.",
  filteredEmpty: "No member is in this tier.",
  failed: "This cannot be done right now. Try again in a moment.",
};

// What each operation's refusals say, by status: the page's failed states.
const refusals = {
  listMembers: {},
};

const actions = [
];

/** The message of a refusal of an operation, or the page's default. */
function refusal(operation, status) {
  return refusals[operation][String(status)] ?? messages.failed;
}

/** Reads the list: the filters given, then the page. Only the answer to
    the latest request counts, and a page becomes the list's page once it
    has arrived. */
function loader() {
  let filters = {};
  let page = 1;
  let latest = 0;
  async function load(wanted) {
    const ask = ++latest;
    const query = new URLSearchParams();
    for (const [name, value] of Object.entries(filters)) {
      if (value !== "") {
        query.set(name, value);
      }
    }
    const filtered = [...query.keys()].length > 0;
    query.set("page", String(wanted));
    query.set("pageSize", String(pageSize));
    try {
      const response = await fetch(`/members?${query}`, { headers: { Accept: "application/json" } });
      if (ask !== latest) {
        return;
      }
      if (!response.ok) {
        emit(MEMBERS_LIST_FAILED, { status: response.status });
        return;
      }
      const body = await response.json();
      if (ask !== latest) {
        return;
      }
      if (body.items.length === 0 && wanted > 1 && body.totalPages > 0 && wanted > body.totalPages) {
        load(body.totalPages); // the page asked for is past the last
        return;
      }
      page = wanted;
      emit(MEMBERS_LIST_LOADED, { items: body.items, totalItems: body.totalItems, totalPages: body.totalPages, page, filtered });
    } catch {
      if (ask === latest) {
        emit(MEMBERS_LIST_FAILED, { status: 0 });
      }
    }
  }
  on(MEMBERS_LIST_FILTERED, (payload) => {
    filters = payload;
    load(1);
  });
  on(MEMBERS_LIST_PAGED, (payload) => load(payload.page));
  for (const action of actions) {
    on(action.succeeded, () => load(page));
  }
  load(1);
}

/** The filters form. */
function filterForm() {
  const form = document.getElementById("filters");
  form.addEventListener("submit", (event) => {
    event.preventDefault();
    const given = [...new FormData(form)].map(([name, value]) => [name, String(value).trim()]);
    emit(MEMBERS_LIST_FILTERED, Object.fromEntries(given));
  });
}

/** The table of members. Focus in it stays on the same button, or moves
    to the table when its row is gone. */
function table() {
  const body = document.querySelector("#rows tbody");
  const head = document.querySelectorAll("#rows thead th");
  on(MEMBERS_LIST_LOADED, ({ items }) => {
    const focused = body.contains(document.activeElement) ? document.activeElement.dataset.key : undefined;
    body.replaceChildren();
    for (const row of items) {
      const tr = document.createElement("tr");
      columns.forEach((name, i) => {
        const td = document.createElement("td");
        td.className = head[i].className;
        td.textContent = row[name] ?? "";
        tr.append(td);
      });
      body.append(tr);
    }
    if (focused !== undefined) {
      const again = [...body.querySelectorAll("button")].find((button) => button.dataset.key === focused);
      (again ?? document.getElementById("rows")).focus();
    }
  });
}

/** The status line: states and the messages of events, announced without moving focus. */
function statusLine() {
  const line = document.getElementById("status");
  // An event's message stays until the person filters or pages; a state
  // gives way to the list it describes.
  let kept = false;
  function show(text, failed, keep) {
    line.textContent = text;
    line.classList.toggle("failed", failed);
    kept = keep;
  }
  on(MEMBERS_LIST_FILTERED, () => show("", false, false));
  on(MEMBERS_LIST_PAGED, () => show("", false, false));
  on(MEMBERS_LIST_LOADED, ({ items, filtered }) => {
    if (kept) {
      return;
    }
    show(items.length === 0 ? (filtered ? messages.filteredEmpty : messages.empty) : "", false, false);
  });
  on(MEMBERS_LIST_FAILED, ({ status }) => show(refusal("listMembers", status), true, false));
  for (const action of actions) {
    on(action.succeeded, () => show(action.message, false, true));
    on(action.failed, ({ status }) => show(refusal(action.operation, status), true, true));
  }
}

/** The pager. A button that is disabled while it has focus hands focus on. */
function pager() {
  const nav = document.getElementById("pager");
  const where = nav.querySelector("span");
  const [previous, next] = nav.querySelectorAll("button");
  let page = 1;
  on(MEMBERS_LIST_LOADED, (payload) => {
    page = payload.page;
    where.textContent = `Page ${payload.page} of ${Math.max(payload.totalPages, 1)}`;
    const focused = document.activeElement;
    previous.disabled = payload.page <= 1;
    next.disabled = payload.page >= payload.totalPages;
    if (focused instanceof HTMLButtonElement && nav.contains(focused) && focused.disabled) {
      const other = focused === previous ? next : previous;
      (other.disabled ? document.getElementById("rows") : other).focus();
    }
  });
  for (const button of [previous, next]) {
    button.addEventListener("click", () => emit(MEMBERS_LIST_PAGED, { page: page + Number(button.dataset.step) }));
  }
}

filterForm();
table();
statusLine();
pager();
loader();
