// Generated by specarch-gen-ui from ../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// The page members-list: Members. It lists members through listMembers,
// a page at a time.

import {
  on, emit,
  MEMBERS_LIST_FILTERED, MEMBERS_LIST_PAGED, MEMBERS_LIST_LOADED, MEMBERS_LIST_FAILED,
} from "./events.js";

const columns = ["cardNumber", "fullName", "email", "tier", "outstandingFees"];
const pageSize = 20;

const messages = {
  empty: "No members yet. Register the first one.",
  filteredEmpty: "No member is in this tier.",
  failed: "This cannot be done right now. Try again in a moment.",
};

// What each operation's refusals say, by status: the page's failed states.
const refusals = {
  listMembers: {},
};

const actions = [
];

/** The message of a refusal of an operation, or the page's default. */
function refusal(operation, status) {
  return refusals[operation][String(status)] ?? messages.failed;
}

/** Reads the list: the filters given, then the page. */
function loader() {
  let filters = {};
  let page = 1;
  async function load() {
    const query = new URLSearchParams();
    for (const [name, value] of Object.entries(filters)) {
      if (value !== "") {
        query.set(name, value);
      }
    }
    const filtered = [...query.keys()].length > 0;
    query.set("page", String(page));
    query.set("pageSize", String(pageSize));
    try {
      const response = await fetch(`/members?${query}`, { headers: { Accept: "application/json" } });
      if (!response.ok) {
        emit(MEMBERS_LIST_FAILED, { status: response.status });
        return;
      }
      const body = await response.json();
      emit(MEMBERS_LIST_LOADED, { items: body.items, totalItems: body.totalItems, totalPages: body.totalPages, page, filtered });
    } catch {
      emit(MEMBERS_LIST_FAILED, { status: 0 });
    }
  }
  on(MEMBERS_LIST_FILTERED, (payload) => {
    filters = payload;
    page = 1;
    load();
  });
  on(MEMBERS_LIST_PAGED, (payload) => {
    page = payload.page;
    load();
  });
  for (const action of actions) {
    on(action.succeeded, () => load());
  }
  load();
}

/** The filters form. */
function filterForm() {
  const form = document.getElementById("filters");
  form.addEventListener("submit", (event) => {
    event.preventDefault();
    emit(MEMBERS_LIST_FILTERED, Object.fromEntries(new FormData(form)));
  });
}

/** The table of members. */
function table() {
  const body = document.querySelector("#rows tbody");
  const head = document.querySelectorAll("#rows thead th");
  on(MEMBERS_LIST_LOADED, ({ items }) => {
    body.replaceChildren();
    for (const row of items) {
      const tr = document.createElement("tr");
      columns.forEach((name, i) => {
        const td = document.createElement("td");
        td.className = head[i].className;
        td.textContent = row[name] ?? "";
        tr.append(td);
      });
      body.append(tr);
    }
  });
}

/** The status line: states and the messages of events, announced without moving focus. */
function statusLine() {
  const line = document.getElementById("status");
  // An event's message stays until the person filters or pages; a state
  // gives way to the list it describes.
  let kept = false;
  function show(text, failed, keep) {
    line.textContent = text;
    line.classList.toggle("failed", failed);
    kept = keep;
  }
  on(MEMBERS_LIST_FILTERED, () => show("", false, false));
  on(MEMBERS_LIST_PAGED, () => show("", false, false));
  on(MEMBERS_LIST_LOADED, ({ items, filtered }) => {
    if (items.length === 0) {
      show(filtered ? messages.filteredEmpty : messages.empty, false, false);
    } else if (!kept) {
      show("", false, false);
    }
  });
  on(MEMBERS_LIST_FAILED, ({ status }) => show(refusal("listMembers", status), true, false));
  for (const action of actions) {
    on(action.succeeded, () => show(action.message, false, true));
    on(action.failed, ({ status }) => show(refusal(action.operation, status), true, true));
  }
}

/** The pager. */
function pager() {
  const nav = document.getElementById("pager");
  const where = nav.querySelector("span");
  const [previous, next] = nav.querySelectorAll("button");
  let page = 1;
  on(MEMBERS_LIST_LOADED, (payload) => {
    page = payload.page;
    where.textContent = `Page ${payload.page} of ${Math.max(payload.totalPages, 1)}`;
    previous.disabled = payload.page <= 1;
    next.disabled = payload.page >= payload.totalPages;
  });
  for (const button of [previous, next]) {
    button.addEventListener("click", () => emit(MEMBERS_LIST_PAGED, { page: page + Number(button.dataset.step) }));
  }
}

filterForm();
table();
statusLine();
pager();
loader();
