// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { FormPageSchema } from "@/screens";

export const schema = {
  title: "fee-waiver-form.title",
  permission: "fees.request",
  submit: { operation: "requestFeeWaiver", method: "POST", path: "/loans/{loanId}/fee-waivers", fields: ["amount", "reason"] },
  layout: "page",
  sections: [
    {
      fields: [
        { type: "text", name: "amount", label: "fee-waiver-form.fields.amount", required: true },
        { type: "textArea", name: "reason", label: "fee-waiver-form.fields.reason", required: true, maxLength: 500 },
      ],
    },
  ],
  rows: [],
  checks: [],
  failed: [],
  events: [{ status: 202, navigate: "loans-list", message: "fee-waiver-form.onSubmitted" }],
} satisfies FormPageSchema;
