// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page invitation has no red scenario for "violates not-the-invitation: !(password == invitation) is false"; add under tests invitation-violates-not-the-invitation-password-invitation-is-false: { page: invitation, scenario: red, covers: ["violates not-the-invitation: !(password == invitation) is false"], given: "...", when: "the page is submitted with !(password == invitation) is false", then: "it is not sent: Choose a password of your own." } [test_case_missing.0f98c397@specarch.yaml#/pages/invitation]
// specarch-problem: warning: test_case_missing: page invitation has no red scenario for "violates not-the-invitation: size(password) >= 12 is false"; add under tests invitation-violates-not-the-invitation-size-password-12-is-false: { page: invitation, scenario: red, covers: ["violates not-the-invitation: size(password) >= 12 is false"], given: "...", when: "the page is submitted with size(password) >= 12 is false", then: "it is not sent: Choose a password of your own." } [test_case_missing.41001d86@specarch.yaml#/pages/invitation]
// specarch-problem: warning: test_case_missing: page invitation has no red scenario for "violates repeated"; add under tests invitation-violates-repeated: { page: invitation, scenario: red, covers: [violates repeated], given: "...", when: "the page is submitted breaking it", then: "it is not sent: The two passwords differ." } [test_case_missing.f0d9d682@specarch.yaml#/pages/invitation]
// specarch-problem: warning: test_golden_missing: page invitation has no golden scenario; add one under tests, for example invitation-succeeds: { page: invitation, scenario: golden, given: "any caller", when: "the page invitation is submitted with every field valid", then: "it is answered 204 and leads to the page sign-in, saying: Your account is ready. Sign in." } [test_golden_missing@specarch.yaml#/pages/invitation]
// specarch-problem: warning: generator: nickname has no title, so its label is its name; give the property a title [generator@specarch.yaml#/pages/invitation/fields/3]
import type { TaskPageSchema } from "@/screens";

export const schema = {
  title: "invitation.title",
  submit: { operation: "acceptInvitation", method: "POST", path: "/invitations" },
  fields: [
    { type: "text", name: "invitation", label: "invitation.fields.invitation", required: true, maxLength: 8, pattern: "^[A-Z]{8}$" },
    {
      type: "password",
      name: "password",
      label: "invitation.fields.password",
      required: true,
      minLength: 12,
      maxLength: 128,
      rules: [
        { text: "screens.minLength", count: 12 },
        { text: "screens.maxLength", count: 128 },
      ],
    },
    {
      type: "password",
      name: "repeat",
      label: "invitation.fields.repeat",
      required: true,
      maxLength: 128,
      rules: [{ text: "screens.maxLength", count: 128 }],
    },
    { type: "text", name: "nickname", label: "invitation.fields.nickname", required: false, maxLength: 30 },
  ],
  checks: [
    {
      name: "not-the-invitation",
      rule: ["&&", ["!", ["==", ["field", "password"], ["field", "invitation"]]], [">=", ["size", ["field", "password"]], ["value", 12]]],
      message: "invitation.checks.not-the-invitation",
    },
    { name: "repeated", rule: ["==", ["field", "repeat"], ["field", "password"]], message: "invitation.checks.repeated", field: "repeat" },
  ],
  failed: [{ status: 409, problem: "invitation-used", message: "invitation.failed.invitation-used", field: "invitation" }],
  events: [{ status: 204, navigate: "sign-in", message: "invitation.onSubmitted.204", keepsReturnTo: true }],
} satisfies TaskPageSchema;
