// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page invitation has no red scenario for "violates not-the-invitation: !(password == invitation) is false"; add under tests invitation-violates-not-the-invitation-password-invitation-is-false: { page: invitation, scenario: red, covers: ["violates not-the-invitation: !(password == invitation) is false"], given: "...", when: "the page is submitted with !(password == invitation) is false", then: "it is not sent: Choose a password of your own." } [test_case_missing.0f98c397@specarch.yaml#/pages/invitation]
// specarch-problem: warning: test_case_missing: page invitation has no red scenario for "violates not-the-invitation: size(password) >= 12 is false"; add under tests invitation-violates-not-the-invitation-size-password-12-is-false: { page: invitation, scenario: red, covers: ["violates not-the-invitation: size(password) >= 12 is false"], given: "...", when: "the page is submitted with size(password) >= 12 is false", then: "it is not sent: Choose a password of your own." } [test_case_missing.41001d86@specarch.yaml#/pages/invitation]
// specarch-problem: warning: test_case_missing: page invitation has no red scenario for "violates repeated"; add under tests invitation-violates-repeated: { page: invitation, scenario: red, covers: [violates repeated], given: "...", when: "the page is submitted breaking it", then: "it is not sent: The two passwords differ." } [test_case_missing.f0d9d682@specarch.yaml#/pages/invitation]
// specarch-problem: warning: test_golden_missing: page invitation has no golden scenario; add one under tests, for example invitation-succeeds: { page: invitation, scenario: golden, given: "any caller", when: "the page invitation is submitted with every field valid", then: "it is answered 204 and leads to the page sign-in, saying: Your account is ready. Sign in." } [test_golden_missing@specarch.yaml#/pages/invitation]
// specarch-problem: warning: generator: nickname has no title, so its label is its name; give the property a title [generator@specarch.yaml#/pages/invitation/fields/3]
import type { Metadata } from "next";
import { TaskPage } from "@/screens";
import { chosenLanguage } from "@/language";
import { stringOf, texts } from "@/strings";
import { schema } from "./page.schema";

export async function generateMetadata(): Promise<Metadata> {
  return { title: stringOf("invitation.title", await chosenLanguage()) };
}

const routes = {
  "sign-in": "/sign-in",
};

export default async function Page({ searchParams }: { readonly searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { returnTo } = await searchParams;
  const t = texts(schema, await chosenLanguage());
  return <TaskPage schema={schema} texts={t} routes={routes} returnTo={typeof returnTo === "string" ? returnTo : undefined} />;
}
