// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_golden_missing: page member-form has no golden scenario; add one under tests, for example member-form-succeeds: { page: member-form, scenario: golden, given: "any caller", when: "the page member-form is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/member-form]
// specarch-problem: warning: test_red_missing: page member-form has no red scenario; add one under tests, for example member-form-refused: { page: member-form, scenario: red, given: "...", when: "...", then: "it is refused" } [test_red_missing@specarch.yaml#/pages/member-form]
// specarch-problem: warning: generator: billing.location.longitude has no title, so its label is its name; give the property a title [generator@specarch.yaml#/pages/member-form/sections/0/fields/1]
// specarch-problem: warning: generator: address.location.longitude has no title, so its label is its name; give the property a title [generator@specarch.yaml#/pages/member-form/sections/1/fields/0]
import type { Metadata } from "next";
import { FormPage, Guard } from "@/screens";
import { chosenLanguage } from "@/language";
import { stringOf, texts } from "@/strings";
import { schema } from "./page.schema";

export async function generateMetadata(): Promise<Metadata> {
  return { title: stringOf("member-form.title", await chosenLanguage()) };
}

const routes = {
  "member-view": "/members/{memberId}",
};

export default async function Page() {
  const t = texts(schema, await chosenLanguage());
  return (
    <Guard permission={schema.permission} texts={t}>
      <FormPage schema={schema} texts={t} routes={routes} />
    </Guard>
  );
}
