// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page branch-list has no red scenario for "denied with expired session"; add under tests branch-list-denied-with-expired-session: { page: branch-list, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page branch-list is opened", then: "it is refused as not signed in" } [test_case_missing.686dd861@specarch.yaml#/pages/branch-list]
// specarch-problem: warning: test_case_missing: page branch-list has no red scenario for "denied without members.read"; add under tests branch-list-denied-without-members-read: { page: branch-list, scenario: red, covers: [denied without members.read], given: "a caller without members.read", when: "the page branch-list is opened", then: "it is refused as not allowed" } [test_case_missing.fd14dc50@specarch.yaml#/pages/branch-list]
// specarch-problem: warning: test_golden_missing: page branch-list has no golden scenario; add one under tests, for example branch-list-succeeds: { page: branch-list, scenario: golden, given: "a caller with members.read", when: "the page branch-list is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/branch-list]
import assert from "node:assert/strict";
import { test } from "node:test";
import { decide } from "../screens/access.ts";
import { schema } from "../app/branches/page.schema.ts";

test("branch-list is refused to someone signed in without members.read", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: [] }), "refused");
});

test("branch-list sends someone signed out to sign in", () => {
  assert.equal(decide(schema.permission, { signedIn: false, permissions: [] }), "sign-in");
});

test("branch-list opens to someone who holds members.read", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: ["members.read"] }), "allowed");
});
