// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
import assert from "node:assert/strict";
import { test } from "node:test";
import { application } from "../application.ts";
import { visibleMenu } from "../screens/access.ts";

test("the menu shows no entry to someone signed in without its page's permission", () => {
  for (const group of application.menu) {
    for (const item of group.items) {
      if (item.permission === "public") {
        continue;
      }
      const held = application.menu.flatMap((g) => g.items.map((i) => i.permission)).filter((p) => p !== item.permission);
      const shown = visibleMenu(application.menu, { signedIn: true, permissions: held }).flatMap((g) => g.items);
      assert.ok(!shown.some((entry) => entry.route === item.route && entry.permission === item.permission), item.route);
    }
  }
});

test("the menu shows every entry to someone who holds every page's permission", () => {
  const held = application.menu.flatMap((g) => g.items.map((i) => i.permission));
  const shown = visibleMenu(application.menu, { signedIn: true, permissions: held }).flatMap((g) => g.items);
  assert.equal(shown.length, application.menu.flatMap((g) => g.items).length);
});
