// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import assert from "node:assert/strict";
import { test } from "node:test";
import { decide } from "../screens/access.ts";
import { schema } from "../app/removals/page.schema.ts";

test("removals-inbox is refused to someone signed in without members.approve", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: [] }), "refused");
});

test("removals-inbox sends someone signed out to sign in", () => {
  assert.equal(decide(schema.permission, { signedIn: false, permissions: [] }), "sign-in");
});

test("removals-inbox opens to someone who holds members.approve", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: ["members.approve"] }), "allowed");
});
