// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import assert from "node:assert/strict";
import { afterEach, test } from "node:test";
import { forward, paged } from "../server/forward.ts";
import { server } from "../server/settings.ts";

const settings = { ...server, service: "http://service.test/v1" };
const realFetch = globalThis.fetch;
const sent: Request[] = [];

function serve(answer: () => Response): void {
  globalThis.fetch = async (input: string | URL | Request, init?: RequestInit) => {
    sent.push(new Request(input, init));
    return answer();
  };
}

afterEach(() => {
  globalThis.fetch = realFetch;
  sent.length = 0;
});

function at(value: unknown, path: string): unknown {
  return path.split(".").reduce<unknown>((into, name) => (typeof into === "object" && into !== null ? (into as Record<string, unknown>)[name] : undefined), value);
}

test("a route forwards to the service with the session's token and no cookie", async () => {
  serve(() => new Response(JSON.stringify({ ok: true }), { status: 201, headers: { "content-type": "application/json", "set-cookie": "kept=1; Path=/; HttpOnly" } }));
  const request = new Request("http://app.test" + server.routes + "/things/7?q=a%20b", {
    method: "POST",
    headers: { cookie: "other=1; " + server.cookie + "=the-token", "content-type": "application/json", "x-other": "no" },
    body: JSON.stringify({ name: "x" }),
  });
  const answer = await forward(request, settings);
  assert.equal(sent.length, 1);
  assert.equal(sent[0].url, "http://service.test/v1/things/7?q=a+b");
  assert.equal(sent[0].method, "POST");
  assert.equal(sent[0].headers.get(server.header), server.scheme === "" ? "the-token" : server.scheme + " the-token");
  assert.equal(sent[0].headers.get("cookie"), null);
  assert.equal(sent[0].headers.get("x-other"), null);
  assert.deepEqual(await sent[0].json(), { name: "x" });
  assert.equal(answer.status, 201);
  assert.deepEqual(await answer.json(), { ok: true });
  assert.deepEqual(answer.headers.getSetCookie(), ["kept=1; Path=/; HttpOnly"]);
});

test("a route sends no token to someone without the session's cookie", async () => {
  serve(() => new Response(null, { status: 204 }));
  const answer = await forward(new Request("http://app.test" + server.routes + "/things"), settings);
  assert.equal(sent[0].headers.get(server.header), null);
  assert.equal(answer.status, 204);
});

test("a route answers 502 when the service cannot be reached", async () => {
  globalThis.fetch = async () => {
    throw new TypeError("unreachable");
  };
  assert.equal((await forward(new Request("http://app.test" + server.routes + "/things"), settings)).status, 502);
  assert.equal((await forward(new Request("http://app.test" + server.routes + "/things"), { ...settings, service: "" })).status, 502);
});

test("a route pages a list the service answers whole", async () => {
  serve(() => Response.json(Array.from({ length: 45 }, (_, i) => ({ n: i }))));
  const query = "?" + server.wire.page + "=2&" + server.wire.pageSize + "=20&status=open";
  const answer = await paged(new Request("http://app.test" + server.routes + "/things" + query), settings, { pageSize: 20, maximum: 50 });
  assert.equal(sent[0].url, "http://service.test/v1/things?status=open");
  const body: unknown = await answer.json();
  assert.deepEqual(at(body, server.wire.items), Array.from({ length: 20 }, (_, i) => ({ n: 20 + i })));
  assert.equal(at(body, server.wire.totalItems), 45);
  assert.equal(at(body, server.wire.totalPages), 3);
});

test("a route refuses a page size above the maximum without calling the service", async () => {
  serve(() => Response.json([]));
  const query = "?" + server.wire.pageSize + "=51";
  const answer = await paged(new Request("http://app.test" + server.routes + "/things" + query), settings, { pageSize: 20, maximum: 50 });
  assert.equal(answer.status, 400);
  assert.equal(sent.length, 0);
});
