-- Generated by specarch-gen-sql from ../project/specarch.yaml, version 1.0.0; meta-model 0.1; postgresql through type-rendering 1.2.0. Do not edit this file: a change to the schema is a new migration.
-- Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.

CREATE TABLE books (
    id UUID NOT NULL,
    title VARCHAR(300) NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);
