// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/0.1.0.yaml beside the specification; this file is not the approved output.
import type { ServerSettings } from "./forward";

/**
 * Where the server routes answer and forward, how they carry the session's
 * token to the service, and the request headers they send on.
 */
export const server: ServerSettings = {
  routes: "/api",
  service: process.env.SERVICE_URL ?? "",
  cookie: "session",
  header: "Authorization",
  scheme: "Bearer",
  headers: ["accept", "content-type", "idempotency-key"],
  wire: { page: "page", pageSize: "pageSize", items: "items", totalItems: "totalItems", totalPages: "totalPages" },
};
