// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page member-change has no red scenario for "not found memberId"; add under tests member-change-not-found-member-id: { page: member-change, scenario: red, covers: [not found memberId], given: "no record has that memberId", when: "the page member-change is opened for that memberId", then: "it says the record was not found" } [test_case_missing@specarch.yaml#/pages/member-change]
// specarch-problem: warning: test_golden_missing: page member-change has no golden scenario; add one under tests, for example member-change-succeeds: { page: member-change, scenario: golden, given: "any caller", when: "the page member-change is opened for a record that exists", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/member-change]
// specarch-problem: warning: generator: address.location.longitude has no title, so its label is its name; give the property a title [generator@specarch.yaml#/pages/member-change/fields/1]
import type { FormPageSchema } from "@/screens";

export const schema = {
  title: "member-change.title",
  permission: "public",
  source: { operation: "getMember", path: "/members/{memberId}", failed: [] },
  submit: { operation: "changeMember", method: "PATCH", path: "/members/{memberId}", fields: ["address", "phones"] },
  layout: "page",
  sections: [
    {
      fields: [
        { type: "text", name: "name", label: "member-change.fields.name", required: false, minLength: 1, maxLength: 100, readOnly: true },
        {
          type: "value",
          name: "address",
          label: "member-change.fields.address",
          required: false,
          parts: [
            { type: "text", name: "city", label: "member-change.fields.address.city", required: true, maxLength: 100 },
            {
              type: "value",
              name: "location",
              label: "member-change.fields.address.location",
              required: false,
              parts: [
                {
                  type: "number",
                  name: "latitude",
                  label: "member-change.fields.address.location.latitude",
                  required: true,
                  min: -90,
                  max: 90,
                },
                {
                  type: "number",
                  name: "longitude",
                  label: "member-change.fields.address.location.longitude",
                  required: true,
                  min: -180,
                  max: 180,
                },
              ],
            },
            { type: "text", name: "street", label: "member-change.fields.address.street", required: true, minLength: 1, maxLength: 200 },
          ],
        },
        {
          type: "valueList",
          name: "phones",
          label: "member-change.fields.phones",
          required: false,
          parts: [
            { type: "checkbox", name: "mobile", label: "member-change.fields.phones.mobile", required: false },
            {
              type: "text",
              name: "number",
              label: "member-change.fields.phones.number",
              required: true,
              maxLength: 20,
              pattern: "^[0-9 +]{6,20}$",
            },
          ],
          minimum: 1,
          maximum: 3,
        },
      ],
    },
  ],
  rows: [],
  checks: [],
  failed: [],
  events: [{ navigate: "member-view", with: { memberId: "id" }, message: "member-change.onSubmitted" }],
} satisfies FormPageSchema;
