// Code generated by specarch-gen-go-dxlib from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. DO NOT EDIT.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.

// Package catalogue is Catalogue on dxlib: its tables, the handler of each
// operation, the privileges, roles and menu items as data, and its tasks.
// Where a design gives no standard operation, a handler calls a body the
// service writes beside this file.
package catalogue

import (
	"net/http"
	"regexp"
	"unicode/utf8"

	"github.com/donnyhardyanto/dxlib/api"
	"github.com/donnyhardyanto/dxlib/tables"
	"github.com/donnyhardyanto/dxlib/task"
	"github.com/donnyhardyanto/dxlib/utils"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// Tables holds the dxlib table of each entity. An audited or softly deleted
// entity is a DXTable, which keeps its audit fields and its deleted flag;
// any other is a DXRawTable.
var Tables = struct {
	Book *tables.DXTable
}{
	Book: tables.NewDXTableSimple("catalogue", "book", "book", "", "", "id", "", "", nil, [][]string{}, []string{"title"}, []string{"title", "pages"}, []string{"shelf"}),
}

// Register binds each operation's handler to its operationId, as the
// document of the dxlib dialect names it.
func Register(a *api.DXAPI) {
	a.RegisterHandler("createBook", CreateBook)
	a.RegisterHandler("getBook", GetBook)
	a.RegisterHandler("listBooks", ListBooks)
}

// specarch-problem: warning: test_case_missing: operation createBook has no red scenario for "price not a valid decimal"; add under tests create-book-price-not-a-valid-decimal: { operation: createBook, scenario: red, covers: [price not a valid decimal], given: "...", when: "createBook is called with price that is not a valid decimal", then: "it is refused" } [test_case_missing.25cb7c7f@specarch.yaml#/paths/~1books/post]
// specarch-problem: warning: test_case_missing: operation createBook has no red scenario for "missing title"; add under tests create-book-missing-title: { operation: createBook, scenario: red, covers: [missing title], given: "...", when: "createBook is called without title", then: "it is refused" } [test_case_missing.273b5203@specarch.yaml#/paths/~1books/post]
// specarch-problem: warning: test_case_missing: operation createBook has no red scenario for "shelf not one of its values"; add under tests create-book-shelf-not-one-of-its-values: { operation: createBook, scenario: red, covers: [shelf not one of its values], given: "...", when: "createBook is called with shelf set to a value it does not allow", then: "it is refused" } [test_case_missing.8e5fb0e0@specarch.yaml#/paths/~1books/post]
// specarch-problem: warning: test_case_missing: operation createBook has no red scenario for "missing edition"; add under tests create-book-missing-edition: { operation: createBook, scenario: red, covers: [missing edition], given: "...", when: "createBook is called without edition", then: "it is refused" } [test_case_missing.953de51f@specarch.yaml#/paths/~1books/post]
// specarch-problem: warning: test_case_missing: operation createBook has no red scenario for "missing price"; add under tests create-book-missing-price: { operation: createBook, scenario: red, covers: [missing price], given: "...", when: "createBook is called without price", then: "it is refused" } [test_case_missing.9673076f@specarch.yaml#/paths/~1books/post]
// specarch-problem: warning: test_case_missing: operation createBook has no red scenario for "missing shelf"; add under tests create-book-missing-shelf: { operation: createBook, scenario: red, covers: [missing shelf], given: "...", when: "createBook is called without shelf", then: "it is refused" } [test_case_missing.9ad623fb@specarch.yaml#/paths/~1books/post]
// specarch-problem: warning: test_case_missing: operation createBook has no red scenario for "denied without books.write"; add under tests create-book-denied-without-books-write: { operation: createBook, scenario: red, covers: [denied without books.write], given: "a caller without books.write", when: "createBook is called", then: "it is refused as not allowed" } [test_case_missing.b3604f8f@specarch.yaml#/paths/~1books/post]
// specarch-problem: warning: test_case_missing: operation createBook has no red scenario for "missing pages"; add under tests create-book-missing-pages: { operation: createBook, scenario: red, covers: [missing pages], given: "...", when: "createBook is called without pages", then: "it is refused" } [test_case_missing.c2cb36c3@specarch.yaml#/paths/~1books/post]
// specarch-problem: warning: test_case_missing: operation createBook has no red scenario for "contactEmail not a valid email"; add under tests create-book-contact-email-not-a-valid-email: { operation: createBook, scenario: red, covers: [contactEmail not a valid email], given: "...", when: "createBook is called with contactEmail that is not a valid email", then: "it is refused" } [test_case_missing.ddeb7b18@specarch.yaml#/paths/~1books/post]
// specarch-problem: warning: test_golden_missing: operation createBook has no golden scenario; add one under tests, for example create-book-succeeds: { operation: createBook, scenario: golden, given: "a caller with books.write", when: "createBook is called with values inside every limit", then: "it answers 201: The book." } [test_golden_missing@specarch.yaml#/paths/~1books/post]
// CreateBookRequest holds the parameters of createBook; Has says whether one was given.
type CreateBookRequest struct {
	ContactEmail    string
	HasContactEmail bool
	Edition         int32
	HasEdition      bool
	Pages           int32
	HasPages        bool
	Price           decimal.Decimal
	HasPrice        bool
	Shelf           string
	HasShelf        bool
	Subtitle        string
	HasSubtitle     bool
	Title           string
	HasTitle        bool
}

func readCreateBookRequest(aepr *api.DXAPIEndPointRequest) (r CreateBookRequest, err error) {
	if r.HasContactEmail, r.ContactEmail, err = aepr.GetParameterValueAsString("contact_email"); err != nil {
		return r, err
	}
	if r.HasEdition, r.Edition, err = aepr.GetParameterValueAsInt32("edition"); err != nil {
		return r, err
	}
	if !r.HasEdition {
		r.Edition = 1
	}
	if r.HasPages, r.Pages, err = aepr.GetParameterValueAsInt32("pages"); err != nil {
		return r, err
	}
	if r.HasPrice, r.Price, err = aepr.GetParameterValueAsDecimal("price"); err != nil {
		return r, err
	}
	if r.HasShelf, r.Shelf, err = aepr.GetParameterValueAsString("shelf"); err != nil {
		return r, err
	}
	if r.HasSubtitle, r.Subtitle, err = aepr.GetParameterValueAsString("subtitle"); err != nil {
		return r, err
	}
	if r.HasTitle, r.Title, err = aepr.GetParameterValueAsString("title"); err != nil {
		return r, err
	}
	return r, nil
}

// checkCreateBook checks what dxlib's validator does not: the constraints the
// document lists under x-specarch-unenforced.
func checkCreateBook(aepr *api.DXAPIEndPointRequest, r CreateBookRequest) error {
	if r.HasPages && r.Pages > 5000 {
		return aepr.WriteResponseAndNewErrorf(http.StatusUnprocessableEntity, "", "%s", "INVALID_PARAMETER:pages:maximum: 5000")
	}
	if r.HasSubtitle && utf8.RuneCountInString(r.Subtitle) > 300 {
		return aepr.WriteResponseAndNewErrorf(http.StatusUnprocessableEntity, "", "%s", "INVALID_PARAMETER:subtitle:maxLength: 300")
	}
	if r.HasTitle && utf8.RuneCountInString(r.Title) > 300 {
		return aepr.WriteResponseAndNewErrorf(http.StatusUnprocessableEntity, "", "%s", "INVALID_PARAMETER:title:maxLength: 300")
	}
	return nil
}

// CreateBook handles createBook.
func CreateBook(aepr *api.DXAPIEndPointRequest) error {
	r, err := readCreateBookRequest(aepr)
	if err != nil {
		return err
	}
	if err := checkCreateBook(aepr, r); err != nil {
		return err
	}
	data := utils.JSON{}
	if r.HasContactEmail {
		data["contact_email"] = r.ContactEmail
	}
	data["edition"] = r.Edition
	if r.HasPages {
		data["pages"] = r.Pages
	}
	if r.HasPrice {
		data["price"] = r.Price
	}
	if r.HasShelf {
		data["shelf"] = r.Shelf
	}
	if r.HasSubtitle {
		data["subtitle"] = r.Subtitle
	}
	if r.HasTitle {
		data["title"] = r.Title
	}
	data["id"] = uuid.NewString()
	Tables.Book.SetInsertAuditFields(aepr, data)
	if _, _, err := Tables.Book.Insert(aepr.Context, &aepr.Log, data, nil); err != nil {
		return err
	}
	uid, _ := data["id"].(string)
	_, row, err := Tables.Book.GetByUidAuto(aepr.Context, &aepr.Log, uid)
	if err != nil {
		return err
	}
	aepr.WriteResponseAsJSON(http.StatusCreated, nil, row)
	return nil
}

// specarch-problem: warning: test_case_missing: operation getBook has no red scenario for "not found bookId"; add under tests get-book-not-found-book-id: { operation: getBook, scenario: red, covers: [not found bookId], given: "no record has that bookId", when: "getBook is called with that bookId", then: "it is refused as not found" } [test_case_missing.e3e268f7@specarch.yaml#/paths/~1books~1{bookId}/get]
// specarch-problem: warning: test_case_missing: operation getBook has no red scenario for "bookId not a valid uuid"; add under tests get-book-book-id-not-a-valid-uuid: { operation: getBook, scenario: red, covers: [bookId not a valid uuid], given: "...", when: "getBook is called with bookId that is not a valid uuid", then: "it is refused" } [test_case_missing.f97e6ca0@specarch.yaml#/paths/~1books~1{bookId}/get]
// specarch-problem: warning: test_golden_missing: operation getBook has no golden scenario; add one under tests, for example get-book-succeeds: { operation: getBook, scenario: golden, given: "any caller", when: "getBook is called with values inside every limit", then: "it answers 200: The book." } [test_golden_missing@specarch.yaml#/paths/~1books~1{bookId}/get]
// specarch-problem: warning: sensitivity_exposed: getBook is public, and its 200 response carries Book.contactEmail, which is personal; give the operation a permission, or leave the field out [sensitivity_exposed@specarch.yaml#/paths/~1books~1{bookId}/get/responses/200]
// GetBookRequest holds the parameters of getBook; Has says whether one was given.
type GetBookRequest struct {
	BookId    string
	HasBookId bool
}

func readGetBookRequest(aepr *api.DXAPIEndPointRequest) (r GetBookRequest, err error) {
	if r.HasBookId, r.BookId, err = aepr.GetParameterValueAsString("book_id"); err != nil {
		return r, err
	}
	return r, nil
}

// checkGetBook checks what dxlib's validator does not: the constraints the
// document lists under x-specarch-unenforced.
func checkGetBook(aepr *api.DXAPIEndPointRequest, r GetBookRequest) error {
	if r.HasBookId && !pattern1.MatchString(r.BookId) {
		return aepr.WriteResponseAndNewErrorf(http.StatusUnprocessableEntity, "", "%s", "INVALID_PARAMETER:book_id:format: uuid")
	}
	return nil
}

// GetBook handles getBook.
func GetBook(aepr *api.DXAPIEndPointRequest) error {
	r, err := readGetBookRequest(aepr)
	if err != nil {
		return err
	}
	if err := checkGetBook(aepr, r); err != nil {
		return err
	}
	_, row, err := Tables.Book.GetByUidNotDeletedAuto(aepr.Context, &aepr.Log, r.BookId)
	if err != nil {
		return err
	}
	if row == nil {
		return aepr.WriteResponseAndNewErrorf(http.StatusNotFound, "", "BOOK_NOT_FOUND:%s", r.BookId)
	}
	aepr.WriteResponseAsJSON(http.StatusOK, nil, row)
	return nil
}

// specarch-problem: warning: test_case_missing: operation listBooks has no red scenario for "denied without books.read"; add under tests list-books-denied-without-books-read: { operation: listBooks, scenario: red, covers: [denied without books.read], given: "a caller without books.read", when: "listBooks is called", then: "it is refused as not allowed" } [test_case_missing@specarch.yaml#/paths/~1books/get]
// specarch-problem: warning: test_golden_missing: operation listBooks has no golden scenario; add one under tests, for example list-books-succeeds: { operation: listBooks, scenario: golden, given: "a caller with books.read", when: "listBooks is called", then: "it answers 200: A page of books." } [test_golden_missing@specarch.yaml#/paths/~1books/get]
// ListBooksRequest holds the parameters of listBooks; Has says whether one was given.
type ListBooksRequest struct {
}

func readListBooksRequest(aepr *api.DXAPIEndPointRequest) (r ListBooksRequest, err error) {
	return r, nil
}

// checkListBooks checks what dxlib's validator does not: the constraints the
// document lists under x-specarch-unenforced.
func checkListBooks(aepr *api.DXAPIEndPointRequest, r ListBooksRequest) error {
	return nil
}

// ListBooks handles listBooks.
func ListBooks(aepr *api.DXAPIEndPointRequest) error {
	r, err := readListBooksRequest(aepr)
	if err != nil {
		return err
	}
	if err := checkListBooks(aepr, r); err != nil {
		return err
	}
	if _, size, err := aepr.GetParameterValueAsInt64("row_per_page"); err != nil {
		return err
	} else if size > 100 {
		return aepr.WriteResponseAndNewErrorf(http.StatusUnprocessableEntity, "", "%s", "INVALID_PARAMETER:row_per_page:maximum: 100")
	}
	return Tables.Book.RequestSearchPagingList(aepr)
}

// Privilege is a permission of the specification, as a privilege row of
// dxlib_module's user management. Seeding them is the service's.
type Privilege struct{ NameId, Description string }

// Role is a role of the specification with the privileges it grants.
type Role struct {
	NameId, Description string
	PrivilegeNameIds    []string
}

// MenuItem is an entry of the menu: a page, shown to who has its
// privilege, or a group of entries.
type MenuItem struct {
	NameId, Title, Page, PrivilegeNameId string
	Children                             []MenuItem
}

// Privileges are the specification's permissions.
var Privileges = []Privilege{
	{"books.read", "See books."},
	{"books.write", "Add books."},
}

// Roles are the specification's roles.
var Roles = []Role{
	{"desk", "The desk.", []string{"books.read", "books.write"}},
}

// MenuItems is the specification's menu.
var MenuItems = []MenuItem{}

// RegisterTasks adds a dxlib task per job that repeats at an interval. Each
// calls a job function the service writes.
func RegisterTasks() error {
	// specarch-problem: warning: test_case_missing: job sweepWithdrawn has no golden scenario for "runs twice"; add under tests sweep-withdrawn-runs-twice: { job: sweepWithdrawn, scenario: golden, covers: [runs twice], given: "the job sweepWithdrawn has run", when: "it runs again over the same records", then: "nothing changes a second time" } [test_case_missing@specarch.yaml#/jobs/sweepWithdrawn]
	// specarch-problem: warning: test_golden_missing: job sweepWithdrawn has no golden scenario; add one under tests, for example sweep-withdrawn-succeeds: { job: sweepWithdrawn, scenario: golden, given: "...", when: "the job sweepWithdrawn runs", then: "it completes" } [test_golden_missing@specarch.yaml#/jobs/sweepWithdrawn]
	// specarch-problem: warning: test_red_missing: job sweepWithdrawn has no red scenario; add one under tests, for example sweep-withdrawn-refused: { job: sweepWithdrawn, scenario: red, given: "...", when: "...", then: "it is refused" } [test_red_missing@specarch.yaml#/jobs/sweepWithdrawn]
	if _, err := task.Manager.NewTask("sweepWithdrawn", "always", 3600, jobSweepWithdrawn); err != nil {
		return err
	}
	return nil
}

// The patterns the checks match against, compiled once.
var (
	pattern1 = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
)
