// Code generated by specarch-gen-go-dxlib from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. DO NOT EDIT.

// Package catalogue is Catalogue on dxlib: its tables, the handler of each
// operation, the privileges, roles and menu items as data, and its tasks.
// Where a design gives no standard operation, a handler calls a body the
// service writes beside this file.
package catalogue

import (
	"net/http"
	"regexp"
	"unicode/utf8"

	"github.com/donnyhardyanto/dxlib/api"
	"github.com/donnyhardyanto/dxlib/tables"
	"github.com/donnyhardyanto/dxlib/task"
	"github.com/donnyhardyanto/dxlib/utils"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// Tables holds the dxlib table of each entity. An audited or softly deleted
// entity is a DXTable, which keeps its audit fields and its deleted flag;
// any other is a DXRawTable.
var Tables = struct {
	Book *tables.DXTable
}{
	Book: tables.NewDXTableSimple("catalogue", "book", "book", "", "", "id", "", "", nil, [][]string{}, []string{"title"}, []string{"title", "pages"}, []string{"shelf"}),
}

// Register binds each operation's handler to its operationId, as the
// document of the dxlib dialect names it.
func Register(a *api.DXAPI) {
	a.RegisterHandler("createBook", CreateBook)
	a.RegisterHandler("getBook", GetBook)
	a.RegisterHandler("listBooks", ListBooks)
}

// CreateBookRequest holds the parameters of createBook; Has says whether one was given.
type CreateBookRequest struct {
	ContactEmail    string
	HasContactEmail bool
	Pages           int32
	HasPages        bool
	Price           decimal.Decimal
	HasPrice        bool
	Shelf           string
	HasShelf        bool
	Title           string
	HasTitle        bool
}

func readCreateBookRequest(aepr *api.DXAPIEndPointRequest) (r CreateBookRequest, err error) {
	if r.HasContactEmail, r.ContactEmail, err = aepr.GetParameterValueAsString("contact_email"); err != nil {
		return r, err
	}
	if r.HasPages, r.Pages, err = aepr.GetParameterValueAsInt32("pages"); err != nil {
		return r, err
	}
	if r.HasPrice, r.Price, err = aepr.GetParameterValueAsDecimal("price"); err != nil {
		return r, err
	}
	if r.HasShelf, r.Shelf, err = aepr.GetParameterValueAsString("shelf"); err != nil {
		return r, err
	}
	if r.HasTitle, r.Title, err = aepr.GetParameterValueAsString("title"); err != nil {
		return r, err
	}
	return r, nil
}

// checkCreateBook checks what dxlib's validator does not: the constraints the
// document lists under x-specarch-unenforced.
func checkCreateBook(aepr *api.DXAPIEndPointRequest, r CreateBookRequest) error {
	if r.HasPages && r.Pages > 5000 {
		return aepr.WriteResponseAndNewErrorf(http.StatusUnprocessableEntity, "", "%s", "INVALID_PARAMETER:pages:maximum: 5000")
	}
	if r.HasTitle && utf8.RuneCountInString(r.Title) > 300 {
		return aepr.WriteResponseAndNewErrorf(http.StatusUnprocessableEntity, "", "%s", "INVALID_PARAMETER:title:maxLength: 300")
	}
	return nil
}

// CreateBook handles createBook.
func CreateBook(aepr *api.DXAPIEndPointRequest) error {
	r, err := readCreateBookRequest(aepr)
	if err != nil {
		return err
	}
	if err := checkCreateBook(aepr, r); err != nil {
		return err
	}
	data := utils.JSON{}
	if r.HasContactEmail {
		data["contact_email"] = r.ContactEmail
	}
	if r.HasPages {
		data["pages"] = r.Pages
	}
	if r.HasPrice {
		data["price"] = r.Price
	}
	if r.HasShelf {
		data["shelf"] = r.Shelf
	}
	if r.HasTitle {
		data["title"] = r.Title
	}
	data["id"] = uuid.NewString()
	Tables.Book.SetInsertAuditFields(aepr, data)
	if _, _, err := Tables.Book.Insert(aepr.Context, &aepr.Log, data, nil); err != nil {
		return err
	}
	uid, _ := data["id"].(string)
	_, row, err := Tables.Book.GetByUidAuto(aepr.Context, &aepr.Log, uid)
	if err != nil {
		return err
	}
	aepr.WriteResponseAsJSON(http.StatusCreated, nil, row)
	return nil
}

// GetBookRequest holds the parameters of getBook; Has says whether one was given.
type GetBookRequest struct {
	BookId    string
	HasBookId bool
}

func readGetBookRequest(aepr *api.DXAPIEndPointRequest) (r GetBookRequest, err error) {
	if r.HasBookId, r.BookId, err = aepr.GetParameterValueAsString("book_id"); err != nil {
		return r, err
	}
	return r, nil
}

// checkGetBook checks what dxlib's validator does not: the constraints the
// document lists under x-specarch-unenforced.
func checkGetBook(aepr *api.DXAPIEndPointRequest, r GetBookRequest) error {
	if r.HasBookId && !pattern1.MatchString(r.BookId) {
		return aepr.WriteResponseAndNewErrorf(http.StatusUnprocessableEntity, "", "%s", "INVALID_PARAMETER:book_id:format: uuid")
	}
	return nil
}

// GetBook handles getBook.
func GetBook(aepr *api.DXAPIEndPointRequest) error {
	r, err := readGetBookRequest(aepr)
	if err != nil {
		return err
	}
	if err := checkGetBook(aepr, r); err != nil {
		return err
	}
	_, row, err := Tables.Book.GetByUidNotDeletedAuto(aepr.Context, &aepr.Log, r.BookId)
	if err != nil {
		return err
	}
	if row == nil {
		return aepr.WriteResponseAndNewErrorf(http.StatusNotFound, "", "BOOK_NOT_FOUND:%s", r.BookId)
	}
	aepr.WriteResponseAsJSON(http.StatusOK, nil, row)
	return nil
}

// ListBooksRequest holds the parameters of listBooks; Has says whether one was given.
type ListBooksRequest struct {
}

func readListBooksRequest(aepr *api.DXAPIEndPointRequest) (r ListBooksRequest, err error) {
	return r, nil
}

// checkListBooks checks what dxlib's validator does not: the constraints the
// document lists under x-specarch-unenforced.
func checkListBooks(aepr *api.DXAPIEndPointRequest, r ListBooksRequest) error {
	return nil
}

// ListBooks handles listBooks.
func ListBooks(aepr *api.DXAPIEndPointRequest) error {
	r, err := readListBooksRequest(aepr)
	if err != nil {
		return err
	}
	if err := checkListBooks(aepr, r); err != nil {
		return err
	}
	if _, size, err := aepr.GetParameterValueAsInt64("row_per_page"); err != nil {
		return err
	} else if size > 100 {
		return aepr.WriteResponseAndNewErrorf(http.StatusUnprocessableEntity, "", "%s", "INVALID_PARAMETER:row_per_page:maximum: 100")
	}
	return Tables.Book.RequestSearchPagingList(aepr)
}

// Privilege is a permission of the specification, as a privilege row of
// dxlib_module's user management. Seeding them is the service's.
type Privilege struct{ NameId, Description string }

// Role is a role of the specification with the privileges it grants.
type Role struct {
	NameId, Description string
	PrivilegeNameIds    []string
}

// MenuItem is an entry of the menu: a page, shown to who has its
// privilege, or a group of entries.
type MenuItem struct {
	NameId, Title, Page, PrivilegeNameId string
	Children                             []MenuItem
}

// Privileges are the specification's permissions.
var Privileges = []Privilege{
	{"books.read", "See books."},
	{"books.write", "Add books."},
}

// Roles are the specification's roles.
var Roles = []Role{
	{"desk", "The desk.", []string{"books.read", "books.write"}},
}

// MenuItems is the specification's menu.
var MenuItems = []MenuItem{}

// RegisterTasks adds a dxlib task per job that repeats at an interval. Each
// calls a job function the service writes.
func RegisterTasks() error {
	if _, err := task.Manager.NewTask("sweepWithdrawn", "always", 3600, jobSweepWithdrawn); err != nil {
		return err
	}
	return nil
}

// The patterns the checks match against, compiled once.
var (
	pattern1 = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
)
