// Generated by specarch-gen-ui from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page books-list has no red scenario for "denied without books.read"; add under tests books-list-denied-without-books-read: { page: books-list, scenario: red, covers: [denied without books.read], given: "a caller without books.read", when: "the page books-list is opened", then: "it is refused as not allowed" } [test_case_missing@specarch.yaml#/pages/books-list]
// specarch-problem: warning: test_golden_missing: page books-list has no golden scenario; add one under tests, for example books-list-succeeds: { page: books-list, scenario: golden, given: "a caller with books.read", when: "the page books-list is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/books-list]
// The page books-list: Books. It lists books through listBooks, a page
// at a time, and runs withdrawBook on a row.

import {
  on, emit,
  BOOKS_LIST_FILTERED, BOOKS_LIST_PAGED, BOOKS_LIST_LOADED, BOOKS_LIST_FAILED,
  WITHDRAW_BOOK_SUCCEEDED, WITHDRAW_BOOK_FAILED,
} from "./events.js";

const columns = ["title", "shelf"];
const pageSize = 25;

const messages = {
  empty: "The catalogue is empty.",
  filteredEmpty: "No book is on this shelf.",
  failed: "This cannot be done right now. Try again in a moment.",
};

// What each operation's refusals say, by status: the page's failed states.
const refusals = {
  listBooks: {},
  withdrawBook: {
    "409": "A member holds this book, so it stays in the catalogue.",
  },
};

const actions = [
  {
    label: "Withdraw",
    operation: "withdrawBook",
    method: "POST",
    path: (row) => `/books/${encodeURIComponent(row.id)}/withdraw`,
    message: "The book is withdrawn.",
    succeeded: WITHDRAW_BOOK_SUCCEEDED,
    failed: WITHDRAW_BOOK_FAILED,
  },
];

/** The message of a refusal of an operation, or the page's default. */
function refusal(operation, status) {
  return refusals[operation][String(status)] ?? messages.failed;
}

/** Reads the list: the filters given, then the page. Only the answer to
    the latest request counts, and a page becomes the list's page once it
    has arrived. */
function loader() {
  let filters = {};
  let page = 1;
  let latest = 0;
  async function load(wanted) {
    const ask = ++latest;
    const query = new URLSearchParams();
    for (const [name, value] of Object.entries(filters)) {
      if (value !== "") {
        query.set(name, value);
      }
    }
    const filtered = [...query.keys()].length > 0;
    query.set("page", String(wanted));
    query.set("pageSize", String(pageSize));
    try {
      const response = await fetch(`/books?${query}`, { headers: { Accept: "application/json" } });
      if (ask !== latest) {
        return;
      }
      if (!response.ok) {
        emit(BOOKS_LIST_FAILED, { status: response.status });
        return;
      }
      const body = await response.json();
      if (ask !== latest) {
        return;
      }
      if (body.items.length === 0 && wanted > 1 && body.totalPages > 0 && wanted > body.totalPages) {
        load(body.totalPages); // the page asked for is past the last
        return;
      }
      page = wanted;
      emit(BOOKS_LIST_LOADED, { items: body.items, totalItems: body.totalItems, totalPages: body.totalPages, page, filtered });
    } catch {
      if (ask === latest) {
        emit(BOOKS_LIST_FAILED, { status: 0 });
      }
    }
  }
  on(BOOKS_LIST_FILTERED, (payload) => {
    filters = payload;
    load(1);
  });
  on(BOOKS_LIST_PAGED, (payload) => load(payload.page));
  for (const action of actions) {
    on(action.succeeded, () => load(page));
  }
  load(1);
}

/** The filters form. */
function filterForm() {
  const form = document.getElementById("filters");
  form.addEventListener("submit", (event) => {
    event.preventDefault();
    const given = [...new FormData(form)].map(([name, value]) => [name, String(value).trim()]);
    emit(BOOKS_LIST_FILTERED, Object.fromEntries(given));
  });
}

/** Runs an action on a row, once the person confirms it, its button
    disabled while it runs. */
async function run(action, row, button) {
  if (action.confirm && !window.confirm(action.confirm)) {
    return;
  }
  button.disabled = true;
  try {
    const response = await fetch(action.path(row), { method: action.method, headers: { Accept: "application/json" } });
    if (response.ok) {
      emit(action.succeeded, { id: row.id });
    } else {
      button.disabled = false;
      emit(action.failed, { id: row.id, status: response.status });
    }
  } catch {
    button.disabled = false;
    emit(action.failed, { id: row.id, status: 0 });
  }
}

/** The table of books. Focus in it stays on the same button, or moves
    to the table when its row is gone. */
function table() {
  const body = document.querySelector("#rows tbody");
  const head = document.querySelectorAll("#rows thead th");
  on(BOOKS_LIST_LOADED, ({ items }) => {
    const focused = body.contains(document.activeElement) ? document.activeElement.dataset.key : undefined;
    body.replaceChildren();
    for (const row of items) {
      const tr = document.createElement("tr");
      columns.forEach((name, i) => {
        const td = document.createElement("td");
        td.className = head[i].className;
        td.textContent = row[name] ?? "";
        tr.append(td);
      });
      const cell = document.createElement("td");
      for (const action of actions) {
        const button = document.createElement("button");
        button.type = "button";
        button.textContent = action.label;
        button.setAttribute("aria-label", `${action.label} ${row[columns[0]] ?? ""}`.trim());
        button.dataset.key = `${action.operation} ${row.id}`;
        button.addEventListener("click", () => run(action, row, button));
        cell.append(button);
      }
      tr.append(cell);
      body.append(tr);
    }
    if (focused !== undefined) {
      const again = [...body.querySelectorAll("button")].find((button) => button.dataset.key === focused);
      (again ?? document.getElementById("rows")).focus();
    }
  });
}

/** The status line: states and the messages of events, announced without moving focus. */
function statusLine() {
  const line = document.getElementById("status");
  // An event's message stays until the person filters or pages; a state
  // gives way to the list it describes.
  let kept = false;
  function show(text, failed, keep) {
    line.textContent = text;
    line.classList.toggle("failed", failed);
    kept = keep;
  }
  on(BOOKS_LIST_FILTERED, () => show("", false, false));
  on(BOOKS_LIST_PAGED, () => show("", false, false));
  on(BOOKS_LIST_LOADED, ({ items, filtered }) => {
    if (kept) {
      return;
    }
    show(items.length === 0 ? (filtered ? messages.filteredEmpty : messages.empty) : "", false, false);
  });
  on(BOOKS_LIST_FAILED, ({ status }) => show(refusal("listBooks", status), true, false));
  for (const action of actions) {
    on(action.succeeded, () => show(action.message, false, true));
    on(action.failed, ({ status }) => show(refusal(action.operation, status), true, true));
  }
}

/** The pager. A button that is disabled while it has focus hands focus on. */
function pager() {
  const nav = document.getElementById("pager");
  const where = nav.querySelector("span");
  const [previous, next] = nav.querySelectorAll("button");
  let page = 1;
  on(BOOKS_LIST_LOADED, (payload) => {
    page = payload.page;
    where.textContent = `Page ${payload.page} of ${Math.max(payload.totalPages, 1)}`;
    const focused = document.activeElement;
    previous.disabled = payload.page <= 1;
    next.disabled = payload.page >= payload.totalPages;
    if (focused instanceof HTMLButtonElement && nav.contains(focused) && focused.disabled) {
      const other = focused === previous ? next : previous;
      (other.disabled ? document.getElementById("rows") : other).focus();
    }
  });
  for (const button of [previous, next]) {
    button.addEventListener("click", () => emit(BOOKS_LIST_PAGED, { page: page + Number(button.dataset.step) }));
  }
}

filterForm();
table();
statusLine();
pager();
loader();
