// Generated by specarch-gen-ui from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// The events the screens raise, each name declared once with its payload.
// A component subscribes where it is created; no name is a wildcard or
// computed. Set DEBUG to true to log every event.

export const DEBUG = false;

/** The filters of the books list were applied: { shelf } */
export const BOOKS_LIST_FILTERED = "BOOKS_LIST_FILTERED";
/** Another page of the books list was asked for: { page } */
export const BOOKS_LIST_PAGED = "BOOKS_LIST_PAGED";
/** A page of books arrived: { items, totalItems, totalPages, page, filtered } */
export const BOOKS_LIST_LOADED = "BOOKS_LIST_LOADED";
/** The books could not be read: { status } */
export const BOOKS_LIST_FAILED = "BOOKS_LIST_FAILED";
/** withdrawBook succeeded: { id } */
export const WITHDRAW_BOOK_SUCCEEDED = "WITHDRAW_BOOK_SUCCEEDED";
/** withdrawBook was refused or failed: { id, status } */
export const WITHDRAW_BOOK_FAILED = "WITHDRAW_BOOK_FAILED";

const handlers = new Map();

/** Calls handler with the payload of every event of that name. */
export function on(name, handler) {
  if (!handlers.has(name)) {
    handlers.set(name, []);
  }
  handlers.get(name).push(handler);
}

/** Raises an event. */
export function emit(name, payload) {
  if (DEBUG) {
    console.log(name, payload);
  }
  for (const handler of handlers.get(name) ?? []) {
    handler(payload);
  }
}
