// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/0.1.0.yaml beside the specification; this file is not the approved output.
"use client";

import {
  Button,
  InlineLoading,
  InlineNotification,
  Link,
  MultiSelect,
  OverflowMenu,
  OverflowMenuItem,
  Pagination,
  Select,
  SelectItem,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableHeader,
  TableRow,
  TableToolbar,
  TableToolbarContent,
  TableToolbarSearch,
  TextInput,
} from "@carbon/react";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState, useSyncExternalStore, type FormEvent } from "react";
import { decide } from "./access";
import { Confirm, runAction } from "./Confirm";
import { leave } from "./Notice";
import { evaluate } from "./rules";
import type { ColumnSchema, FailureSchema, ListPageSchema, RowActionSchema } from "./schema";
import { body, property, segment, service } from "./service";
import { useSession } from "./session";
import { say, type Texts } from "./texts";

export interface ListPageProps {
  readonly schema: ListPageSchema;
  readonly texts: Texts;
  readonly routes: Readonly<Record<string, string>>;
}

type Row = Readonly<Record<string, unknown>>;

interface Sort {
  readonly field: string;
  readonly descending: boolean;
}

/** One page of the list as it arrived, for the request it answers. */
interface Result {
  readonly key: string;
  readonly rows: readonly Row[];
  readonly totalItems: number;
  readonly failed?: string;
}

interface Confirming {
  readonly action: RowActionSchema;
  readonly row: Row;
}

const compactQuery = "(max-width: 41.98rem)";

function subscribeCompact(listener: () => void): () => void {
  const query = window.matchMedia(compactQuery);
  query.addEventListener("change", listener);
  return () => query.removeEventListener("change", listener);
}

/** Whether the screen is compact, below Carbon's medium breakpoint. */
function useCompact(): boolean {
  return useSyncExternalStore(subscribeCompact, () => window.matchMedia(compactQuery).matches, () => false);
}

function refusal(failed: readonly FailureSchema[], status: number): FailureSchema | undefined {
  return failed.find((f) => f.status === status) ?? failed.find((f) => f.status === undefined);
}

/** A route with its parameters taken from fields of a row. */
function fill(route: string, parameters: Readonly<Record<string, string>>, row: Row): string {
  return route.replace(/\{([^}]+)\}/g, (_, name: string) => segment(String(row[parameters[name] ?? name] ?? "")));
}

function text(value: unknown): string {
  return value === null || value === undefined ? "" : String(value);
}

/**
 * A list read from its operation a page at a time, sorted, searched and
 * filtered by the service, with its row actions, each offered while its
 * rule holds for the row and its permission is held: one runs an operation
 * on the row, and one opens a page with its route filled from the row.
 */
export function ListPage({ schema, texts, routes }: ListPageProps) {
  const pathname = usePathname();
  const session = useSession();
  const compact = useCompact();
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(schema.pageSize);
  const [sort, setSort] = useState<Sort | undefined>(undefined);
  const [search, setSearch] = useState("");
  const [filters, setFilters] = useState<Readonly<Record<string, string>>>({});
  const [shown, setShown] = useState<readonly string[]>(schema.columns.map((column) => column.field));
  const [reload, setReload] = useState(0);
  const [result, setResult] = useState<Result | undefined>(undefined);
  const [failed, setFailed] = useState("");
  const [confirming, setConfirming] = useState<Confirming | undefined>(undefined);
  const [reason, setReason] = useState("");
  const [running, setRunning] = useState(false);
  const latest = useRef("");

  const query = new URLSearchParams();
  for (const filter of schema.filters) {
    const value = filters[filter.field] ?? "";
    if (value !== "") {
      query.set(filter.query, value);
    }
  }
  if (search !== "") {
    query.set(schema.wire.search, search);
  }
  const filtered = [...query.keys()].length > 0;
  if (sort !== undefined) {
    query.set(schema.wire.sort, (sort.descending ? "-" : "") + sort.field);
  }
  query.set(schema.wire.page, String(page));
  query.set(schema.wire.pageSize, String(pageSize));
  const key = query.toString() + "#" + reload;

  useEffect(() => {
    latest.current = key;
    const url = service + schema.source.path + "?" + key.split("#")[0];
    fetch(url, { credentials: "include", headers: { Accept: "application/json" } })
      .then(async (response) => {
        const answer = response.ok ? await body(response) : undefined;
        if (latest.current !== key) {
          return;
        }
        const items = property(answer, schema.wire.items);
        if (!response.ok || !Array.isArray(items)) {
          const failure = refusal(schema.failed, response.status);
          setResult({ key, rows: [], totalItems: 0, failed: say(texts, failure?.message ?? "screens.failed") });
          return;
        }
        const totalPages = Number(property(answer, schema.wire.totalPages) ?? 0);
        if (items.length === 0 && page > 1 && totalPages > 0 && page > totalPages) {
          setPage(totalPages); // the page asked for is past the last
          return;
        }
        setResult({ key, rows: items as Row[], totalItems: Number(property(answer, schema.wire.totalItems) ?? 0) });
      })
      .catch(() => {
        if (latest.current === key) {
          setResult({ key, rows: [], totalItems: 0, failed: say(texts, "screens.failed") });
        }
      });
  }, [key, page, schema, texts]);

  const loading = result?.key !== key;
  const holds = (permission: string) => session !== undefined && session !== null && decide(permission, session) === "allowed";
  const columns = schema.columns.filter((column) => shown.includes(column.field) && (!compact || column.compact));
  const offered = (row: Row) => schema.rowActions.filter((action) => holds(action.permission) && (action.when === undefined || evaluate(action.when, row) === true));

  function sortBy(column: ColumnSchema) {
    setSort((current) => {
      if (current?.field !== column.field) {
        return { field: column.field, descending: false };
      }
      return current.descending ? undefined : { field: column.field, descending: true };
    });
    setPage(1);
  }

  function applyFilters(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    setFilters(Object.fromEntries(schema.filters.map((filter) => [filter.field, String(form.get(filter.field) ?? "").trim()])));
    setPage(1);
  }

  async function run(action: RowActionSchema, row: Row) {
    if (action.reason !== undefined && reason.trim() === "") {
      return;
    }
    setRunning(true);
    const refused = await runAction(action, row, reason, texts);
    if (refused === undefined) {
      setFailed("");
      if (action.message !== undefined) {
        leave(say(texts, action.message), pathname);
      }
      setReload((n) => n + 1);
    } else {
      setFailed(refused);
    }
    setRunning(false);
    setConfirming(undefined);
    setReason("");
  }

  function start(action: RowActionSchema, row: Row) {
    setReason("");
    if (action.confirm === undefined) {
      void run(action, row);
    } else {
      setConfirming({ action, row });
    }
  }

  const message = result?.failed ?? (result && result.rows.length === 0 ? say(texts, filtered ? schema.filteredEmpty : schema.empty) : "");

  return (
    <section className="screens-list">
      <h1>{say(texts, schema.title)}</h1>
      {failed !== "" && <InlineNotification kind="error" role="alert" lowContrast title={failed} onClose={() => setFailed("")} />}
      {schema.filters.length > 0 && (
        <form className="screens-filters" onSubmit={applyFilters}>
          {schema.filters.map((filter) =>
            filter.options !== undefined ? (
              <Select key={filter.field} id={"filter-" + filter.field} name={filter.field} labelText={say(texts, filter.title)} defaultValue="">
                <SelectItem value="" text={say(texts, "screens.any")} />
                {filter.options.map((option) => (
                  <SelectItem key={option} value={option} text={option} />
                ))}
              </Select>
            ) : (
              <TextInput
                key={filter.field}
                id={"filter-" + filter.field}
                name={filter.field}
                labelText={say(texts, filter.title)}
                type={filter.date ? "date" : "text"}
              />
            ),
          )}
          <Button type="submit" kind="secondary">
            {say(texts, "screens.filter")}
          </Button>
        </form>
      )}
      <TableContainer>
        <TableToolbar aria-label={say(texts, schema.title)}>
          <TableToolbarContent>
            {schema.search && (
              <TableToolbarSearch
                persistent
                labelText={say(texts, "screens.search")}
                placeholder={say(texts, "screens.search")}
                onChange={(event: "" | { target: HTMLInputElement }) => {
                  setSearch(event === "" ? "" : event.target.value);
                  setPage(1);
                }}
              />
            )}
            <MultiSelect
              id="screens-columns"
              titleText={say(texts, "screens.columns")}
              hideLabel
              label={say(texts, "screens.columns")}
              items={schema.columns.map((column) => column.field)}
              itemToString={(field) => say(texts, schema.columns.find((column) => column.field === field)?.title ?? "")}
              initialSelectedItems={schema.columns.map((column) => column.field)}
              onChange={({ selectedItems }) => setShown(selectedItems ?? [])}
            />
            <Button kind="ghost" onClick={() => setReload((n) => n + 1)}>
              {say(texts, "screens.refresh")}
            </Button>
            {schema.actions
              .filter((action) => holds(action.permission))
              .map((action) => (
                <Button key={action.navigate} href={routes[action.navigate]}>
                  {say(texts, action.label)}
                </Button>
              ))}
          </TableToolbarContent>
        </TableToolbar>
        <Table aria-label={say(texts, schema.title)}>
          <TableHead>
            <TableRow>
              {columns.map((column) => (
                <TableHeader
                  key={column.field}
                  isSortable={column.sortable}
                  isSortHeader={sort?.field === column.field}
                  sortDirection={sort?.field !== column.field ? "NONE" : sort.descending ? "DESC" : "ASC"}
                  onClick={column.sortable ? () => sortBy(column) : undefined}
                >
                  {say(texts, column.title)}
                </TableHeader>
              ))}
              {schema.rowActions.length > 0 && <TableHeader>{say(texts, "screens.actions")}</TableHeader>}
            </TableRow>
          </TableHead>
          <TableBody>
            {(result?.rows ?? []).map((row, index) => (
              <TableRow key={text(row[schema.columns[0]?.field ?? ""]) + "-" + index}>
                {columns.map((column, at) => (
                  <TableCell key={column.field}>
                    {at === 0 && schema.select !== undefined ? (
                      <Link href={fill(routes[schema.select.navigate] ?? "/", schema.select.with, row)}>{text(row[column.field])}</Link>
                    ) : (
                      text(row[column.field])
                    )}
                  </TableCell>
                ))}
                {schema.rowActions.length > 0 && (
                  <TableCell>
                    {offered(row).length > 0 && (
                      <OverflowMenu aria-label={say(texts, "screens.actions") + " " + text(row[columns[0]?.field ?? ""])} flipped>
                        {offered(row).map((action) =>
                          "navigate" in action ? (
                            <OverflowMenuItem key={action.label} itemText={say(texts, action.label)} href={fill(routes[action.navigate] ?? "/", action.with, row)} />
                          ) : (
                            <OverflowMenuItem key={action.label} itemText={say(texts, action.label)} onClick={() => start(action, row)} />
                          ),
                        )}
                      </OverflowMenu>
                    )}
                  </TableCell>
                )}
              </TableRow>
            ))}
          </TableBody>
        </Table>
        {loading && <InlineLoading description={say(texts, "screens.loading")} />}
        {!loading && message !== "" && <p role="status">{message}</p>}
        <Pagination
          page={page}
          pageSize={pageSize}
          pageSizes={[...schema.pageSizes]}
          totalItems={result?.totalItems ?? 0}
          onChange={({ page: wanted, pageSize: size }) => {
            setPage(wanted);
            setPageSize(size);
          }}
        />
      </TableContainer>
      {confirming?.action.confirm !== undefined && (
        <Confirm
          action={{ ...confirming.action, confirm: confirming.action.confirm }}
          texts={texts}
          reason={reason}
          running={running}
          onReason={setReason}
          onConfirm={() => void run(confirming.action, confirming.row)}
          onClose={() => setConfirming(undefined)}
        />
      )}
    </section>
  );
}
