// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
"use client";

import { ToastNotification } from "@carbon/react";
import { usePathname } from "next/navigation";
import { useEffect, useSyncExternalStore } from "react";

const key = "screens.notice";
const listeners = new Set<() => void>();

function changed(): void {
  listeners.forEach((listener) => listener());
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

function stored(): string | null {
  try {
    return sessionStorage.getItem(key);
  } catch {
    return null;
  }
}

function read(item: string | null): { text: string; path: string } | null {
  try {
    const notice: unknown = item === null ? null : JSON.parse(item);
    if (typeof notice === "object" && notice !== null && "text" in notice && "path" in notice) {
      const { text, path } = notice;
      return typeof text === "string" && typeof path === "string" ? { text, path } : null;
    }
  } catch {
    // a notice that cannot be read is not shown
  }
  return null;
}

function forget(): void {
  try {
    sessionStorage.removeItem(key);
  } catch {
    return;
  }
  changed();
}

/** Keeps a message for the page at path, announced there once it opens. */
export function leave(text: string, path: string): void {
  try {
    sessionStorage.setItem(key, JSON.stringify({ text, path }));
  } catch {
    return;
  }
  changed();
}

/**
 * The message an event left for this page, announced without moving
 * focus, until it is closed or another page opens.
 */
export function Notice() {
  const pathname = usePathname();
  const notice = read(useSyncExternalStore(subscribe, stored, () => null));
  useEffect(() => {
    const left = read(stored());
    if (left !== null && left.path !== pathname) {
      sessionStorage.removeItem(key);
    }
  }, [pathname]);
  if (notice === null || notice.path !== pathname) {
    return null;
  }
  return <ToastNotification kind="success" role="status" lowContrast title={notice.text} onClose={forget} />;
}
