// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { StringKey } from "@/strings";

/** A text to show: a string key, and the values its placeholders take. */
export interface Message {
  readonly text: StringKey;
  readonly count?: number;
  readonly pattern?: string;
}

/**
 * A rule over the values of a page, from an expression of the
 * specification: a field's value, a constant, or an operator and its
 * operands.
 */
export type Rule =
  | readonly ["field", string]
  | readonly ["value", string | number | boolean | null]
  | readonly ["!", Rule]
  | readonly ["size", Rule]
  | readonly ["==" | "!=" | "<" | "<=" | ">" | ">=" | "&&" | "||", Rule, Rule];

interface FieldBase {
  readonly name: string;
  readonly label: StringKey;
  readonly required: boolean;
}

/** A field of type string with no format the other field types take. */
export interface TextFieldSchema extends FieldBase {
  readonly type: "text";
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly pattern?: string;
}

/** A field of format email. */
export interface EmailFieldSchema extends FieldBase {
  readonly type: "email";
  readonly maxLength?: number;
}

/** A field of format password, its rules shown under it. */
export interface PasswordFieldSchema extends FieldBase {
  readonly type: "password";
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly pattern?: string;
  readonly rules: readonly Message[];
}

export type FieldSchema = TextFieldSchema | EmailFieldSchema | PasswordFieldSchema;

/** A rule across the fields, checked before the page is sent. */
export interface CheckSchema {
  readonly name: string;
  readonly rule: Rule;
  readonly message: StringKey;
  readonly field?: string;
}

/**
 * A problem the operation answers, and where the page shows it; with no
 * status, every problem the page names no message for.
 */
export interface FailureSchema {
  readonly status?: number;
  readonly problem: string;
  readonly message: StringKey;
  readonly field?: string;
}

/**
 * What a success the operation answers leads to: a page by its name, the
 * route parameters taken from the answer's body, and a message. A page
 * that keeps returnTo hands on the page sign-in was asked for from; any
 * other page gives way to it.
 */
export interface EventSchema {
  readonly status: number;
  readonly navigate?: string;
  readonly with?: Readonly<Record<string, string>>;
  readonly message?: StringKey;
  readonly keepsReturnTo?: boolean;
}

/** The operation a page sends its fields to. */
export interface SubmitSchema {
  readonly operation: string;
  readonly method: "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
}

/** A form that submits to an operation without loading a record. */
export interface TaskPageSchema {
  readonly title: StringKey;
  readonly submit: SubmitSchema;
  readonly fields: readonly FieldSchema[];
  readonly checks: readonly CheckSchema[];
  readonly failed: readonly FailureSchema[];
  readonly events: readonly EventSchema[];
}

/** A column of a list: the row's field, its title, and whether it sorts and stays on a compact screen. */
export interface ColumnSchema {
  readonly field: string;
  readonly title: StringKey;
  readonly sortable: boolean;
  readonly compact: boolean;
}

/** A filter of a list: the field, its name in the query, its title, and its values when they are a list. */
export interface FilterSchema {
  readonly field: string;
  readonly query: string;
  readonly title: StringKey;
  readonly options?: readonly string[];
  readonly date?: boolean;
}

/** An action of a list's toolbar that opens a page. */
export interface PageActionSchema {
  readonly label: StringKey;
  readonly navigate: string;
  readonly permission: string;
}

/** The reason a confirmation asks for, sent as a property of the request's body. */
export interface ReasonSchema {
  readonly property: string;
  readonly label: StringKey;
  readonly maxLength?: number;
}

/**
 * An action on a row: the operation, its path with the route parameters
 * each taken from a field of the row, who may run it and while what holds,
 * its confirmation, the reason it asks for, its message and its refusals.
 */
export interface RowActionSchema {
  readonly label: StringKey;
  readonly operation: string;
  readonly method: "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly parameters: Readonly<Record<string, string>>;
  readonly permission: string;
  readonly when?: Rule;
  readonly confirm?: StringKey;
  readonly reason?: ReasonSchema;
  readonly message?: StringKey;
  readonly failed: readonly FailureSchema[];
}

/** Where selecting a row leads: a page, its route parameters each from a field of the row. */
export interface SelectSchema {
  readonly navigate: string;
  readonly with: Readonly<Record<string, string>>;
}

/** The names of a list's request and answer on the wire, the paginated-list idiom's. */
export interface WireSchema {
  readonly page: string;
  readonly pageSize: string;
  readonly sort: string;
  readonly search: string;
  readonly items: string;
  readonly totalItems: string;
  readonly totalPages: string;
}

/** A list read a page at a time from an operation. */
export interface ListPageSchema {
  readonly title: StringKey;
  readonly permission: string;
  readonly source: { readonly operation: string; readonly path: string };
  readonly columns: readonly ColumnSchema[];
  readonly filters: readonly FilterSchema[];
  readonly search: boolean;
  readonly pageSize: number;
  readonly pageSizes: readonly number[];
  readonly actions: readonly PageActionSchema[];
  readonly rowActions: readonly RowActionSchema[];
  readonly select?: SelectSchema;
  readonly empty: StringKey;
  readonly filteredEmpty: StringKey;
  readonly failed: readonly FailureSchema[];
  readonly wire: WireSchema;
}
