// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import { application } from "@/application";

/** Where the screens call the service, empty when it answers on the page's own origin. */
export const service = application.service;

/** The JSON body of an answer, or undefined when it has none or cannot be read. */
export async function body(response: Response): Promise<unknown> {
  try {
    return await response.json();
  } catch {
    return undefined;
  }
}

/** A property of an answer's body. */
export function property(value: unknown, name: string): unknown {
  return typeof value === "object" && value !== null ? (value as Record<string, unknown>)[name] : undefined;
}

/** A value as one path segment; "." and ".." would otherwise move up the path. */
export function segment(value: string): string {
  const encoded = encodeURIComponent(value);
  return encoded === "." || encoded === ".." ? encoded.replaceAll(".", "%2E") : encoded;
}
