// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
"use client";

import { ComboBox } from "@carbon/react";
import { useEffect, useRef, useState } from "react";
import type { Fields } from "./rules";
import type { LookupFieldSchema } from "./schema";
import { body, property, service } from "./service";
import { say, type Texts } from "./texts";

export interface LookupProps {
  readonly field: LookupFieldSchema;
  /** The id of the control, the field's name unless the page holds it more than once. */
  readonly id?: string;
  readonly label: string;
  readonly value: string;
  readonly problem?: string;
  readonly texts: Texts;
  readonly readOnly: boolean;
  /** The record picked, or undefined when the choice is cleared. */
  readonly onPick: (record: Fields | undefined) => void;
}

function words(field: LookupFieldSchema, record: Fields): string {
  const shown = field.text.map((name) => record[name]).filter((part) => part !== null && part !== undefined && part !== "");
  return shown.length > 0 ? shown.map(String).join(" · ") : String(record[field.value] ?? "");
}

/**
 * A field that holds another record's key, picked in a ComboBox from the
 * records its source lists: searched by the service as the person types
 * when the source searches, and otherwise among the one page read.
 */
export function Lookup({ field, id, label, value, problem, texts, readOnly, onPick }: LookupProps) {
  const [typed, setTyped] = useState("");
  const [items, setItems] = useState<readonly Fields[]>([]);
  const [failed, setFailed] = useState(false);
  const latest = useRef("");
  const asked = field.source.search === undefined ? "" : typed;

  useEffect(() => {
    const query = new URLSearchParams();
    query.set(field.source.pageSize.name, String(field.source.pageSize.value));
    if (field.source.search !== undefined && asked !== "") {
      query.set(field.source.search, asked);
    }
    const key = query.toString();
    latest.current = key;
    fetch(service + field.source.path + "?" + key, { credentials: "include", headers: { Accept: "application/json" } })
      .then(async (response) => {
        const answer = response.ok ? await body(response) : undefined;
        if (latest.current !== key) {
          return;
        }
        const found = property(answer, field.source.items);
        setFailed(!Array.isArray(found));
        setItems(Array.isArray(found) ? found.filter((item): item is Fields => typeof item === "object" && item !== null) : []);
      })
      .catch(() => {
        if (latest.current === key) {
          setFailed(true);
          setItems([]);
        }
      });
  }, [field, asked]);

  const selected = value === "" ? null : (items.find((item) => String(item[field.value] ?? "") === value) ?? { [field.value]: value });
  const offered = selected !== null && !items.includes(selected) ? [selected, ...items] : [...items];
  const nothing = !failed && typed !== "" && offered.every((item) => !words(field, item).toLowerCase().includes(typed.toLowerCase()));
  return (
    <ComboBox<Fields>
      id={id ?? field.name}
      titleText={label}
      items={offered}
      itemToString={(item) => (item === null ? "" : words(field, item))}
      selectedItem={selected}
      shouldFilterItem={({ item, inputValue }) =>
        field.source.search !== undefined || inputValue === null || words(field, item).toLowerCase().includes(inputValue.toLowerCase())
      }
      onInputChange={(text) => setTyped(text)}
      onChange={({ selectedItem }) => onPick(selectedItem ?? undefined)}
      readOnly={readOnly}
      invalid={problem !== undefined || failed}
      invalidText={problem ?? say(texts, "screens.failed")}
      warn={nothing}
      warnText={say(texts, "screens.nothingMatches")}
      aria-required={field.required}
    />
  );
}
