-- Generated by specarch-gen-sql from ../project/specarch.yaml, version 1.0.0; meta-model 0.1; postgresql through type-rendering 1.2.0. Do not edit this file: a change to the schema is a new migration.
-- Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.

DROP VIEW book_with_author;

ALTER TABLE books ADD COLUMN subtitle VARCHAR(300);

CREATE VIEW book_with_author AS
SELECT
    t0.id,
    t0.author_id,
    t0.subtitle,
    t0.title,
    t1.name AS author_name
FROM books t0
    LEFT JOIN authors t1 ON t1.id = t0.author_id;
