// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page member-form has no red scenario for "violates notes-not-the-name"; add under tests member-form-violates-notes-not-the-name: { page: member-form, scenario: red, covers: [violates notes-not-the-name], given: "...", when: "the form is submitted breaking it", then: "it is not sent: The notes repeat the name." } [test_case_missing.1ee0813c@specarch.yaml#/pages/member-form]
// specarch-problem: warning: test_case_missing: page member-form has no red scenario for "denied with expired session"; add under tests member-form-denied-with-expired-session: { page: member-form, scenario: red, covers: [denied with expired session], given: "a caller whose session has expired", when: "the page member-form is opened", then: "it is refused as not signed in" } [test_case_missing.4453c8b5@specarch.yaml#/pages/member-form]
// specarch-problem: warning: test_case_missing: page member-form has no red scenario for "pin entered twice differently"; add under tests member-form-pin-entered-twice-differently: { page: member-form, scenario: red, covers: [pin entered twice differently], given: "...", when: "the form is submitted with two different entries of pin", then: "it is not sent, and says the two entries differ" } [test_case_missing.48e7da62@specarch.yaml#/pages/member-form]
// specarch-problem: warning: test_case_missing: page member-form has no red scenario for "denied without members.write"; add under tests member-form-denied-without-members-write: { page: member-form, scenario: red, covers: [denied without members.write], given: "a caller without members.write", when: "the page member-form is opened", then: "it is refused as not allowed" } [test_case_missing.c6088d4e@specarch.yaml#/pages/member-form]
// specarch-problem: warning: test_golden_missing: page member-form has no golden scenario; add one under tests, for example member-form-succeeds: { page: member-form, scenario: golden, given: "a caller with members.write", when: "the page member-form is opened", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/member-form]
import type { FormPageSchema } from "@/screens";

export const schema = {
  title: "member-form.title",
  permission: "members.write",
  submit: {
    operation: "createMember",
    method: "POST",
    path: "/members",
    fields: ["name", "status", "joinedOn", "homeBranchId", "visits", "newsletter", "notes", "pin"],
    idempotencyKey: "Idempotency-Key",
  },
  layout: "tabs",
  sections: [
    {
      title: "member-form.sections.0",
      fields: [
        { type: "text", name: "name", label: "member-form.fields.name", required: true, minLength: 1, maxLength: 100 },
        { type: "select", name: "status", label: "member-form.fields.status", required: true, options: ["active", "inactive"] },
        { type: "date", name: "joinedOn", label: "member-form.fields.joinedOn", required: true, hook: true },
      ],
    },
    {
      title: "member-form.sections.1",
      fields: [
        {
          type: "lookup",
          name: "homeBranchId",
          label: "member-form.fields.homeBranchId",
          required: false,
          source: {
            operation: "listBranches",
            path: "/branches",
            items: "items",
            pageSize: { name: "pageSize", value: 50 },
            search: "search",
          },
          value: "id",
          text: ["name"],
          fills: {},
        },
        {
          type: "number",
          name: "visits",
          label: "member-form.fields.visits",
          required: false,
          min: 0,
          max: 1000,
          step: 1,
          readOnlyWhen: ["==", ["field", "status"], ["value", "inactive"]],
        },
        { type: "checkbox", name: "newsletter", label: "member-form.fields.newsletter", required: false },
        { type: "textArea", name: "notes", label: "member-form.fields.notes", required: false, hiddenWhen: ["!", ["field", "newsletter"]] },
        {
          type: "text",
          name: "pin",
          label: "member-form.fields.pin",
          required: false,
          maxLength: 4,
          pattern: "^[0-9]{4}$",
          twice: "member-form.fields.pin.again",
        },
      ],
    },
  ],
  rows: [],
  checks: [
    {
      name: "notes-not-the-name",
      rule: ["!=", ["field", "notes"], ["field", "name"]],
      message: "member-form.checks.notes-not-the-name",
      field: "notes",
    },
  ],
  failed: [],
  events: [{ navigate: "member-view", with: { memberId: "id" }, message: "member-form.onSubmitted" }],
} satisfies FormPageSchema;
