// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
import { paged } from "@/server/forward";
import { server } from "@/server/settings";

/** listAllBranches: GET /branches/all, read whole from the service and answered a page at a time. */
export function GET(request: Request): Promise<Response> {
  return paged(request, server, { pageSize: 25, maximum: 100 });
}
