// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import { paged } from "@/server/forward";
import { server } from "@/server/settings";

/** listAllBranches: GET /branches/all, read whole from the service and answered a page at a time. */
export function GET(request: Request): Promise<Response> {
  return paged(request, server, { pageSize: 25, maximum: 100 });
}
