// Package gentests writes Go tests from a specification's design tests and
// worked examples: the logic of the specarch-gen-tests-go plug-in. The
// tests call a Harness the project writes, so what is stack-specific (how
// a caller signs in, how a record is stored, how a request is sent) stays
// in the project and the generated file stays the same on every stack's
// Go code.
package gentests

import (
	"encoding/json"
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// Request is what specarch writes on a plug-in's standard input.
type Request struct {
	Specarch        string           `json:"specarch"`
	Target          string           `json:"target"`
	Root            string           `json:"root"`
	Specification   map[string]any   `json:"specification"`
	Implementations []Implementation `json:"implementations"`
	Output          string           `json:"output"`
}

// Implementation is one implementation file in the request.
type Implementation struct {
	File     string         `json:"file"`
	Content  map[string]any `json:"content"`
	Settings map[string]any `json:"settings,omitempty"`
}

// File is one file the plug-in answers with.
type File struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// Diagnostic is one problem the plug-in reports, in the validator's fields.
type Diagnostic struct {
	File     string `json:"file"`
	Line     int    `json:"line"`
	Severity string `json:"severity"`
	Path     string `json:"path"`
	Rule     string `json:"rule"`
	Message  string `json:"message"`
}

// Response is what the plug-in writes on its standard output.
type Response struct {
	Files       []File       `json:"files"`
	Diagnostics []Diagnostic `json:"diagnostics"`
}

// FileName is the one file the plug-in writes in the target's folder.
const FileName = "specarch_design_test.go"

// Decode reads a request, keeping numbers as their text.
func Decode(data []byte) (*Request, error) {
	dec := json.NewDecoder(strings.NewReader(string(data)))
	dec.UseNumber()
	var r Request
	if err := dec.Decode(&r); err != nil {
		return nil, err
	}
	return &r, nil
}

// Generate writes the Go tests of a request.
func Generate(r *Request) Response {
	g := &gen{spec: r.Specification, mappings: map[string]string{}}
	pkg := "specarchtests"
	for _, impl := range r.Implementations {
		if m, ok := impl.Content["mappings"].(map[string]any); ok {
			for k, v := range m {
				if target := str(v, "target"); target != "" {
					g.mappings[k] = target
				}
			}
		}
		if p, ok := impl.Settings["package"].(string); ok && p != "" {
			pkg = p
		}
	}
	info, _ := r.Specification["info"].(map[string]any)
	g.line("// Code generated by specarch-gen-tests-go from %s, version %s, meta-model %s. DO NOT EDIT.", relRoot(r.Root, r.Output), str(info, "version"), r.Specarch)
	g.line("")
	g.line("// Package %s runs the design tests and worked examples of %s through", pkg, str(info, "title"))
	g.line("// the Harness the project gives them in newHarness.")
	g.line("package %s", pkg)
	g.line("")
	g.line(`import (`)
	g.line(`	"math/big"`)
	g.line(`	"testing"`)
	g.line(`)`)
	g.line("")
	g.b.WriteString(prelude + "\n")
	tests, _ := r.Specification["tests"].(map[string]any)
	for _, name := range sortedKeys(tests) {
		t, _ := tests[name].(map[string]any)
		g.test(name, t)
	}
	algorithms, _ := r.Specification["algorithms"].(map[string]any)
	for _, name := range sortedKeys(algorithms) {
		a, _ := algorithms[name].(map[string]any)
		g.examples(name, a)
	}
	src, err := format.Source([]byte(g.b.String()))
	if err != nil {
		return Response{Diagnostics: []Diagnostic{{File: r.Root, Line: 1, Severity: "error", Path: "/", Rule: "generator",
			Message: fmt.Sprintf("the generated Go does not parse (%v); this is a bug in specarch-gen-tests-go", err)}}}
	}
	return Response{Files: []File{{Path: FileName, Content: string(src)}}, Diagnostics: []Diagnostic{}}
}

// relRoot is the root file's path as seen from the output folder, so the
// header reads the same wherever specarch was run from.
// The plug-in runs in specarch's working folder, so both resolve from it.
func relRoot(root, output string) string {
	absRoot, err1 := filepath.Abs(filepath.FromSlash(root))
	absOut, err2 := filepath.Abs(filepath.FromSlash(output))
	if err1 != nil || err2 != nil {
		return root
	}
	rel, err := filepath.Rel(absOut, absRoot)
	if err != nil {
		return root
	}
	return filepath.ToSlash(rel)
}

// prelude is the part of every generated file that does not depend on the
// specification: the values, the harness and the checks.
const prelude = `// Value is a value of the design with its type, as the specification
// writes it: Text is the value's text, Kind its type in the expression
// language (int, uint, double, decimal, string, bool, enum, date,
// timestamp, duration, time, bytes or null).
type Value struct {
	Kind string
	Text string
}

// Record is a record or an input: values by field or parameter name.
type Record map[string]Value

// Response is what an operation or a page answers.
type Response struct {
	Status int
	Body   Record
}

// Result is what a command run gives.
type Result struct {
	Exit   int
	Output []string
}

// Harness is what the project gives the generated tests, in a file of its
// own beside this one, through func newHarness(t *testing.T) Harness: how
// a caller signs in, how a record is stored and read back, how an operation is
// called, a command run, a page opened and an algorithm computed. Each
// name it takes is the mapping the implementation file gives the element,
// or the element's own name when it gives none. Request gets the path as
// the specification writes it, such as /loans/{loanId}/return; the harness
// fills its parameters from the input record.
type Harness interface {
	SignIn(t *testing.T, role string)
	Insert(t *testing.T, mapping string, r Record)
	Records(t *testing.T, mapping string) []Record
	Request(t *testing.T, mapping, method, path string, in Record) Response
	Run(t *testing.T, mapping, command string, arguments map[string][]Value, options Record) Result
	Open(t *testing.T, mapping, page, route string, in Record) Response
	Emitted(t *testing.T) []string
	Compute(t *testing.T, mapping string, in Record) Value
}

// same reports whether two values are equal in their type: decimals and
// numbers by value, everything else by text.
func same(a, b Value) bool {
	switch a.Kind {
	case "decimal", "int", "uint", "double":
		x, okx := new(big.Rat).SetString(a.Text)
		y, oky := new(big.Rat).SetString(b.Text)
		return okx && oky && x.Cmp(y) == 0
	}
	return a.Kind == b.Kind && a.Text == b.Text
}

// holds reports whether a record has every value of want.
func holds(r, want Record) bool {
	for k, v := range want {
		if got, ok := r[k]; !ok || !same(got, v) {
			return false
		}
	}
	return true
}

func expectStatus(t *testing.T, r Response, status int) {
	t.Helper()
	if r.Status != status {
		t.Errorf("status %d, want %d", r.Status, status)
	}
}

func expectBody(t *testing.T, r Response, want Record) {
	t.Helper()
	if !holds(r.Body, want) {
		t.Errorf("body %v does not hold %v", r.Body, want)
	}
}

func expectExit(t *testing.T, r Result, exit int) {
	t.Helper()
	if r.Exit != exit {
		t.Errorf("exit %d, want %d", r.Exit, exit)
	}
}

func expectOutput(t *testing.T, r Result, lines []string) {
	t.Helper()
	if len(r.Output) != len(lines) {
		t.Errorf("output %q, want %q", r.Output, lines)
		return
	}
	for i := range lines {
		if r.Output[i] != lines[i] {
			t.Errorf("output %q, want %q", r.Output, lines)
			return
		}
	}
}

func expectState(t *testing.T, h Harness, mapping string, want Record) {
	t.Helper()
	for _, r := range h.Records(t, mapping) {
		if holds(r, want) {
			return
		}
	}
	t.Errorf("no record of %s holds %v", mapping, want)
}

func expectEmitted(t *testing.T, h Harness, messages ...string) {
	t.Helper()
	got := h.Emitted(t)
	for _, m := range messages {
		found := false
		for _, g := range got {
			found = found || g == m
		}
		if !found {
			t.Errorf("%s was not published; published: %v", m, got)
		}
	}
	if len(messages) == 0 && len(got) > 0 {
		t.Errorf("nothing should be published; published: %v", got)
	}
}

func expectValue(t *testing.T, got, want Value) {
	t.Helper()
	if !same(got, want) {
		t.Errorf("got %s %s, want %s %s", got.Kind, got.Text, want.Kind, want.Text)
	}
}`

type gen struct {
	b        strings.Builder
	spec     map[string]any
	mappings map[string]string
}

func (g *gen) line(format string, args ...any) { fmt.Fprintf(&g.b, format+"\n", args...) }

// mapping is the implementation's name for a design element, or the
// element's own name.
func (g *gen) mapping(pointer, own string) string {
	if m := g.mappings[pointer]; m != "" {
		return m
	}
	return own
}

// test writes one design test.
func (g *gen) test(name string, t map[string]any) {
	fn := "Test" + pascal(name)
	if reason := str(t, "notApplicable"); reason != "" {
		g.line("// %s is not applicable: %s", name, oneLine(reason))
		g.line("")
		return
	}
	g.line("// %s: %s, %s scenario.", fn, subjectOf(t), str(t, "scenario"))
	g.line("func %s(t *testing.T) {", fn)
	g.line("	// Given %s", oneLine(str(t, "given")))
	g.line("	// When %s", oneLine(str(t, "when")))
	g.line("	// Then %s", oneLine(str(t, "then")))
	g.line("	h := newHarness(t)")
	fixture, _ := t["fixture"].(map[string]any)
	if caller := str(fixture, "caller"); caller != "" && caller != "public" {
		g.line("	h.SignIn(t, %q)", caller)
	}
	for _, ent := range sortedKeys(fixture) {
		if ent == "caller" || strings.HasPrefix(ent, "x-") {
			continue
		}
		recs, _ := fixture[ent].([]any)
		for _, rec := range recs {
			m, _ := rec.(map[string]any)
			g.line("	h.Insert(t, %q, %s)", g.mapping("#/entities/"+ent, ent), g.record(m, g.entityFields(ent)))
		}
	}
	input, hasInput := t["input"].(map[string]any)
	expect, hasExpect := t["expect"].(map[string]any)
	call := ""
	if hasInput || hasExpect {
		call = g.call(t, input)
	}
	if call == "" {
		g.line("	body%s(t, h) // written by hand beside this file: the design gives no call to make", pascal(name))
		g.line("}")
		g.line("")
		return
	}
	g.line("	%s", call)
	checked := false
	if v, ok := expect["status"]; ok {
		g.line("	expectStatus(t, got, %s)", text(v))
		checked = true
	}
	if body, ok := expect["body"].(map[string]any); ok {
		g.line("	expectBody(t, got, %s)", g.record(body, g.responseFields(t)))
		checked = true
	}
	if v, ok := expect["exit"]; ok {
		g.line("	expectExit(t, got, %s)", text(v))
		checked = true
	}
	if lines, ok := expect["standardOutput"].([]any); ok {
		var qs []string
		for _, l := range lines {
			qs = append(qs, strconv.Quote(text(l)))
		}
		g.line("	expectOutput(t, got, []string{%s})", strings.Join(qs, ", "))
		checked = true
	}
	if state, ok := expect["state"].(map[string]any); ok {
		for _, ent := range sortedKeys(state) {
			recs, _ := state[ent].([]any)
			for _, rec := range recs {
				m, _ := rec.(map[string]any)
				g.line("	expectState(t, h, %q, %s)", g.mapping("#/entities/"+ent, ent), g.record(m, g.entityFields(ent)))
			}
		}
	}
	if emits, ok := expect["emits"].([]any); ok {
		var qs []string
		for _, e := range emits {
			qs = append(qs, strconv.Quote(text(e)))
		}
		g.line("	expectEmitted(t, h, %s)", strings.Join(qs, ", "))
	}
	if expect["emitsNothing"] == true {
		g.line("	expectEmitted(t, h)")
	}
	if !checked {
		g.line("	_ = got")
	}
	g.line("}")
	g.line("")
}

// call is the statement that makes a test's call, or "" when its subject
// is not an operation, a command or a page.
func (g *gen) call(t map[string]any, input map[string]any) string {
	switch {
	case str(t, "operation") != "":
		id := str(t, "operation")
		p, method, pointer, fields := g.operation(id)
		if p == "" {
			return ""
		}
		return fmt.Sprintf("got := h.Request(t, %q, %q, %q, %s)", g.mapping(pointer, id), strings.ToUpper(method), p, g.record(input, fields))
	case str(t, "command") != "":
		name := str(t, "command")
		cmd, _ := mapAt(g.spec, "commands", name).(map[string]any)
		argFields := map[string]map[string]any{}
		if args, ok := cmd["arguments"].([]any); ok {
			for _, a := range args {
				m, _ := a.(map[string]any)
				s, _ := m["schema"].(map[string]any)
				argFields[str(m, "name")] = s
			}
		}
		var parts []string
		args, _ := input["arguments"].(map[string]any)
		for _, k := range sortedKeys(args) {
			vals, ok := args[k].([]any)
			if !ok {
				vals = []any{args[k]}
			}
			var vs []string
			for _, v := range vals {
				vs = append(vs, g.value(v, argFields[k]))
			}
			parts = append(parts, fmt.Sprintf("%q: {%s}", k, strings.Join(vs, ", ")))
		}
		optFields := map[string]map[string]any{}
		if opts, ok := cmd["options"].(map[string]any); ok {
			for k, o := range opts {
				m, _ := o.(map[string]any)
				s, _ := m["schema"].(map[string]any)
				optFields[k] = s
			}
		}
		opts, _ := input["options"].(map[string]any)
		return fmt.Sprintf("got := h.Run(t, %q, %q, map[string][]Value{%s}, %s)", g.mapping("#/commands/"+escape(name), name), name, strings.Join(parts, ", "), g.record(opts, optFields))
	case str(t, "page") != "":
		name := str(t, "page")
		page, _ := mapAt(g.spec, "pages", name).(map[string]any)
		return fmt.Sprintf("got := h.Open(t, %q, %q, %q, %s)", g.mapping("#/pages/"+name, name), name, str(page, "route"), g.record(input, nil))
	}
	return ""
}

// operation finds an operation by its operationId: its path, method,
// pointer, and the schemas of its parameters and body fields.
func (g *gen) operation(id string) (p, method, pointer string, fields map[string]map[string]any) {
	paths, _ := g.spec["paths"].(map[string]any)
	for _, pathKey := range sortedKeys(paths) {
		item, _ := paths[pathKey].(map[string]any)
		for _, m := range []string{"get", "post", "put", "patch", "delete"} {
			op, ok := item[m].(map[string]any)
			if !ok || str(op, "operationId") != id {
				continue
			}
			fields = map[string]map[string]any{}
			for _, list := range []any{item["parameters"], op["parameters"]} {
				params, _ := list.([]any)
				for _, prm := range params {
					pm, _ := prm.(map[string]any)
					s, _ := pm["schema"].(map[string]any)
					fields[str(pm, "name")] = s
				}
			}
			if rb, ok := op["requestBody"].(map[string]any); ok {
				content, _ := rb["content"].(map[string]any)
				for _, ct := range sortedKeys(content) {
					c, _ := content[ct].(map[string]any)
					schema, _ := c["schema"].(map[string]any)
					for k, v := range g.schemaFields(schema) {
						fields[k] = v
					}
					break
				}
			}
			return pathKey, m, "#/paths/" + escape(pathKey) + "/" + m, fields
		}
	}
	return "", "", "", nil
}

// responseFields are the fields of the entity a test's operation answers
// with, for its expected status or its first success.
func (g *gen) responseFields(t map[string]any) map[string]map[string]any {
	p, method, _, _ := g.operation(str(t, "operation"))
	op, _ := mapAt(g.spec, "paths", p, method).(map[string]any)
	responses, _ := op["responses"].(map[string]any)
	expect, _ := t["expect"].(map[string]any)
	status := text(expect["status"])
	for _, code := range sortedKeys(responses) {
		if status != "" && code != status || status == "" && !strings.HasPrefix(code, "2") {
			continue
		}
		r, _ := responses[code].(map[string]any)
		content, _ := r["content"].(map[string]any)
		for _, ct := range sortedKeys(content) {
			c, _ := content[ct].(map[string]any)
			schema, _ := c["schema"].(map[string]any)
			if items, ok := schema["items"].(map[string]any); ok {
				schema = items
			}
			return g.schemaFields(schema)
		}
	}
	return nil
}

// schemaFields are an object schema's fields, through a $ref to an entity.
func (g *gen) schemaFields(schema map[string]any) map[string]map[string]any {
	if ref := str(schema, "$ref"); strings.HasPrefix(ref, "#/entities/") {
		return g.entityFields(strings.TrimPrefix(ref, "#/entities/"))
	}
	out := map[string]map[string]any{}
	props, _ := schema["properties"].(map[string]any)
	for k, v := range props {
		m, _ := v.(map[string]any)
		out[k] = m
	}
	return out
}

func (g *gen) entityFields(ent string) map[string]map[string]any {
	e, _ := mapAt(g.spec, "entities", ent).(map[string]any)
	return g.schemaFields(map[string]any{"properties": e["properties"]})
}

// examples writes one unit test per worked example of an algorithm.
func (g *gen) examples(name string, a map[string]any) {
	exs, _ := a["examples"].([]any)
	if len(exs) == 0 {
		return
	}
	inputs := map[string]map[string]any{}
	if in, ok := a["inputs"].(map[string]any); ok {
		for k, v := range in {
			m, _ := v.(map[string]any)
			inputs[k] = m
		}
	}
	output, _ := a["output"].(map[string]any)
	fn := "TestAlgorithm" + pascal(name)
	g.line("// %s runs the worked examples of algorithm %s.", fn, name)
	g.line("func %s(t *testing.T) {", fn)
	g.line("	h := newHarness(t)")
	for i, e := range exs {
		ex, _ := e.(map[string]any)
		label := str(ex, "name")
		if label == "" {
			label = fmt.Sprintf("example %d", i+1)
		}
		in, _ := ex["inputs"].(map[string]any)
		g.line("	t.Run(%q, func(t *testing.T) {", label)
		g.line("		expectValue(t, h.Compute(t, %q, %s), %s)", g.mapping("#/algorithms/"+name, name), g.record(in, inputs), g.value(ex["expected"], output))
		g.line("	})")
	}
	g.line("}")
	g.line("")
}

// record writes values by name as a Record literal, each with the type
// its field gives.
func (g *gen) record(m map[string]any, fields map[string]map[string]any) string {
	if len(m) == 0 {
		return "Record{}"
	}
	var parts []string
	for _, k := range sortedKeys(m) {
		parts = append(parts, fmt.Sprintf("%q: %s", k, g.value(m[k], fields[k])))
	}
	return "Record{" + strings.Join(parts, ", ") + "}"
}

// value writes one value as a Value literal.
func (g *gen) value(v any, field map[string]any) string {
	if v == nil {
		return `Value{Kind: "null"}`
	}
	return fmt.Sprintf("Value{Kind: %q, Text: %q}", g.kind(field, v), text(v))
}

// kind is a field's type in the expression language, or, when the field is
// not known, the type of the value as written.
func (g *gen) kind(field map[string]any, v any) string {
	if field == nil {
		switch v.(type) {
		case json.Number:
			return "double"
		case bool:
			return "bool"
		}
		return "string"
	}
	if strings.HasPrefix(str(field, "$ref"), "#/enums/") {
		return "enum"
	}
	if strings.HasPrefix(str(field, "$ref"), "#/entities/") {
		return "object"
	}
	if _, ok := field["enum"]; ok {
		return "enum"
	}
	switch str(field, "format") {
	case "int32", "int64":
		return "int"
	case "uint64":
		return "uint"
	case "double":
		return "double"
	case "decimal":
		return "decimal"
	case "date":
		return "date"
	case "date-time":
		return "timestamp"
	case "duration":
		return "duration"
	case "time":
		return "time"
	case "byte", "binary":
		return "bytes"
	}
	switch str(field, "type") {
	case "integer":
		return "int"
	case "number":
		return "double"
	case "boolean":
		return "bool"
	case "array":
		return "list"
	case "object":
		return "object"
	}
	return "string"
}

func subjectOf(t map[string]any) string {
	for _, k := range []string{"operation", "command", "page", "job", "flow", "requirement"} {
		if v := str(t, k); v != "" {
			return k + " " + v
		}
	}
	ent := str(t, "entity")
	if c := str(t, "constraint"); c != "" {
		return ent + " constraint " + c
	}
	if tr, ok := t["transition"].(map[string]any); ok {
		return fmt.Sprintf("%s transition %s to %s", ent, str(tr, "from"), str(tr, "to"))
	}
	return ent + " state machine"
}

func mapAt(m map[string]any, keys ...string) any {
	var cur any = m
	for _, k := range keys {
		mm, ok := cur.(map[string]any)
		if !ok {
			return nil
		}
		cur = mm[k]
	}
	return cur
}

func str(m any, key string) string {
	mm, _ := m.(map[string]any)
	s, _ := mm[key].(string)
	return s
}

func text(v any) string {
	switch x := v.(type) {
	case nil:
		return ""
	case string:
		return x
	case json.Number:
		return x.String()
	case bool:
		return strconv.FormatBool(x)
	}
	b, _ := json.Marshal(v)
	return string(b)
}

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }

func escape(token string) string {
	return strings.NewReplacer("~", "~0", "/", "~1").Replace(token)
}

// pascal turns a test name such as lend-a-copy into LendACopy.
func pascal(s string) string {
	var b strings.Builder
	up := true
	for _, r := range s {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			up = true
			continue
		}
		if up {
			r = unicode.ToUpper(r)
			up = false
		}
		b.WriteRune(r)
	}
	return b.String()
}

func sortedKeys(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
