package gentests

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// GoFile is the one file the Go plug-in writes in the target's folder.
const GoFile = "specarch_design_test.go"

// GenerateGo writes the Go tests of a request: one file, in the package
// the target's settings name or specarchtests.
func GenerateGo(r *Request) Response {
	s := Build(r)
	pkg := setting(r, "package")
	if pkg == "" {
		pkg = "specarchtests"
	}
	w := &writer{}
	w.line("// Code generated by specarch-gen-tests-go from %s, version %s, meta-model %s. DO NOT EDIT.", s.Root, s.Version, s.Meta)
	w.line("")
	w.line("// Package %s runs the design tests and worked examples of %s through", pkg, s.Title)
	w.line("// the Harness the project gives them in newHarness.")
	w.line("package %s", pkg)
	w.line("")
	w.line(`import (`)
	w.line(`	"math/big"`)
	w.line(`	"testing"`)
	w.line(`)`)
	w.line("")
	w.b.WriteString(goPrelude + "\n")
	for _, t := range s.Tests {
		goTest(w, t)
	}
	for _, a := range s.Algorithms {
		goAlgorithm(w, a)
	}
	src, err := format.Source([]byte(w.b.String()))
	if err != nil {
		return failed(r, fmt.Sprintf("the generated Go does not parse (%v); this is a bug in specarch-gen-tests-go", err))
	}
	return Response{Files: []File{{Path: GoFile, Content: string(src)}}, Diagnostics: []Diagnostic{}}
}

func goTest(w *writer, t Test) {
	fn := "Test" + pascal(t.Name)
	if t.NotApplicable != "" {
		w.line("// %s is not applicable: %s", t.Name, t.NotApplicable)
		w.line("")
		return
	}
	w.line("// %s: %s, %s scenario.", fn, t.Subject, t.Scenario)
	w.line("func %s(t *testing.T) {", fn)
	w.line("	// Given %s", t.Given)
	w.line("	// When %s", t.When)
	w.line("	// Then %s", t.Then)
	w.line("	h := newHarness(t)")
	if t.Caller != "" {
		w.line("	h.SignIn(t, %q)", t.Caller)
	}
	for _, s := range t.Inserts {
		w.line("	h.Insert(t, %q, %s)", s.Mapping, goRecord(s.Record))
	}
	c := t.Call
	if c == nil {
		w.line("	body%s(t, h) // written by hand beside this file: the design gives no call to make", pascal(t.Name))
		w.line("}")
		w.line("")
		return
	}
	switch c.Kind {
	case "request":
		w.line("	got := h.Request(t, %q, %q, %q, %s)", c.Mapping, c.Method, c.Path, goRecord(c.Input))
	case "run":
		var parts []string
		for _, a := range c.Arguments {
			var vs []string
			for _, v := range a.Values {
				vs = append(vs, goValue(v))
			}
			parts = append(parts, fmt.Sprintf("%q: {%s}", a.Name, strings.Join(vs, ", ")))
		}
		w.line("	got := h.Run(t, %q, %q, map[string][]Value{%s}, %s)", c.Mapping, c.Command, strings.Join(parts, ", "), goRecord(c.Options))
	case "open":
		w.line("	got := h.Open(t, %q, %q, %q, %s)", c.Mapping, c.Page, c.Route, goRecord(c.Input))
	}
	e := t.Expect
	if e.Status != "" {
		w.line("	expectStatus(t, got, %s)", e.Status)
	}
	if e.HasBody {
		w.line("	expectBody(t, got, %s)", goRecord(e.Body))
	}
	if e.Exit != "" {
		w.line("	expectExit(t, got, %s)", e.Exit)
	}
	if e.HasOutput {
		var qs []string
		for _, l := range e.Output {
			qs = append(qs, strconv.Quote(l))
		}
		w.line("	expectOutput(t, got, []string{%s})", strings.Join(qs, ", "))
	}
	for _, s := range e.State {
		w.line("	expectState(t, h, %q, %s)", s.Mapping, goRecord(s.Record))
	}
	if len(e.Emits) > 0 {
		var qs []string
		for _, m := range e.Emits {
			qs = append(qs, strconv.Quote(m))
		}
		w.line("	expectEmitted(t, h, %s)", strings.Join(qs, ", "))
	}
	if e.EmitsNothing {
		w.line("	expectEmitted(t, h)")
	}
	if !e.Checked() {
		w.line("	_ = got")
	}
	w.line("}")
	w.line("")
}

func goAlgorithm(w *writer, a Algorithm) {
	fn := "TestAlgorithm" + pascal(a.Name)
	w.line("// %s runs the worked examples of algorithm %s.", fn, a.Name)
	w.line("func %s(t *testing.T) {", fn)
	w.line("	h := newHarness(t)")
	for _, ex := range a.Examples {
		w.line("	t.Run(%q, func(t *testing.T) {", ex.Label)
		w.line("		expectValue(t, h.Compute(t, %q, %s), %s)", a.Mapping, goRecord(ex.Input), goValue(ex.Expected))
		w.line("	})")
	}
	w.line("}")
	w.line("")
}

func goRecord(fields []Field) string {
	if len(fields) == 0 {
		return "Record{}"
	}
	var parts []string
	for _, f := range fields {
		parts = append(parts, fmt.Sprintf("%q: %s", f.Name, goValue(f.Value)))
	}
	return "Record{" + strings.Join(parts, ", ") + "}"
}

func goValue(v Value) string {
	if v.Null {
		return `Value{Kind: "null"}`
	}
	return fmt.Sprintf("Value{Kind: %q, Text: %q}", v.Kind, v.Text)
}

// goPrelude is the part of every generated file that does not depend on the
// specification: the values, the harness and the checks.
const goPrelude = `// Value is a value of the design with its type, as the specification
// writes it: Text is the value's text, Kind its type in the expression
// language (int, uint, double, decimal, string, bool, enum, date,
// timestamp, duration, time, bytes or null).
type Value struct {
	Kind string
	Text string
}

// Record is a record or an input: values by field or parameter name.
type Record map[string]Value

// Response is what an operation or a page answers.
type Response struct {
	Status int
	Body   Record
}

// Result is what a command run gives.
type Result struct {
	Exit   int
	Output []string
}

// Harness is what the project gives the generated tests, in a file of its
// own beside this one, through func newHarness(t *testing.T) Harness: how
// a caller signs in, how a record is stored and read back, how an operation is
// called, a command run, a page opened and an algorithm computed. Each
// name it takes is the mapping the implementation file gives the element,
// or the element's own name when it gives none. Request gets the path as
// the specification writes it, such as /loans/{loanId}/return; the harness
// fills its parameters from the input record.
type Harness interface {
	SignIn(t *testing.T, role string)
	Insert(t *testing.T, mapping string, r Record)
	Records(t *testing.T, mapping string) []Record
	Request(t *testing.T, mapping, method, path string, in Record) Response
	Run(t *testing.T, mapping, command string, arguments map[string][]Value, options Record) Result
	Open(t *testing.T, mapping, page, route string, in Record) Response
	Emitted(t *testing.T) []string
	Compute(t *testing.T, mapping string, in Record) Value
}

// same reports whether two values are equal in their type: decimals and
// numbers by value, everything else by text.
func same(a, b Value) bool {
	switch a.Kind {
	case "decimal", "int", "uint", "double":
		x, okx := new(big.Rat).SetString(a.Text)
		y, oky := new(big.Rat).SetString(b.Text)
		return okx && oky && x.Cmp(y) == 0
	}
	return a.Kind == b.Kind && a.Text == b.Text
}

// holds reports whether a record has every value of want.
func holds(r, want Record) bool {
	for k, v := range want {
		if got, ok := r[k]; !ok || !same(got, v) {
			return false
		}
	}
	return true
}

func expectStatus(t *testing.T, r Response, status int) {
	t.Helper()
	if r.Status != status {
		t.Errorf("status %d, want %d", r.Status, status)
	}
}

func expectBody(t *testing.T, r Response, want Record) {
	t.Helper()
	if !holds(r.Body, want) {
		t.Errorf("body %v does not hold %v", r.Body, want)
	}
}

func expectExit(t *testing.T, r Result, exit int) {
	t.Helper()
	if r.Exit != exit {
		t.Errorf("exit %d, want %d", r.Exit, exit)
	}
}

func expectOutput(t *testing.T, r Result, lines []string) {
	t.Helper()
	if len(r.Output) != len(lines) {
		t.Errorf("output %q, want %q", r.Output, lines)
		return
	}
	for i := range lines {
		if r.Output[i] != lines[i] {
			t.Errorf("output %q, want %q", r.Output, lines)
			return
		}
	}
}

func expectState(t *testing.T, h Harness, mapping string, want Record) {
	t.Helper()
	for _, r := range h.Records(t, mapping) {
		if holds(r, want) {
			return
		}
	}
	t.Errorf("no record of %s holds %v", mapping, want)
}

func expectEmitted(t *testing.T, h Harness, messages ...string) {
	t.Helper()
	got := h.Emitted(t)
	for _, m := range messages {
		found := false
		for _, g := range got {
			found = found || g == m
		}
		if !found {
			t.Errorf("%s was not published; published: %v", m, got)
		}
	}
	if len(messages) == 0 && len(got) > 0 {
		t.Errorf("nothing should be published; published: %v", got)
	}
}

func expectValue(t *testing.T, got, want Value) {
	t.Helper()
	if !same(got, want) {
		t.Errorf("got %s %s, want %s %s", got.Kind, got.Text, want.Kind, want.Text)
	}
}`
