package gentests

import (
	"fmt"
	"strings"
)

// SwiftFile is the one file the Swift plug-in writes in the target's folder.
const SwiftFile = "SpecArchDesignTests.swift"

// SwiftFramework is the one testing framework the Swift plug-in writes for.
const SwiftFramework = "Swift Testing"

// GenerateSwift writes the Swift tests of a request: one file of Swift
// Testing tests, for the test target the target's folder belongs to.
func GenerateSwift(r *Request) Response {
	if _, refused := framework(r, "specarch-gen-tests-swift", SwiftFramework); refused != nil {
		return *refused
	}
	s := Build(r)
	w := &writer{}
	w.line("// Code generated by specarch-gen-tests-swift from %s, version %s, meta-model %s. DO NOT EDIT.", s.Root, s.Version, s.Meta)
	w.line("")
	w.line("// The design tests and worked examples of %s, run through the", s.Title)
	w.line("// SpecArch.Harness the project gives them in makeHarness().")
	w.line("")
	w.line("import Foundation")
	w.line("import Testing")
	w.line("")
	w.b.WriteString(swiftPrelude + "\n")
	w.line("")
	w.line("extension SpecArch {")
	w.line("    @Suite(%s)", swiftString(s.Title+": design tests and worked examples"))
	w.line("    struct DesignTests {")
	first := true
	for _, t := range s.Tests {
		if !first {
			w.line("")
		}
		first = false
		swiftTest(w, t)
	}
	for _, a := range s.Algorithms {
		if !first {
			w.line("")
		}
		first = false
		swiftAlgorithm(w, a)
	}
	w.line("    }")
	w.line("}")
	return Response{Files: []File{{Path: SwiftFile, Content: w.b.String()}}, Diagnostics: []Diagnostic{}}
}

const swiftIndent = "        "

func swiftTest(w *writer, t Test) {
	in := swiftIndent
	if t.NotApplicable != "" {
		w.line(in+"// %s is not applicable: %s", t.Name, t.NotApplicable)
		return
	}
	w.line(in+"@Test(%s)", swiftString(t.Name+": "+t.Subject+", "+t.Scenario+" scenario"))
	w.line(in+"func test%s() async throws {", pascal(t.Name))
	w.line(in+"    // Given %s", t.Given)
	w.line(in+"    // When %s", t.When)
	w.line(in+"    // Then %s", t.Then)
	w.line(in + "    let h = try await makeHarness()")
	if t.Caller != "" {
		w.line(in+"    try await h.signIn(role: %s)", swiftString(t.Caller))
	}
	for _, s := range t.Inserts {
		w.line(in+"    try await h.insert(%s, %s)", swiftString(s.Mapping), swiftRecord(s.Record))
	}
	c := t.Call
	if c == nil {
		w.line(in+"    try await body%s(h) // written by hand beside this file: the design gives no call to make", pascal(t.Name))
		w.line(in + "}")
		return
	}
	got := "let got = "
	if !t.Expect.Checked() {
		got = "_ = "
	}
	switch c.Kind {
	case "request":
		w.line(in+"    %stry await h.request(%s, method: %s, path: %s, input: %s)", got, swiftString(c.Mapping), swiftString(c.Method), swiftString(c.Path), swiftRecord(c.Input))
	case "run":
		var parts []string
		for _, a := range c.Arguments {
			var vs []string
			for _, v := range a.Values {
				vs = append(vs, swiftValue(v))
			}
			parts = append(parts, fmt.Sprintf("%s: [%s]", swiftString(a.Name), strings.Join(vs, ", ")))
		}
		args := "[:]"
		if len(parts) > 0 {
			args = "[" + strings.Join(parts, ", ") + "]"
		}
		w.line(in+"    %stry await h.run(%s, command: %s, arguments: %s, options: %s)", got, swiftString(c.Mapping), swiftString(c.Command), args, swiftRecord(c.Options))
	case "open":
		w.line(in+"    %stry await h.open(%s, page: %s, route: %s, input: %s)", got, swiftString(c.Mapping), swiftString(c.Page), swiftString(c.Route), swiftRecord(c.Input))
	}
	e := t.Expect
	if e.Status != "" {
		w.line(in+"    expectStatus(got, %s)", e.Status)
	}
	if e.HasBody {
		w.line(in+"    expectBody(got, %s)", swiftRecord(e.Body))
	}
	if e.Exit != "" {
		w.line(in+"    expectExit(got, %s)", e.Exit)
	}
	if e.HasOutput {
		w.line(in+"    expectOutput(got, %s)", swiftStrings(e.Output))
	}
	for _, s := range e.State {
		w.line(in+"    try await expectState(h, %s, %s)", swiftString(s.Mapping), swiftRecord(s.Record))
	}
	if len(e.Emits) > 0 {
		w.line(in+"    try await expectEmitted(h, %s)", swiftStrings(e.Emits))
	}
	if e.EmitsNothing {
		w.line(in + "    try await expectEmitted(h, [])")
	}
	w.line(in + "}")
}

func swiftAlgorithm(w *writer, a Algorithm) {
	in := swiftIndent
	w.line(in+"@Test(%s, arguments: [", swiftString("algorithm "+a.Name+": worked examples"))
	for _, ex := range a.Examples {
		w.line(in+"    (%s, %s as Record, %s),", swiftString(ex.Label), swiftRecord(ex.Input), swiftValue(ex.Expected))
	}
	w.line(in + "])")
	w.line(in+"func testAlgorithm%s(example: String, input: Record, expected: Value) async throws {", pascal(a.Name))
	w.line(in + "    let h = try await makeHarness()")
	w.line(in+"    expectValue(try await h.compute(%s, input: input), expected, example: example)", swiftString(a.Mapping))
	w.line(in + "}")
}

func swiftRecord(fields []Field) string {
	if len(fields) == 0 {
		return "[:]"
	}
	var parts []string
	for _, f := range fields {
		parts = append(parts, swiftString(f.Name)+": "+swiftValue(f.Value))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func swiftValue(v Value) string {
	if v.Null {
		return "Value.null"
	}
	out := fmt.Sprintf("Value(kind: %s, text: %s", swiftString(v.Kind), swiftString(v.Text))
	if len(v.Parts) > 0 {
		out += ", parts: " + swiftRecord(v.Parts)
	}
	if len(v.Items) > 0 {
		var items []string
		for _, item := range v.Items {
			items = append(items, swiftValue(item))
		}
		out += ", items: [" + strings.Join(items, ", ") + "]"
	}
	return out + ")"
}

func swiftStrings(list []string) string {
	var qs []string
	for _, s := range list {
		qs = append(qs, swiftString(s))
	}
	return "[" + strings.Join(qs, ", ") + "]"
}

// swiftString is a Swift string literal of s.
func swiftString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '\\':
			b.WriteString(`\\`)
		case r == '"':
			b.WriteString(`\"`)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\r':
			b.WriteString(`\r`)
		case r == '\t':
			b.WriteString(`\t`)
		case r < 0x20 || r == 0x7f:
			fmt.Fprintf(&b, `\u{%x}`, r)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// refusedFramework is the answer to an implementation file whose testing
// framework the plug-in does not write for: refused by name rather than
// written in another framework the project does not run.
func refusedFramework(file, got, plugin, wants string) Response {
	return Response{Files: []File{}, Diagnostics: []Diagnostic{{File: file, Line: 1, Severity: "error", Path: "/testing/framework", Rule: "generator",
		Message: fmt.Sprintf("%s writes tests for %s, and this implementation file's testing framework is %q; name %s there, or write these tests by hand", plugin, wants, got, wants)}}}
}

// swiftPrelude is the part of every generated Swift file that does not
// depend on the specification: the values, the harness and the checks.
const swiftPrelude = `/// The values, the harness and the checks the generated tests use.
enum SpecArch {
    /// A value of the design with its type, as the specification writes
    /// it: text is the value's text, kind its type in the expression
    /// language (int, uint, double, decimal, string, bool, enum, date,
    /// timestamp, duration, time, bytes, object, list or null). An object,
    /// such as a value object, has its parts in parts and a list its items
    /// in items, each with its own type; text is then the value as JSON.
    struct Value: Sendable, CustomStringConvertible {
        var kind: String
        var text: String
        var parts: Record = [:]
        var items: [Value] = []

        static let null = Value(kind: "null", text: "")

        var description: String { kind == "null" ? "null" : "\(kind) \(text)" }
    }

    /// A record or an input: values by field or parameter name.
    typealias Record = [String: Value]

    /// What an operation or a page answers.
    struct Response: Sendable {
        var status: Int
        var body: Record
    }

    /// What a command run gives.
    struct CommandResult: Sendable {
        var exit: Int
        var output: [String]
    }

    /// What the project gives the generated tests, in a file of its own
    /// beside this one, through func makeHarness() async throws -> any
    /// SpecArch.Harness: how a caller signs in, how a record is stored and
    /// read back, how an operation is called, a command run, a page opened
    /// and an algorithm computed. Each name it takes is the mapping the
    /// implementation file gives the element, or the element's own name
    /// when it gives none. request gets the path as the specification
    /// writes it, such as /loans/{loanId}/return; the harness fills its
    /// parameters from the input record.
    protocol Harness {
        func signIn(role: String) async throws
        func insert(_ mapping: String, _ record: Record) async throws
        func records(_ mapping: String) async throws -> [Record]
        func request(_ mapping: String, method: String, path: String, input: Record) async throws -> Response
        func run(_ mapping: String, command: String, arguments: [String: [Value]], options: Record) async throws -> CommandResult
        func open(_ mapping: String, page: String, route: String, input: Record) async throws -> Response
        func emitted() async throws -> [String]
        func compute(_ mapping: String, input: Record) async throws -> Value
    }

    /// Whether a value got is the value wanted, in its type: decimals and
    /// numbers by value, an object when it holds every part wanted, a list
    /// item by item, everything else by text.
    static func same(_ a: Value, _ b: Value) -> Bool {
        switch a.kind {
        case "decimal", "int", "uint", "double":
            guard let x = number(a.text), let y = number(b.text) else {
                return false
            }
            return x == y
        case "object":
            return b.kind == "object" && holds(a.parts, b.parts)
        case "list":
            return b.kind == "list" && a.items.count == b.items.count && zip(a.items, b.items).allSatisfy { same($0, $1) }
        default:
            return a.kind == b.kind && a.text == b.text
        }
    }

    /// A number's text in one form, digits and a power of ten with no
    /// zero at either end of the digits, so that numbers compare exactly
    /// whatever their length; nil when the whole text is not a number.
    static func number(_ s: String) -> String? {
        guard s.range(of: #"^[+-]?([0-9]+\.?[0-9]*|\.[0-9]+)([eE][+-]?[0-9]+)?$"#, options: .regularExpression) != nil else {
            return nil
        }
        var t = Substring(s)
        var negative = false
        if let sign = t.first, sign == "+" || sign == "-" {
            negative = sign == "-"
            t = t.dropFirst()
        }
        var exponent = 0
        if let e = t.firstIndex(where: { $0 == "e" || $0 == "E" }) {
            guard let n = Int(t[t.index(after: e)...]) else {
                return nil
            }
            exponent = n
            t = t[..<e]
        }
        let parts = t.split(separator: ".", omittingEmptySubsequences: false)
        let fraction = parts.count > 1 ? parts[1] : ""
        var digits = Array(parts[0] + fraction)
        exponent -= fraction.count
        while digits.first == "0" {
            digits.removeFirst()
        }
        if digits.isEmpty {
            return "0"
        }
        while digits.last == "0" {
            digits.removeLast()
            exponent += 1
        }
        return (negative ? "-" : "") + String(digits) + "e" + String(exponent)
    }

    /// Whether a record has every value of want.
    static func holds(_ r: Record, _ want: Record) -> Bool {
        want.allSatisfy { k, v in r[k].map { same($0, v) } ?? false }
    }

    static func expectStatus(_ r: Response, _ status: Int, sourceLocation: SourceLocation = #_sourceLocation) {
        if r.status != status {
            Issue.record("status \(r.status), want \(status)", sourceLocation: sourceLocation)
        }
    }

    static func expectBody(_ r: Response, _ want: Record, sourceLocation: SourceLocation = #_sourceLocation) {
        if !holds(r.body, want) {
            Issue.record("body \(r.body) does not hold \(want)", sourceLocation: sourceLocation)
        }
    }

    static func expectExit(_ r: CommandResult, _ exit: Int, sourceLocation: SourceLocation = #_sourceLocation) {
        if r.exit != exit {
            Issue.record("exit \(r.exit), want \(exit)", sourceLocation: sourceLocation)
        }
    }

    static func expectOutput(_ r: CommandResult, _ lines: [String], sourceLocation: SourceLocation = #_sourceLocation) {
        if r.output != lines {
            Issue.record("output \(r.output), want \(lines)", sourceLocation: sourceLocation)
        }
    }

    static func expectState(_ h: any Harness, _ mapping: String, _ want: Record, sourceLocation: SourceLocation = #_sourceLocation) async throws {
        if try await !h.records(mapping).contains(where: { holds($0, want) }) {
            Issue.record("no record of \(mapping) holds \(want)", sourceLocation: sourceLocation)
        }
    }

    static func expectEmitted(_ h: any Harness, _ messages: [String], sourceLocation: SourceLocation = #_sourceLocation) async throws {
        let got = try await h.emitted()
        for m in messages where !got.contains(m) {
            Issue.record("\(m) was not published; published: \(got)", sourceLocation: sourceLocation)
        }
        if messages.isEmpty && !got.isEmpty {
            Issue.record("nothing should be published; published: \(got)", sourceLocation: sourceLocation)
        }
    }

    static func expectValue(_ got: Value, _ want: Value, example: String, sourceLocation: SourceLocation = #_sourceLocation) {
        if !same(got, want) {
            Issue.record("\(example): got \(got), want \(want)", sourceLocation: sourceLocation)
        }
    }
}`
