// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import assert from "node:assert/strict";
import { test } from "node:test";
import { decide } from "../screens/access.ts";
import { schema } from "../app/fee-waivers/page.schema.ts";

test("fee-waivers-inbox is refused to someone signed in without fees.approve", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: [] }), "refused");
});

test("fee-waivers-inbox sends someone signed out to sign in", () => {
  assert.equal(decide(schema.permission, { signedIn: false, permissions: [] }), "sign-in");
});

test("fee-waivers-inbox opens to someone who holds fees.approve", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: ["fees.approve"] }), "allowed");
});
