// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/0.1.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: generator: the picker of bookId reads listBooks, which searches no field, so it offers the first 100 records and finds among them only [generator@design/pages/loan-form.yaml#/pages/loan-form/pickers/bookId/source]
import assert from "node:assert/strict";
import { test } from "node:test";
import { decide } from "../screens/access.ts";
import { schema } from "../app/loans/new/page.schema.ts";

test("loan-form is refused to someone signed in without loans.create", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: [] }), "refused");
});

test("loan-form sends someone signed out to sign in", () => {
  assert.equal(decide(schema.permission, { signedIn: false, permissions: [] }), "sign-in");
});

test("loan-form opens to someone who holds loans.create", () => {
  assert.equal(decide(schema.permission, { signedIn: true, permissions: ["loans.create"] }), "allowed");
});
