package generate

import (
	"fmt"
	"strings"

	"go.yaml.in/yaml/v3"
)

// CompanionName is the hand-written explanation beside a specification's
// root file, whose marked regions the techspec target rewrites.
const CompanionName = "specarch.md"

// Implementation is one implementation file of the specification, parsed.
// Rel is its path as seen from the output folder; Path as given.
type Implementation struct {
	Node *yaml.Node
	Rel  string
	Path string
}

// Techspec writes the technical specification of one specification: its
// merged document and its implementation files. relRoot is the root file's
// path as seen from the output folder; it goes into the header.
func Techspec(root *yaml.Node, relRoot string, impls []Implementation) string {
	d := newDoc("techspec", root, relRoot, impls)
	info := get(root, "info")
	d.line("# %s: technical specification", str(info, "title"))
	d.blank()
	d.para(fmt.Sprintf("Version %s of the specification: %s. The chapters follow arc42, and a chapter with nothing in the specification is left out.", str(info, "version"), contents(root)))
	d.draftNotice("techspec")

	introduction(d, root)
	constraints(d, root)
	context(d, root)
	buildingBlocks(d, root)
	runtime(d, root)
	deployment(d, root, impls)
	crossCutting(d, root)
	decisions(d, "9. Architecture decisions", root)
	qualityTests(d, root)
	glossary(d, root)
	requirements(d, root, impls)
	d.sourcesIndex("Sources")
	return d.String()
}

// doc is one document being written. sources is the specification's
// registry of sources; cited collects the ones its Notes name.
type doc struct {
	strings.Builder
	sources   *yaml.Node
	decisions *yaml.Node
	cited     map[string]bool
	sections  int                   // the sections numbered so far, for documents numbered as they go
	questions []question            // the open questions, for Open paragraphs and draft notices
	pointerOf map[*yaml.Node]string // every mapping's pointer, to find the questions about it
}

// section starts the next numbered section of a document whose sections
// are numbered in the order they appear, so a section left out leaves no
// gap.
func (d *doc) section(title string) {
	d.sections++
	d.heading(2, fmt.Sprintf("%d. %s", d.sections, title))
}

// newDoc starts a document of a target with its generated-from header: the
// root file and each implementation file, with their versions, and the
// meta-model.
func newDoc(target string, root *yaml.Node, relRoot string, impls []Implementation) *doc {
	d := &doc{sources: get(root, "sources"), decisions: get(root, "decisions"), questions: questionsOf(root), pointerOf: pointers(root)}
	from := fmt.Sprintf("%s, version %s", relRoot, str(get(root, "info"), "version"))
	for _, i := range impls {
		from += fmt.Sprintf(", and %s, version %s", i.Rel, str(get(i.Node, "info"), "version"))
	}
	d.line("<!-- Generated by specarch document %s from %s; meta-model %s. Do not edit this file: change the YAML and generate again. -->", target, from, str(root, "specarch"))
	d.blank()
	return d
}

func (d *doc) line(format string, args ...any) { fmt.Fprintf(d, format+"\n", args...) }
func (d *doc) blank()                          { d.WriteString("\n") }
func (d *doc) para(s string) {
	if s = strings.TrimSpace(s); s != "" {
		d.WriteString(s + "\n\n")
	}
}
func (d *doc) heading(level int, s string) {
	d.line("%s %s", strings.Repeat("#", level), s)
	d.blank()
}
func (d *doc) block(s string) {
	if s != "" {
		d.WriteString(s)
		d.blank()
	}
}

// contents counts what the design holds, for the summary line.
func contents(root *yaml.Node) string {
	var parts []string
	count := func(n int, one, many string) {
		switch {
		case n == 1:
			parts = append(parts, "1 "+one)
		case n > 1:
			parts = append(parts, fmt.Sprintf("%d %s", n, many))
		}
	}
	count(len(pairs(root, "requirements")), "requirement", "requirements")
	count(len(pairs(root, "entities")), "entity", "entities")
	count(len(operations(root)), "HTTP operation", "HTTP operations")
	count(len(pairs(root, "commands")), "command", "commands")
	count(len(pairs(root, "channels")), "channel", "channels")
	count(len(pairs(root, "pages")), "page", "pages")
	count(len(pairs(root, "algorithms")), "algorithm", "algorithms")
	count(len(pairs(root, "tests")), "test", "tests")
	count(len(pairs(root, "decisions")), "decision", "decisions")
	count(len(pairs(root, "environments")), "environment", "environments")
	count(len(pairs(root, "checks")), "commissioning check", "commissioning checks")
	if len(parts) == 0 {
		return "no objects yet"
	}
	if len(parts) == 1 {
		return parts[0]
	}
	return strings.Join(parts[:len(parts)-1], ", ") + " and " + parts[len(parts)-1]
}

func introduction(d *doc, root *yaml.Node) {
	info := get(root, "info")
	d.heading(2, "1. Introduction and goals")
	d.para(str(info, "description"))
	if owners := strs(info, "owners"); len(owners) > 0 {
		d.para("Owners: " + strings.Join(owners, ", ") + ".")
	}
	if sh := pairs(root, "stakeholders"); len(sh) > 0 {
		d.heading(3, "Stakeholders")
		d.line("| Stakeholder | Who they are | Concerns |")
		d.line("|---|---|---|")
		for _, s := range sh {
			d.line("| %s | %s | %s |", s.Key.Value, cell(str(s.Value, "description")), cell(joinSentences(strs(s.Value, "concerns"))))
		}
		d.blank()
		d.explainRows(pairRows(root, "stakeholders"))
	}
}

// constraints is chapter 2: the constraints and assumptions of the
// requirements stage.
func constraints(d *doc, root *yaml.Node) {
	cons := pairs(root, "constraints")
	assume := pairs(root, "assumptions")
	if len(cons)+len(assume) == 0 {
		return
	}
	d.heading(2, "2. Constraints")
	if len(cons) > 0 {
		d.line("| Constraint | Kind | Statement |")
		d.line("|---|---|---|")
		for _, c := range cons {
			d.line("| %s | %s | %s |", c.Key.Value, str(c.Value, "kind"), cell(str(c.Value, "statement")))
		}
		d.blank()
		d.explainRows(pairRows(root, "constraints"))
	}
	if len(assume) > 0 {
		d.heading(3, "Assumptions")
		d.line("| Assumption | Statement |")
		d.line("|---|---|")
		for _, a := range assume {
			d.line("| %s | %s |", a.Key.Value, cell(str(a.Value, "statement")))
		}
		d.blank()
		d.explainRows(pairRows(root, "assumptions"))
	}
}

func context(d *doc, root *yaml.Node) {
	ops := operations(root)
	cmds := pairs(root, "commands")
	chans := pairs(root, "channels")
	if len(ops)+len(cmds)+len(chans) == 0 {
		return
	}
	d.heading(2, "3. Context")
	d.para("The interfaces the system offers, as its clients see them.")
	if len(ops) > 0 {
		d.heading(3, "HTTP operations")
		d.line("| Method and path | Operation | Summary | Permission |")
		d.line("|---|---|---|---|")
		for _, o := range ops {
			d.line("| %s %s | %s | %s | %s |", strings.ToUpper(o.method), cell(o.path), o.id, cell(str(o.node, "summary")), str(o.node, "permission"))
		}
		d.blank()
	}
	if len(cmds) > 0 {
		d.heading(3, "Commands")
		d.line("| Command | Summary | Permission | Exit statuses |")
		d.line("|---|---|---|---|")
		for _, c := range cmds {
			var codes []string
			for _, e := range pairs(c.Value, "exitCodes") {
				codes = append(codes, e.Key.Value+": "+e.Value.Value)
			}
			d.line("| %s | %s | %s | %s |", c.Key.Value, cell(str(c.Value, "summary")), str(c.Value, "permission"), cell(strings.Join(codes, "; ")))
		}
		d.blank()
	}
	if len(chans) > 0 {
		d.heading(3, "Channels")
		d.line("| Channel | Message | Summary |")
		d.line("|---|---|---|")
		var rows []row
		for _, ch := range chans {
			rows = append(rows, row{ch.Key.Value, ch.Value})
			for _, m := range pairs(ch.Value, "messages") {
				d.line("| %s | %s | %s |", ch.Key.Value, m.Key.Value, cell(str(m.Value, "summary")))
				rows = append(rows, row{ch.Key.Value + "/" + m.Key.Value, m.Value})
			}
		}
		d.blank()
		d.explainRows(rows)
	}
}

func buildingBlocks(d *doc, root *yaml.Node) {
	entities := pairs(root, "entities")
	enums := pairs(root, "enums")
	if len(entities)+len(enums) == 0 {
		return
	}
	d.heading(2, "5. Building blocks")
	d.block(entityDiagram(root))
	for _, e := range entities {
		d.heading(3, e.Key.Value)
		d.para(str(e.Value, "description"))
		d.explain(e.Value)
		required := map[string]bool{}
		for _, r := range strs(e.Value, "required") {
			required[r] = true
		}
		d.line("| Field | Type | Required | Limits | Description |")
		d.line("|---|---|---|---|---|")
		for _, f := range pairs(e.Value, "properties") {
			req := ""
			if required[f.Key.Value] {
				req = "yes"
			}
			d.line("| %s | %s | %s | %s | %s |", f.Key.Value, cell(typeText(f.Value)), cell(req), cell(limits(f.Value)), cell(str(f.Value, "description")))
		}
		d.blank()
		d.para("Primary key: " + strings.Join(strs(e.Value, "primaryKey"), ", ") + ".")
		if rels := pairs(e.Value, "relations"); len(rels) > 0 {
			d.line("| Relation | Kind | Target | Via | On delete |")
			d.line("|---|---|---|---|---|")
			for _, r := range rels {
				onDelete := str(r.Value, "onDelete")
				if onDelete == "" {
					onDelete = "restrict"
				}
				d.line("| %s | %s | %s | %s | %s |", r.Key.Value, str(r.Value, "kind"), str(r.Value, "target"), str(r.Value, "via"), onDelete)
			}
			d.blank()
			d.explainRows(pairRows(e.Value, "relations"))
		}
		if cons := pairs(e.Value, "constraints"); len(cons) > 0 {
			d.line("| Constraint | Rule | Message |")
			d.line("|---|---|---|")
			for _, c := range cons {
				rule := "check `" + str(c.Value, "expression") + "`"
				if str(c.Value, "kind") == "unique" {
					rule = "unique: " + strings.Join(strs(c.Value, "fields"), ", ")
				}
				d.line("| %s | %s | %s |", c.Key.Value, cell(rule), cell(str(c.Value, "message")))
			}
			d.blank()
			d.explainRows(pairRows(e.Value, "constraints"))
		}
	}
	if len(enums) > 0 {
		d.heading(3, "Enums")
		d.line("| Enum | Value | Meaning |")
		d.line("|---|---|---|")
		for _, e := range enums {
			descs := get(e.Value, "valueDescriptions")
			for _, v := range strs(e.Value, "enum") {
				d.line("| %s | %s | %s |", e.Key.Value, v, cell(str(descs, v)))
			}
		}
		d.blank()
		d.explainRows(pairRows(root, "enums"))
	}
}

func runtime(d *doc, root *yaml.Node) {
	var states []string
	for _, e := range pairs(root, "entities") {
		if str(e.Value, "stateField") != "" && len(items(e.Value, "transitions")) > 0 {
			states = append(states, e.Key.Value)
		}
	}
	ops := operations(root)
	cmds := pairs(root, "commands")
	if len(states)+len(ops)+len(cmds) == 0 {
		return
	}
	d.heading(2, "6. Runtime view")
	for _, e := range states {
		d.heading(3, "States of "+e)
		diagram, _ := stateDiagram(root, e)
		d.block(diagram)
		var rows []row
		for _, t := range items(get(get(root, "entities"), e), "transitions") {
			rows = append(rows, row{fmt.Sprintf("%s to %s", str(t, "from"), str(t, "to")), t})
		}
		d.explainRows(rows)
	}
	for _, o := range ops {
		d.heading(3, fmt.Sprintf("%s (%s %s)", o.id, strings.ToUpper(o.method), o.path))
		d.para(str(o.node, "description"))
		d.explain(o.node)
		d.block(operationSequence(root, o))
	}
	for _, c := range cmds {
		d.heading(3, "Command "+c.Key.Value)
		d.para(str(c.Value, "description"))
		d.explain(c.Value)
		commandDetails(d, c.Value)
		d.block(commandSequence(root, c.Key.Value, c.Value))
	}
}

func commandDetails(d *doc, c *yaml.Node) {
	args := items(c, "arguments")
	opts := pairs(c, "options")
	if len(args)+len(opts) > 0 {
		d.line("| Argument or option | Type | Required | Description |")
		d.line("|---|---|---|---|")
		for _, a := range args {
			t := typeText(get(a, "schema"))
			if str(a, "repeatable") == "true" {
				t += ", one or more"
			}
			req := ""
			if str(a, "required") == "true" {
				req = "yes"
			}
			d.line("| `<%s>` | %s | %s | %s |", str(a, "name"), cell(t), cell(req), cell(str(a, "description")))
		}
		for _, o := range opts {
			req := ""
			if str(o.Value, "required") == "true" {
				req = "yes"
			}
			d.line("| `--%s` | %s | %s | %s |", o.Key.Value, cell(typeText(get(o.Value, "schema"))), cell(req), cell(str(o.Value, "description")))
		}
		d.blank()
	}
	for _, f := range [][2]string{{"reads", "Reads"}, {"writes", "Writes"}} {
		if list := items(c, f[0]); len(list) > 0 {
			var parts []string
			for _, u := range list {
				parts = append(parts, "`"+str(u, "path")+"`: "+strings.TrimSuffix(strings.TrimSpace(str(u, "description")), "."))
			}
			d.para(f[1] + " " + strings.Join(parts, "; ") + ".")
		}
	}
	for _, f := range [][2]string{{"standardOutput", "Standard output"}, {"standardError", "Standard error"}} {
		if s := str(c, f[0]); s != "" {
			d.para(f[1] + ": " + s)
		}
	}
}

func crossCutting(d *doc, root *yaml.Node) {
	perms := permissionsTable(root)
	pages := pairs(root, "pages")
	algs := pairs(root, "algorithms")
	if perms == "" && len(pages)+len(algs) == 0 {
		return
	}
	d.heading(2, "8. Cross-cutting concepts")
	if perms != "" {
		d.heading(3, "Permissions")
		d.para("Access is fail-closed: every operation, command and page names the one permission it needs, and only the roles below grant one.")
		d.block(perms)
		d.explainRows(append(pairRows(root, "permissions"), pairRows(root, "roles")...))
	}
	if len(pages) > 0 {
		d.heading(3, "Pages")
		d.block(pagesFlowchart(root))
		d.line("| Page | Kind | Route | Entity | Permission | Shows |")
		d.line("|---|---|---|---|---|---|")
		for _, p := range pages {
			shows := strs(p.Value, "columns")
			if len(shows) == 0 {
				shows = strs(p.Value, "fields")
			}
			d.line("| %s | %s | %s | %s | %s | %s |", p.Key.Value, str(p.Value, "kind"), cell(str(p.Value, "route")), str(p.Value, "entity"), str(p.Value, "permission"), cell(strings.Join(shows, ", ")))
		}
		d.blank()
		d.explainRows(rowsOf(pages))
	}
	for _, a := range algs {
		d.heading(3, "Algorithm "+a.Key.Value)
		d.para(str(a.Value, "description"))
		d.explain(a.Value)
		var inputs []string
		for _, in := range pairs(a.Value, "inputs") {
			inputs = append(inputs, fmt.Sprintf("`%s` (%s)", in.Key.Value, typeText(in.Value)))
		}
		d.para("Inputs: " + strings.Join(inputs, ", ") + ". Output: " + typeText(get(a.Value, "output")) + ".")
		d.line("Formula:")
		d.blank()
		d.line("    %s", strings.TrimSpace(str(a.Value, "formula")))
		d.blank()
		d.line("| Worked example | Inputs | Expected | Note |")
		d.line("|---|---|---|---|")
		for _, ex := range items(a.Value, "examples") {
			var in []string
			for _, p := range pairs(ex, "inputs") {
				in = append(in, p.Key.Value+" "+p.Value.Value)
			}
			d.line("| %s | %s | %s | %s |", cell(str(ex, "name")), cell(strings.Join(in, ", ")), cell(str(ex, "expected")), cell(str(ex, "note")))
		}
		d.blank()
		d.line("Pseudocode:")
		d.blank()
		d.line("```text")
		d.WriteString(strings.TrimRight(str(a.Value, "pseudocode"), "\n") + "\n")
		d.line("```")
		d.blank()
	}
}

// decisions writes the decision records; with no title they are a part of
// the implementation chapter.
func decisions(d *doc, title string, root *yaml.Node) {
	decs := pairs(root, "decisions")
	if len(decs) == 0 {
		return
	}
	level := 3
	if title == "" {
		d.heading(4, "Implementation decisions")
		level = 5
	} else {
		d.heading(2, title)
	}
	for _, p := range decs {
		dec := p.Value
		d.heading(level, fmt.Sprintf("%s: %s", p.Key.Value, str(dec, "title")))
		status := str(dec, "status") + ", " + str(dec, "date")
		if s := str(dec, "supersededBy"); s != "" {
			status += ", superseded by " + s
		}
		d.para("Status: " + status + ".")
		for _, part := range [][2]string{{"context", "Context"}, {"decision", "Decision"}, {"consequences", "Consequences"}} {
			if v := strings.TrimSpace(str(dec, part[0])); v != "" {
				d.para(part[1] + ": " + v)
			}
		}
		d.explain(dec)
	}
}

func qualityTests(d *doc, root *yaml.Node) {
	tests := pairs(root, "tests")
	if len(tests) == 0 {
		return
	}
	d.heading(2, "10. Quality requirements")
	d.para("The design tests: what must hold on every implementation. Golden scenarios succeed; red scenarios are refused.")
	d.line("| Test | Subject | Level | Scenario | Given | When | Then |")
	d.line("|---|---|---|---|---|---|---|")
	for _, t := range tests {
		subject := testSubject(t.Value)
		if na := str(t.Value, "notApplicable"); na != "" {
			d.line("| %s | %s | %s | %s | %s | %s | %s |", t.Key.Value, cell(subject), str(t.Value, "level"), str(t.Value, "scenario"), "not applicable", " ", cell(na))
			continue
		}
		d.line("| %s | %s | %s | %s | %s | %s | %s |", t.Key.Value, cell(subject), str(t.Value, "level"), str(t.Value, "scenario"), cell(str(t.Value, "given")), cell(str(t.Value, "when")), cell(str(t.Value, "then")))
	}
	d.blank()
	d.explainRows(rowsOf(tests))
}

func testSubject(t *yaml.Node) string {
	for _, k := range []string{"operation", "command", "page"} {
		if v := str(t, k); v != "" {
			return k + " " + v
		}
	}
	if c := str(t, "constraint"); c != "" {
		return str(t, "entity") + " constraint " + c
	}
	if tr := get(t, "transition"); tr != nil {
		return fmt.Sprintf("%s %s to %s", str(t, "entity"), str(tr, "from"), str(tr, "to"))
	}
	if r := str(t, "requirement"); r != "" {
		return "requirement " + r
	}
	if e := str(t, "entity"); e != "" {
		return e + " state machine"
	}
	return ""
}

// glossary is chapter 12.
func glossary(d *doc, root *yaml.Node) {
	terms := pairs(root, "glossary")
	if len(terms) == 0 {
		return
	}
	d.heading(2, "12. Glossary")
	d.line("| Term | Meaning |")
	d.line("|---|---|")
	for _, t := range terms {
		d.line("| %s | %s |", cell(t.Key.Value), cell(str(t.Value, "definition")))
	}
	d.blank()
	d.explainRows(rowsOf(terms))
}

// requirements is chapter 13: the needs, the requirements with their
// attributes, and the traceability matrix: what satisfies and what
// verifies each requirement.
func requirements(d *doc, root *yaml.Node, impls []Implementation) {
	reqs := pairs(root, "requirements")
	needs := pairs(root, "needs")
	satisfied, verified := traceLinks(root, impls)
	external := map[string]bool{}
	for _, s := range pairs(root, "sources") {
		if str(s.Value, "kind") == "requirement-set" {
			external[str(s.Value, "prefix")] = true
		}
	}
	if len(reqs)+len(needs)+len(satisfied)+len(verified) == 0 {
		return
	}
	d.heading(2, "13. Requirements")
	if len(needs) > 0 {
		d.heading(3, "Needs")
		d.line("| Need | Statement | Stakeholders | Status |")
		d.line("|---|---|---|---|")
		for _, n := range needs {
			d.line("| %s | %s | %s | %s |", n.Key.Value, cell(str(n.Value, "statement")), cell(strings.Join(strs(n.Value, "stakeholders"), ", ")), cell(str(n.Value, "status")))
		}
		d.blank()
		d.explainRows(rowsOf(needs))
	}
	if len(reqs) > 0 {
		d.heading(3, "Requirements")
		d.line("| Requirement | Statement | Kind | Priority | Status | Verification | Acceptance | Needs |")
		d.line("|---|---|---|---|---|---|---|---|")
		for _, r := range reqs {
			d.line("| %s | %s | %s | %s | %s | %s | %s | %s |", r.Key.Value, cell(str(r.Value, "statement")), str(r.Value, "kind"), str(r.Value, "priority"), str(r.Value, "status"), cell(str(r.Value, "verification")), cell(strings.Join(strs(r.Value, "acceptance"), " ")), cell(strings.Join(strs(r.Value, "needs"), ", ")))
		}
		d.blank()
		d.explainRows(rowsOf(reqs))
	}
	for _, s := range pairs(root, "sources") {
		if str(s.Value, "kind") == "requirement-set" {
			d.para(fmt.Sprintf("%s: requirements with the prefix %s are in %s.", s.Key.Value, str(s.Value, "prefix"), strings.TrimSpace(str(s.Value, "title"))))
		}
	}
	d.heading(3, "Traceability")
	d.para("What satisfies and what verifies each requirement. An empty cell is a gap.")
	harm := harmColumn(reqs)
	d.line("| Requirement |%s Satisfied by | Verified by |", harm.header)
	d.line("|---|%s---|---|", harm.rule)
	ids := map[string]bool{}
	for _, r := range reqs {
		ids[r.Key.Value] = true
	}
	for k := range satisfied {
		ids[k] = true
	}
	for k := range verified {
		ids[k] = true
	}
	for _, k := range sortedLinks(ids) {
		d.line("| %s |%s %s | %s |", k, harm.cell(k), cell(strings.Join(unique(satisfied[k]), "; ")), cell(strings.Join(unique(verified[k]), "; ")))
	}
	d.blank()
}

// childLabel builds a reader's name for a nested object: "entities Loan".
func childLabel(parent, key string) string {
	if parent == "" {
		return key
	}
	return parent + " " + key
}

func unique(s []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, v := range s {
		if !seen[v] {
			seen[v] = true
			out = append(out, v)
		}
	}
	return out
}

// traceLinks finds, for every requirement ID, the elements that satisfy it
// and the ones that verify it, each named the way a reader finds it:
// "entities Loan", "tests loan-late".
func traceLinks(root *yaml.Node, impls []Implementation) (satisfied, verified map[string][]string) {
	satisfied = map[string][]string{}
	verified = map[string][]string{}
	var walk func(n *yaml.Node, label string)
	walk = func(n *yaml.Node, label string) {
		for _, p := range pairsOf(n) {
			switch p.Key.Value {
			case "satisfies":
				for _, r := range itemsOf(p.Value) {
					satisfied[r.Value] = append(satisfied[r.Value], label)
				}
				continue
			case "verifies":
				for _, r := range itemsOf(p.Value) {
					verified[r.Value] = append(verified[r.Value], label)
				}
				continue
			}
			walk(p.Value, childLabel(label, p.Key.Value))
		}
		for i, it := range itemsOf(n) {
			walk(it, fmt.Sprintf("%s %d", label, i+1))
		}
	}
	walk(root, "")
	for _, i := range impls {
		walk(i.Node, "implementation "+str(get(i.Node, "info"), "title"))
	}
	return satisfied, verified
}
