package generate

import (
	"fmt"
	"math"
	"strconv"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/SpecArch/specarch/internal/source"
	"github.com/SpecArch/specarch/internal/validate"
)

// CompanionName is the hand-written explanation beside a specification's
// root file, whose marked regions the techspec target rewrites.
const CompanionName = "specarch.md"

// Implementation is one implementation file of the specification, parsed.
// Rel is its path as seen from the output folder; Path as given.
type Implementation struct {
	Node   *yaml.Node
	Rel    string
	Path   string
	Idioms []IdiomUse // the idioms the file uses, as the validator resolves them
}

// IdiomUse is one idiom as an implementation file uses it: shipped,
// overridden (with the parts the project replaces and the version it
// copied), the project's own, or excluded, with the reason.
type IdiomUse struct {
	Name, Version, As, From, Why string
	Parts                        []string
}

// Techspec writes the technical specification of one specification: its
// merged document and its implementation files. relRoot is the root file's
// path as seen from the output folder; it goes into the header.
func Techspec(root *yaml.Node, relRoot string, impls []Implementation) string {
	d := newDoc("techspec", root, relRoot, impls)
	info := get(root, "info")
	d.line("# %s: technical specification", str(info, "title"))
	d.blank()
	d.para(fmt.Sprintf("Version %s of the specification: %s. The chapters follow arc42, and a chapter with nothing in the specification is left out.", str(info, "version"), contents(root)))
	d.draftNotice("techspec")

	introduction(d, root)
	constraints(d, root)
	context(d, root)
	buildingBlocks(d, root)
	runtime(d, root)
	deployment(d, root, impls)
	crossCutting(d, root)
	decisions(d, "9. Architecture decisions", root)
	qualityTests(d, root)
	glossary(d, root)
	requirements(d, root, impls)
	d.sourcesIndex("Sources")
	return d.String()
}

// doc is one document being written. sources is the specification's
// registry of sources; cited collects the ones its Notes name.
type doc struct {
	strings.Builder
	sources   *yaml.Node
	decisions *yaml.Node
	cited     map[string]bool
	sections  int                   // the sections numbered so far, for documents numbered as they go
	questions []question            // the open questions, for Open paragraphs and draft notices
	pointerOf map[*yaml.Node]string // every mapping's pointer, to find the questions about it
}

// section starts the next numbered section of a document whose sections
// are numbered in the order they appear, so a section left out leaves no
// gap.
func (d *doc) section(title string) {
	d.sections++
	d.heading(2, fmt.Sprintf("%d. %s", d.sections, title))
}

// newDoc starts a document of a target with its generated-from header: the
// root file and each implementation file, with their versions, and the
// meta-model.
func newDoc(target string, root *yaml.Node, relRoot string, impls []Implementation) *doc {
	d := &doc{sources: get(root, "sources"), decisions: get(root, "decisions"), questions: questionsOf(root), pointerOf: pointers(root)}
	from := fmt.Sprintf("%s, version %s", relRoot, str(get(root, "info"), "version"))
	for _, i := range impls {
		from += fmt.Sprintf(", and %s, version %s", i.Rel, str(get(i.Node, "info"), "version"))
	}
	d.line("<!-- Generated by specarch document %s from %s; meta-model %s. Do not edit this file: change the YAML and generate again. -->", target, from, str(root, "specarch"))
	d.blank()
	return d
}

func (d *doc) line(format string, args ...any) { fmt.Fprintf(d, format+"\n", args...) }
func (d *doc) blank()                          { d.WriteString("\n") }
func (d *doc) para(s string) {
	if s = strings.TrimSpace(s); s != "" {
		d.WriteString(s + "\n\n")
	}
}
func (d *doc) heading(level int, s string) {
	d.line("%s %s", strings.Repeat("#", level), s)
	d.blank()
}
func (d *doc) block(s string) {
	if s != "" {
		d.WriteString(s)
		d.blank()
	}
}

// contents counts what the design holds, for the summary line.
func contents(root *yaml.Node) string {
	var parts []string
	count := func(n int, one, many string) {
		switch {
		case n == 1:
			parts = append(parts, "1 "+one)
		case n > 1:
			parts = append(parts, fmt.Sprintf("%d %s", n, many))
		}
	}
	count(len(pairs(root, "requirements")), "requirement", "requirements")
	count(len(pairs(root, "entities")), "entity", "entities")
	count(len(pairs(root, "views")), "view", "views")
	count(len(operations(root)), "HTTP operation", "HTTP operations")
	count(len(pairs(root, "commands")), "command", "commands")
	count(len(pairs(root, "channels")), "channel", "channels")
	count(len(pairs(root, "dependencies")), "dependency", "dependencies")
	count(len(pairs(root, "pages")), "page", "pages")
	count(len(pairs(root, "flows")), "flow", "flows")
	count(len(pairs(root, "algorithms")), "algorithm", "algorithms")
	count(len(pairs(root, "tests")), "test", "tests")
	count(len(pairs(root, "decisions")), "decision", "decisions")
	count(len(pairs(root, "environments")), "environment", "environments")
	count(len(pairs(root, "checks")), "commissioning check", "commissioning checks")
	if len(parts) == 0 {
		return "no objects yet"
	}
	if len(parts) == 1 {
		return parts[0]
	}
	return strings.Join(parts[:len(parts)-1], ", ") + " and " + parts[len(parts)-1]
}

func introduction(d *doc, root *yaml.Node) {
	info := get(root, "info")
	d.heading(2, "1. Introduction and goals")
	d.para(str(info, "description"))
	if owners := strs(info, "owners"); len(owners) > 0 {
		d.para("Owners: " + strings.Join(owners, ", ") + ".")
	}
	if sh := pairs(root, "stakeholders"); len(sh) > 0 {
		d.heading(3, "Stakeholders")
		d.line("| Stakeholder | Who they are | Concerns |")
		d.line("|---|---|---|")
		for _, s := range sh {
			d.line("| %s | %s | %s |", s.Key.Value, cell(str(s.Value, "description")), cell(joinSentences(strs(s.Value, "concerns"))))
		}
		d.blank()
		d.explainRows(pairRows(root, "stakeholders"))
	}
}

// constraints is chapter 2: the constraints and assumptions of the
// requirements stage.
func constraints(d *doc, root *yaml.Node) {
	cons := pairs(root, "constraints")
	assume := pairs(root, "assumptions")
	if len(cons)+len(assume) == 0 {
		return
	}
	d.heading(2, "2. Constraints")
	if len(cons) > 0 {
		d.line("| Constraint | Kind | Statement |")
		d.line("|---|---|---|")
		for _, c := range cons {
			d.line("| %s | %s | %s |", c.Key.Value, str(c.Value, "kind"), cell(str(c.Value, "statement")))
		}
		d.blank()
		d.explainRows(pairRows(root, "constraints"))
	}
	if len(assume) > 0 {
		d.heading(3, "Assumptions")
		d.line("| Assumption | Statement |")
		d.line("|---|---|")
		for _, a := range assume {
			d.line("| %s | %s |", a.Key.Value, cell(str(a.Value, "statement")))
		}
		d.blank()
		d.explainRows(pairRows(root, "assumptions"))
	}
}

func context(d *doc, root *yaml.Node) {
	ops := operations(root)
	cmds := pairs(root, "commands")
	chans := pairs(root, "channels")
	deps := pairs(root, "dependencies")
	if len(ops)+len(cmds)+len(chans)+len(deps) == 0 {
		return
	}
	d.heading(2, "3. Context")
	d.para("The interfaces the system offers, as its clients see them.")
	if len(ops) > 0 {
		d.heading(3, "HTTP operations")
		d.line("| Method and path | Operation | Summary | Permission |")
		d.line("|---|---|---|---|")
		for _, o := range ops {
			d.line("| %s %s | %s | %s | %s |", strings.ToUpper(o.method), cell(o.path), o.id, cell(str(o.node, "summary")), str(o.node, "permission"))
		}
		d.blank()
	}
	if len(cmds) > 0 {
		d.heading(3, "Commands")
		d.line("| Command | Summary | Permission | Exit statuses |")
		d.line("|---|---|---|---|")
		for _, c := range cmds {
			var codes []string
			for _, e := range pairs(c.Value, "exitCodes") {
				codes = append(codes, e.Key.Value+": "+e.Value.Value)
			}
			d.line("| %s | %s | %s | %s |", c.Key.Value, cell(str(c.Value, "summary")), str(c.Value, "permission"), cell(strings.Join(codes, "; ")))
		}
		d.blank()
	}
	if len(chans) > 0 {
		d.heading(3, "Channels")
		d.line("| Channel | Message | Summary |")
		d.line("|---|---|---|")
		var rows []row
		for _, ch := range chans {
			rows = append(rows, row{ch.Key.Value, ch.Value})
			for _, m := range pairs(ch.Value, "messages") {
				d.line("| %s | %s | %s |", ch.Key.Value, m.Key.Value, cell(str(m.Value, "summary")))
				rows = append(rows, row{ch.Key.Value + "/" + m.Key.Value, m.Value})
			}
		}
		d.blank()
		d.explainRows(rows)
	}
	if len(deps) > 0 {
		d.heading(3, "Dependencies")
		d.para("External systems the operations call. A call that fails, or that does not answer within its time limit, is given up, and the operation answers as its failure response says.")
		d.line("| Dependency | Time limit per call | Called by | Description |")
		d.line("|---|---|---|---|")
		for _, dep := range deps {
			var callers []string
			for _, o := range ops {
				for _, c := range strs(o.node, "calls") {
					if c == dep.Key.Value {
						callers = append(callers, o.id)
					}
				}
			}
			d.line("| %s | %s | %s | %s |", dep.Key.Value, str(dep.Value, "timeout"), cell(strings.Join(callers, ", ")), cell(str(dep.Value, "description")))
		}
		d.blank()
		d.explainRows(rowsOf(deps))
	}
}

func buildingBlocks(d *doc, root *yaml.Node) {
	entities := pairs(root, "entities")
	enums := pairs(root, "enums")
	views := pairs(root, "views")
	if len(entities)+len(enums)+len(views) == 0 {
		return
	}
	d.heading(2, "5. Building blocks")
	d.block(entityDiagram(root))
	for _, e := range entities {
		d.heading(3, e.Key.Value)
		d.para(str(e.Value, "description"))
		d.explain(e.Value)
		required := map[string]bool{}
		for _, r := range strs(e.Value, "required") {
			required[r] = true
		}
		d.line("| Field | Type | Required | Limits | Description |")
		d.line("|---|---|---|---|---|")
		for _, f := range pairs(e.Value, "properties") {
			req := ""
			if required[f.Key.Value] {
				req = "yes"
			}
			d.line("| %s | %s | %s | %s | %s |", f.Key.Value, cell(typeText(f.Value)), cell(req), cell(limits(f.Value)), cell(str(f.Value, "description")))
		}
		d.blank()
		d.para("Primary key: " + strings.Join(strs(e.Value, "primaryKey"), ", ") + ".")
		if v := get(e.Value, "validity"); v != nil {
			if from := str(v, "from"); from != "" {
				d.para(fmt.Sprintf("Validity: a record is current from its %s until its %s; outside that it is refused where it is used.", from, str(v, "until")))
			} else {
				d.para(fmt.Sprintf("Validity: a record is current until its %s; after that it is refused where it is used.", str(v, "until")))
			}
		}
		if str(e.Value, "audited") == "true" {
			d.para("Audited: every record also carries createdAt, createdBy, lastModifiedAt and lastModifiedBy, set by the system and never by a caller (the audit-fields idiom).")
		}
		if str(e.Value, "deletion") == "soft" {
			d.para("Deletion is soft: a deleted record keeps a deleted flag set by the system, is not listed, and reads as not found (the soft-delete idiom).")
		}
		if rels := pairs(e.Value, "relations"); len(rels) > 0 {
			d.line("| Relation | Kind | Target | Via | On delete |")
			d.line("|---|---|---|---|---|")
			for _, r := range rels {
				onDelete := str(r.Value, "onDelete")
				if onDelete == "" {
					onDelete = "restrict"
				}
				d.line("| %s | %s | %s | %s | %s |", r.Key.Value, str(r.Value, "kind"), str(r.Value, "target"), str(r.Value, "via"), onDelete)
			}
			d.blank()
			d.explainRows(pairRows(e.Value, "relations"))
		}
		if cons := pairs(e.Value, "constraints"); len(cons) > 0 {
			d.line("| Constraint | Rule | Message |")
			d.line("|---|---|---|")
			for _, c := range cons {
				rule := "check `" + str(c.Value, "expression") + "`"
				if str(c.Value, "kind") == "unique" {
					rule = "unique: " + strings.Join(strs(c.Value, "fields"), ", ")
				}
				d.line("| %s | %s | %s |", c.Key.Value, cell(rule), cell(str(c.Value, "message")))
			}
			d.blank()
			d.explainRows(pairRows(e.Value, "constraints"))
		}
	}
	if len(views) > 0 {
		d.heading(3, "Views")
		d.para("A view is a read model: one row per record of the entity it reads from, with every field of that entity and the fields below. It is never written. A path is null when a relation on it has no record; a count leaves out softly deleted records.")
		for _, v := range views {
			from := str(v.Value, "from")
			d.heading(4, v.Key.Value)
			d.para(str(v.Value, "description"))
			d.explain(v.Value)
			d.line("| Field | Type | Read from | Description |")
			d.line("|---|---|---|---|")
			for _, p := range pairs(v.Value, "properties") {
				typ, source := "integer, 64-bit", "count of "+from+"."+str(p.Value, "count")
				if path := str(p.Value, "path"); path != "" {
					typ, source = "", from+"."+path
					if f, optional := viewPathField(root, from, path); f != nil {
						typ = typeText(f)
						if optional && !strings.HasSuffix(typ, " or null") {
							typ += " or null"
						}
					}
				}
				d.line("| %s | %s | %s | %s |", p.Key.Value, cell(typ), cell(source), cell(str(p.Value, "description")))
			}
			d.blank()
			d.para("Reads from: " + from + ".")
		}
	}
	if len(enums) > 0 {
		d.heading(3, "Enums")
		d.line("| Enum | Value | Meaning |")
		d.line("|---|---|---|")
		for _, e := range enums {
			descs := get(e.Value, "valueDescriptions")
			for _, v := range strs(e.Value, "enum") {
				d.line("| %s | %s | %s |", e.Key.Value, v, cell(str(descs, v)))
			}
		}
		d.blank()
		d.explainRows(pairRows(root, "enums"))
	}
}

func runtime(d *doc, root *yaml.Node) {
	var states []string
	for _, e := range pairs(root, "entities") {
		if str(e.Value, "stateField") != "" && len(items(e.Value, "transitions")) > 0 {
			states = append(states, e.Key.Value)
		}
	}
	ops := operations(root)
	cmds := pairs(root, "commands")
	jobs := pairs(root, "jobs")
	if len(states)+len(ops)+len(cmds)+len(jobs) == 0 {
		return
	}
	d.heading(2, "6. Runtime view")
	for _, e := range states {
		d.heading(3, "States of "+e)
		diagram, _ := stateDiagram(root, e)
		d.block(diagram)
		var rows []row
		for _, t := range items(get(get(root, "entities"), e), "transitions") {
			rows = append(rows, row{fmt.Sprintf("%s to %s", str(t, "from"), str(t, "to")), t})
		}
		d.explainRows(rows)
	}
	if errs := pairs(root, "errors"); len(errs) > 0 {
		d.heading(3, "Problem types")
		d.para("Every refusal is an RFC 9457 problem document of one of these types; each operation below names the ones it answers with.")
		d.line("| Problem type | Status | Title | When |")
		d.line("|---|---|---|---|")
		for _, e := range errs {
			d.line("| %s | %s | %s | %s |", e.Key.Value, str(e.Value, "status"), cell(str(e.Value, "title")), cell(str(e.Value, "condition")))
		}
		d.blank()
		d.explainRows(rowsOf(errs))
	}
	for _, o := range ops {
		d.heading(3, fmt.Sprintf("%s (%s %s)", o.id, strings.ToUpper(o.method), o.path))
		d.para(str(o.node, "description"))
		d.explain(o.node)
		operationDetails(d, root, o.node)
		d.block(operationSequence(root, o))
	}
	for _, j := range jobs {
		d.heading(3, "Job "+j.Key.Value)
		d.para(str(j.Value, "description"))
		d.explain(j.Value)
		jobDetails(d, root, j.Value)
	}
	for _, c := range cmds {
		d.heading(3, "Command "+c.Key.Value)
		d.para(str(c.Value, "description"))
		d.explain(c.Value)
		commandDetails(d, c.Value)
		guardText(d, c.Value)
		d.block(commandSequence(root, c.Key.Value, c.Value))
	}
}

// operationDetails writes what an operation calls, how a repeat is told
// from a new request, and its guard.
func operationDetails(d *doc, root *yaml.Node, op *yaml.Node) {
	if calls := strs(op, "calls"); len(calls) > 0 {
		var parts []string
		for _, c := range calls {
			parts = append(parts, fmt.Sprintf("%s (within %s)", c, str(get(get(root, "dependencies"), c), "timeout")))
		}
		d.para("Calls " + strings.Join(parts, ", ") + ".")
	}
	if l := get(op, "listOf"); l != nil {
		text := "Lists " + str(l, "entity") + " a page at a time"
		size := get(l, "pageSize")
		if def := str(size, "default"); def != "" {
			text += ", " + def + " records by default"
		}
		text += ", at most " + str(size, "maximum") + " a page."
		for _, k := range [][2]string{{"searchable", "A search matches"}, {"filterable", "A filter may name"}, {"sortable", "It may be sorted by"}} {
			if fs := strs(l, k[0]); len(fs) > 0 {
				text += " " + k[1] + " " + joinAnd(fs) + "."
			}
		}
		d.para(text + " A request outside these is refused, not ignored (the paginated-list idiom).")
	}
	var refusals []string
	for _, r := range pairs(op, "responses") {
		if p := str(r.Value, "problem"); p != "" {
			refusals = append(refusals, r.Key.Value+" "+p)
		}
	}
	if len(refusals) > 0 {
		d.para("Refuses with " + joinAnd(refusals) + ".")
	}
	if l := get(op, "limits"); l != nil {
		var parts []string
		if n := str(l, "maxRequestBytes"); n != "" {
			parts = append(parts, "a request body of at most "+n+" bytes")
		}
		if r := get(l, "rate"); r != nil {
			rate := str(r, "requests") + " requests per " + str(r, "per")
			if b := str(r, "burst"); b != "" {
				rate += ", with bursts of up to " + b
			}
			parts = append(parts, rate)
		}
		d.para("Limits: " + strings.Join(parts, "; ") + ".")
	}
	if key := str(op, "idempotencyKey"); key != "" {
		d.para(fmt.Sprintf("Idempotent by the %s header: a request repeated with the same key is answered as the first was and has no second effect; a different request with a key already used is refused.", key))
	}
	guardText(d, op)
}

// guardText writes a guard: what the change writes, what must hold, and
// how many records it touches.
func guardText(d *doc, n *yaml.Node) {
	g := get(n, "guard")
	if g == nil {
		return
	}
	text := fmt.Sprintf("Guard: the change writes %s %s %s", str(g, "recordsChanged"), str(g, "entity"), map[bool]string{true: "record", false: "records"}[str(g, "recordsChanged") == "1"])
	if pre := str(g, "precondition"); pre != "" {
		text += ", and `" + pre + "` must hold on each as it is at the moment of the change"
	}
	d.para(text + "; a change that finds otherwise is refused and changes nothing, so a second writer on the same record is refused rather than overwriting the first.")
}

func commandDetails(d *doc, c *yaml.Node) {
	args := items(c, "arguments")
	opts := pairs(c, "options")
	if len(args)+len(opts) > 0 {
		d.line("| Argument or option | Type | Required | Description |")
		d.line("|---|---|---|---|")
		for _, a := range args {
			t := typeText(get(a, "schema"))
			if str(a, "repeatable") == "true" {
				t += ", one or more"
			}
			req := ""
			if str(a, "required") == "true" {
				req = "yes"
			}
			d.line("| `<%s>` | %s | %s | %s |", str(a, "name"), cell(t), cell(req), cell(str(a, "description")))
		}
		for _, o := range opts {
			req := ""
			if str(o.Value, "required") == "true" {
				req = "yes"
			}
			d.line("| `--%s` | %s | %s | %s |", o.Key.Value, cell(typeText(get(o.Value, "schema"))), cell(req), cell(str(o.Value, "description")))
		}
		d.blank()
	}
	for _, f := range [][2]string{{"reads", "Reads"}, {"writes", "Writes"}} {
		if list := items(c, f[0]); len(list) > 0 {
			var parts []string
			for _, u := range list {
				parts = append(parts, "`"+str(u, "path")+"`: "+strings.TrimSuffix(strings.TrimSpace(str(u, "description")), "."))
			}
			d.para(f[1] + " " + strings.Join(parts, "; ") + ".")
		}
	}
	for _, f := range [][2]string{{"standardOutput", "Standard output"}, {"standardError", "Standard error"}} {
		if s := str(c, f[0]); s != "" {
			d.para(f[1] + ": " + s)
		}
	}
}

func crossCutting(d *doc, root *yaml.Node) {
	perms := permissionsTable(root)
	pages := pairs(root, "pages")
	algs := pairs(root, "algorithms")
	session := get(root, "session")
	sensitive := sensitiveFields(root)
	if perms == "" && session == nil && len(pages)+len(algs)+len(sensitive) == 0 {
		return
	}
	d.heading(2, "8. Cross-cutting concepts")
	if len(sensitive) > 0 {
		d.heading(3, "Sensitive data")
		d.para("The entity fields that are not public, and the ones encrypted at rest. A personal field is masked in logs and shown only to who may see it; a credential is never answered (the pii-in-logs and encrypted-column idioms).")
		d.line("| Field | Sensitivity | At rest |")
		d.line("|---|---|---|")
		for _, row := range sensitive {
			d.line("| %s | %s | %s |", row[0], row[1], row[2])
		}
		d.blank()
	}
	if perms != "" {
		d.heading(3, "Permissions")
		d.para("Access is fail-closed: every operation, command and page names the one permission it needs, and only the roles below grant one.")
		d.block(perms)
		d.explainRows(append(pairRows(root, "permissions"), pairRows(root, "roles")...))
	}
	if session != nil {
		d.heading(3, "Sessions")
		d.para(str(session, "description"))
		var ends []string
		if t := str(session, "idleTimeout"); t != "" {
			ends = append(ends, "after "+t+" without a request")
		}
		if t := str(session, "absoluteTimeout"); t != "" {
			ends = append(ends, "after "+t+" from signing in, whatever the caller does")
		}
		d.para("A caller's session expires " + strings.Join(ends, ", and ") + ". Every operation, command and page with a permission other than public refuses a caller whose session has expired.")
		d.explain(session)
	}
	if len(pages) > 0 {
		d.heading(3, "Pages")
		d.block(pagesFlowchart(root))
		if menus := pairs(root, "menus"); len(menus) > 0 {
			d.para("The menu, each entry shown to who may open its page:")
			menuList(d, root, menus, "")
			d.blank()
		}
		d.line("| Page | Kind | Route | Entity | Permission | Shows |")
		d.line("|---|---|---|---|---|---|")
		for _, p := range pages {
			shows := strs(p.Value, "columns")
			if len(shows) == 0 {
				shows = strs(p.Value, "fields")
			}
			text := strings.Join(shows, ", ")
			var groups []string
			for _, sec := range items(p.Value, "sections") {
				groups = append(groups, str(sec, "title")+": "+strings.Join(strs(sec, "fields"), ", "))
			}
			if len(groups) > 0 {
				text = strings.Join(groups, "; ")
			}
			if compact := strs(p.Value, "compactColumns"); len(compact) > 0 {
				text += "; on a compact screen " + strings.Join(compact, ", ")
			}
			d.line("| %s | %s | %s | %s | %s | %s |", p.Key.Value, str(p.Value, "kind"), cell(str(p.Value, "route")), str(p.Value, "entity"), str(p.Value, "permission"), cell(text))
		}
		d.blank()
		var stateRows []string
		for _, p := range pages {
			states := get(p.Value, "states")
			for _, k := range []string{"empty", "filteredEmpty"} {
				if st := get(states, k); st != nil {
					stateRows = append(stateRows, fmt.Sprintf("| %s | %s | %s |", p.Key.Value, map[string]string{"empty": "empty", "filteredEmpty": "filtered empty"}[k], cell(str(st, "message"))))
				}
			}
			for _, f := range pairs(states, "failed") {
				state := "failed: " + f.Key.Value
				if fld := str(f.Value, "field"); fld != "" {
					state += ", beside " + fld
				}
				stateRows = append(stateRows, fmt.Sprintf("| %s | %s | %s |", p.Key.Value, state, cell(str(f.Value, "message"))))
			}
		}
		d.explainRows(rowsOf(pages))
		if len(stateRows) > 0 {
			d.para("What each page shows when it is empty or fails; while it loads or submits, the stack draws its own:")
			d.line("| Page | State | Message |")
			d.line("|---|---|---|")
			for _, r := range stateRows {
				d.line("%s", r)
			}
			d.blank()
		}
	}
	for _, f := range pairs(root, "flows") {
		d.heading(3, "Flow "+f.Key.Value)
		d.para(str(f.Value, "description") + " Done by " + str(f.Value, "actor") + ".")
		d.block(flowFlowchart(f.Value))
		d.explain(f.Value)
	}
	if a := get(root, "accessibility"); a != nil {
		accessibilityTable(d, a, len(items(get(root, "theme"), "pairs")) > 0)
	}
	if get(root, "theme") != nil {
		themeTables(d, root)
	}
	for _, a := range algs {
		d.heading(3, "Algorithm "+a.Key.Value)
		d.para(str(a.Value, "description"))
		d.explain(a.Value)
		var inputs []string
		for _, in := range pairs(a.Value, "inputs") {
			inputs = append(inputs, fmt.Sprintf("`%s` (%s)", in.Key.Value, typeText(in.Value)))
		}
		d.para("Inputs: " + strings.Join(inputs, ", ") + ". Output: " + typeText(get(a.Value, "output")) + ".")
		d.line("Formula:")
		d.blank()
		d.line("    %s", strings.TrimSpace(str(a.Value, "formula")))
		d.blank()
		d.line("| Worked example | Inputs | Expected | Note |")
		d.line("|---|---|---|---|")
		for _, ex := range items(a.Value, "examples") {
			var in []string
			for _, p := range pairs(ex, "inputs") {
				in = append(in, p.Key.Value+" "+p.Value.Value)
			}
			d.line("| %s | %s | %s | %s |", cell(str(ex, "name")), cell(strings.Join(in, ", ")), cell(str(ex, "expected")), cell(str(ex, "note")))
		}
		d.blank()
		d.line("Pseudocode:")
		d.blank()
		d.line("```text")
		d.WriteString(strings.TrimRight(str(a.Value, "pseudocode"), "\n") + "\n")
		d.line("```")
		d.blank()
	}
}

// decisions writes the decision records; with no title they are a part of
// the implementation chapter.
func decisions(d *doc, title string, root *yaml.Node) {
	decs := pairs(root, "decisions")
	if len(decs) == 0 {
		return
	}
	level := 3
	if title == "" {
		d.heading(4, "Implementation decisions")
		level = 5
	} else {
		d.heading(2, title)
	}
	for _, p := range decs {
		dec := p.Value
		d.heading(level, fmt.Sprintf("%s: %s", p.Key.Value, str(dec, "title")))
		status := str(dec, "status") + ", " + str(dec, "date")
		if s := str(dec, "supersededBy"); s != "" {
			status += ", superseded by " + s
		}
		d.para("Status: " + status + ".")
		for _, part := range [][2]string{{"context", "Context"}, {"decision", "Decision"}, {"consequences", "Consequences"}} {
			if v := strings.TrimSpace(str(dec, part[0])); v != "" {
				d.para(part[1] + ": " + v)
			}
		}
		d.explain(dec)
	}
}

func qualityTests(d *doc, root *yaml.Node) {
	tests := pairs(root, "tests")
	if len(tests) == 0 {
		return
	}
	d.heading(2, "10. Quality requirements")
	d.para("The design tests: what must hold on every implementation. Golden scenarios succeed; red scenarios are refused.")
	d.line("| Test | Subject | Level | Scenario | Given | When | Then |")
	d.line("|---|---|---|---|---|---|---|")
	for _, t := range tests {
		subject := testSubject(t.Value)
		if na := str(t.Value, "notApplicable"); na != "" {
			d.line("| %s | %s | %s | %s | %s | %s | %s |", t.Key.Value, cell(subject), str(t.Value, "level"), str(t.Value, "scenario"), "not applicable", " ", cell(na))
			continue
		}
		d.line("| %s | %s | %s | %s | %s | %s | %s |", t.Key.Value, cell(subject), str(t.Value, "level"), str(t.Value, "scenario"), cell(str(t.Value, "given")), cell(str(t.Value, "when")), cell(str(t.Value, "then")))
	}
	d.blank()
	d.explainRows(rowsOf(tests))
}

func testSubject(t *yaml.Node) string {
	for _, k := range []string{"operation", "command", "page", "job"} {
		if v := str(t, k); v != "" {
			return k + " " + v
		}
	}
	if c := str(t, "constraint"); c != "" {
		return str(t, "entity") + " constraint " + c
	}
	if tr := get(t, "transition"); tr != nil {
		return fmt.Sprintf("%s %s to %s", str(t, "entity"), str(tr, "from"), str(tr, "to"))
	}
	if r := str(t, "requirement"); r != "" {
		return "requirement " + r
	}
	if e := str(t, "entity"); e != "" {
		return e + " state machine"
	}
	return ""
}

// glossary is chapter 12.
func glossary(d *doc, root *yaml.Node) {
	terms := pairs(root, "glossary")
	if len(terms) == 0 {
		return
	}
	d.heading(2, "12. Glossary")
	d.line("| Term | Meaning |")
	d.line("|---|---|")
	for _, t := range terms {
		d.line("| %s | %s |", cell(t.Key.Value), cell(str(t.Value, "definition")))
	}
	d.blank()
	d.explainRows(rowsOf(terms))
}

// requirements is chapter 13: the needs, the requirements with their
// attributes, and the traceability matrix: what satisfies and what
// verifies each requirement.
func requirements(d *doc, root *yaml.Node, impls []Implementation) {
	reqs := pairs(root, "requirements")
	needs := pairs(root, "needs")
	satisfied, verified := traceLinks(root, impls)
	external := map[string]bool{}
	for _, s := range pairs(root, "sources") {
		if str(s.Value, "kind") == "requirement-set" {
			external[str(s.Value, "prefix")] = true
		}
	}
	if len(reqs)+len(needs)+len(satisfied)+len(verified) == 0 {
		return
	}
	d.heading(2, "13. Requirements")
	if len(needs) > 0 {
		d.heading(3, "Needs")
		d.line("| Need | Statement | Stakeholders | Status |")
		d.line("|---|---|---|---|")
		for _, n := range needs {
			d.line("| %s | %s | %s | %s |", n.Key.Value, cell(str(n.Value, "statement")), cell(strings.Join(strs(n.Value, "stakeholders"), ", ")), cell(str(n.Value, "status")))
		}
		d.blank()
		d.explainRows(rowsOf(needs))
	}
	if len(reqs) > 0 {
		d.heading(3, "Requirements")
		d.line("| Requirement | Statement | Kind | Priority | Status | Verification | Acceptance | Needs |")
		d.line("|---|---|---|---|---|---|---|---|")
		for _, r := range reqs {
			d.line("| %s | %s | %s | %s | %s | %s | %s | %s |", r.Key.Value, cell(str(r.Value, "statement")), str(r.Value, "kind"), str(r.Value, "priority"), str(r.Value, "status"), cell(str(r.Value, "verification")), cell(strings.Join(strs(r.Value, "acceptance"), " ")), cell(strings.Join(strs(r.Value, "needs"), ", ")))
		}
		d.blank()
		d.explainRows(rowsOf(reqs))
	}
	for _, s := range pairs(root, "sources") {
		if str(s.Value, "kind") == "requirement-set" {
			d.para(fmt.Sprintf("%s: requirements with the prefix %s are in %s.", s.Key.Value, str(s.Value, "prefix"), strings.TrimSpace(str(s.Value, "title"))))
		}
	}
	d.heading(3, "Traceability")
	d.para("What satisfies and what verifies each requirement. An empty cell is a gap.")
	harm := harmColumn(reqs)
	d.line("| Requirement |%s Satisfied by | Verified by |", harm.header)
	d.line("|---|%s---|---|", harm.rule)
	ids := map[string]bool{}
	for _, r := range reqs {
		ids[r.Key.Value] = true
	}
	for k := range satisfied {
		ids[k] = true
	}
	for k := range verified {
		ids[k] = true
	}
	for _, k := range sortedLinks(ids) {
		d.line("| %s |%s %s | %s |", k, harm.cell(k), cell(strings.Join(unique(satisfied[k]), "; ")), cell(strings.Join(unique(verified[k]), "; ")))
	}
	d.blank()
}

// childLabel builds a reader's name for a nested object: "entities Loan".
func childLabel(parent, key string) string {
	if parent == "" {
		return key
	}
	return parent + " " + key
}

func unique(s []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, v := range s {
		if !seen[v] {
			seen[v] = true
			out = append(out, v)
		}
	}
	return out
}

// traceLinks finds, for every requirement ID, the elements that satisfy it
// and the ones that verify it, each named the way a reader finds it:
// "entities Loan", "tests loan-late".
func traceLinks(root *yaml.Node, impls []Implementation) (satisfied, verified map[string][]string) {
	satisfied = map[string][]string{}
	verified = map[string][]string{}
	var walk func(n *yaml.Node, label string)
	walk = func(n *yaml.Node, label string) {
		for _, p := range pairsOf(n) {
			switch p.Key.Value {
			case "satisfies":
				for _, r := range itemsOf(p.Value) {
					satisfied[r.Value] = append(satisfied[r.Value], label)
				}
				continue
			case "verifies":
				for _, r := range itemsOf(p.Value) {
					verified[r.Value] = append(verified[r.Value], label)
				}
				continue
			}
			walk(p.Value, childLabel(label, p.Key.Value))
		}
		for i, it := range itemsOf(n) {
			walk(it, fmt.Sprintf("%s %d", label, i+1))
		}
	}
	walk(root, "")
	for _, i := range impls {
		walk(i.Node, "implementation "+str(get(i.Node, "info"), "title"))
	}
	return satisfied, verified
}

// sensitiveFields lists every entity field with a sensitivity other than
// public, or encrypted at rest: its name, its sensitivity and how it is
// stored.
func sensitiveFields(root *yaml.Node) [][3]string {
	var out [][3]string
	for _, e := range pairs(root, "entities") {
		for _, f := range pairs(e.Value, "properties") {
			sens := str(f.Value, "sensitivity")
			at := str(f.Value, "atRest")
			if (sens == "" || sens == "public") && at == "" {
				continue
			}
			if at != "" && str(f.Value, "lookup") != "" {
				at += ", found by " + str(f.Value, "lookup")
			}
			if sens == "" {
				sens = "not stated"
			}
			out = append(out, [3]string{e.Key.Value + "." + f.Key.Value, sens, at})
		}
	}
	return out
}

// jobDetails writes what starts a job, what it acts as, reads, writes,
// calls and publishes, and how it retries.
func jobDetails(d *doc, root *yaml.Node, j *yaml.Node) {
	trigger := get(j, "trigger")
	var start string
	switch {
	case str(trigger, "schedule") != "":
		start = "on the schedule `" + str(trigger, "schedule") + "` (UTC)"
	case str(trigger, "every") != "":
		start = "every " + str(trigger, "every")
	default:
		start = "for each " + str(trigger, "consumes") + " it consumes"
	}
	text := "Runs " + start + ", as the role " + str(j, "role") + "."
	if r := strs(j, "reads"); len(r) > 0 {
		text += " Reads " + joinAnd(r) + "."
	}
	if w := strs(j, "writes"); len(w) > 0 {
		text += " Writes " + joinAnd(w) + "."
	}
	if calls := strs(j, "calls"); len(calls) > 0 {
		var parts []string
		for _, c := range calls {
			parts = append(parts, fmt.Sprintf("%s (within %s)", c, str(get(get(root, "dependencies"), c), "timeout")))
		}
		text += " Calls " + joinAnd(parts) + "."
	}
	if e := strs(j, "emits"); len(e) > 0 {
		text += " Publishes " + joinAnd(e) + "."
	}
	if r := get(j, "retries"); r != nil {
		after := "set aside for a person"
		if str(r, "then") == "discard" {
			after = "dropped"
		}
		text += " A failed item is tried " + str(r, "limit") + " times, then " + after + "."
	}
	d.para(text + " Running it twice over the same records changes nothing a second time.")
}

// menuList writes the menu tree as a nested list.
func menuList(d *doc, root *yaml.Node, items []source.Pair, indent string) {
	for _, m := range items {
		if page := str(m.Value, "page"); page != "" {
			perm := str(get(get(root, "pages"), page), "permission")
			d.line("%s- %s: page %s, %s", indent, str(m.Value, "title"), page, perm)
			continue
		}
		d.line("%s- %s", indent, str(m.Value, "title"))
		menuList(d, root, pairs(m.Value, "items"), indent+"  ")
	}
}

// viewPathField follows a view's path from an entity through its relations
// to the field it ends in, or nil, and says whether a relation on the way
// may have no record: its via field is not required, or may be null.
func viewPathField(root *yaml.Node, entity, path string) (*yaml.Node, bool) {
	hops := strings.Split(path, ".")
	cur := get(get(root, "entities"), entity)
	optional := false
	for _, hop := range hops[:len(hops)-1] {
		rel := get(get(cur, "relations"), hop)
		via := str(rel, "via")
		if !contains(strs(cur, "required"), via) || strings.Contains(typeText(get(get(cur, "properties"), via)), "or null") {
			optional = true
		}
		cur = get(get(root, "entities"), str(rel, "target"))
	}
	return get(get(cur, "properties"), hops[len(hops)-1]), optional
}

// wcagCriteria are the WCAG 2.2 success criteria a user interface built
// from a specification meets, with who meets each: the design, checked by
// the validator or not, the generator, or a person.
var wcagCriteria = []struct{ id, name, level, who, how string }{
	{"1.1.1", "Non-text content", "A", "a person", "an image's text alternative is written where the image is chosen"},
	{"1.3.1", "Info and relationships", "A", "the generator", "a page's title, its labels and its order become the stack's headings and labelled controls"},
	{"1.4.1", "Use of color", "A", "the generator", "a state or a value is shown in text as well as in colour"},
	{"1.4.3", "Contrast (minimum)", "AA", "the generator", "the stack's own colours, which a person checks"},
	{"1.4.11", "Non-text contrast", "AA", "the generator", "the stack's own colours for the parts of controls, which a person checks"},
	{"2.1.1", "Keyboard", "A", "the generator", "every action and field is reachable without a pointer"},
	{"2.4.3", "Focus order", "A", "the design", "the order of a page's fields and columns is its focus order"},
	{"2.4.6", "Headings and labels", "AA", "the design, checked", "every page has a title, every field it shows a title, and every action a label of its own"},
	{"2.5.8", "Target size (minimum)", "AA", "the generator", "every control is at least 24 by 24 CSS pixels"},
	{"3.2.3", "Consistent navigation", "AA", "the design", "the menu is one tree, the same on every page"},
	{"3.3.1", "Error identification", "A", "the design, checked", "every failed state a page declares is a message in a full sentence, beside the field it is about"},
	{"3.3.2", "Labels or instructions", "A", "the design, checked", "every field a page shows has a title"},
	{"4.1.2", "Name, role, value", "A", "the design, checked, and the generator", "every action has a label of its own; the generator gives each control its role"},
	{"4.1.3", "Status messages", "AA", "the design and the generator", "every event's message and every state is text, which the generator announces without moving focus"},
}

// accessibilityTable lists the criteria of the target's level and who
// meets each.
func accessibilityTable(d *doc, a *yaml.Node, pairs bool) {
	level := str(a, "level")
	d.heading(3, "Accessibility")
	d.para("The user interface conforms to " + str(a, "standard") + " at level " + level + ". What the design decides is in the specification, and the validator checks what it can; the rest is the generator's to build and a person's to check at commissioning.")
	d.line("| Criterion | Level | Met by | How |")
	d.line("|---|---|---|---|")
	for _, c := range wcagCriteria {
		if len(c.level) > len(level) {
			continue
		}
		who, how := c.who, c.how
		if pairs && (c.id == "1.4.3" || c.id == "1.4.11") {
			who, how = "the design, checked", "every pair of colours the theme declares has the contrast its use asks for, in every mode"
		}
		d.line("| %s %s | %s | %s | %s |", c.id, c.name, c.level, who, how)
	}
	d.blank()
}

// tokenText writes a token's value as a reader reads it: a colour as its
// hex, a dimension or a duration with its unit, an alias as the token it
// names.
func tokenText(v *yaml.Node) string {
	if v == nil {
		return ""
	}
	if v.Kind == yaml.ScalarNode && strings.HasPrefix(v.Value, "{") && strings.HasSuffix(v.Value, "}") {
		return "same as " + strings.Trim(v.Value, "{}")
	}
	if cs := items(v, "components"); len(cs) == 3 {
		var hex strings.Builder
		hex.WriteString("#")
		for _, c := range cs {
			f, err := strconv.ParseFloat(c.Value, 64)
			if err != nil {
				return ""
			}
			fmt.Fprintf(&hex, "%02x", int(math.Round(f*255)))
		}
		return hex.String()
	}
	if u := str(v, "unit"); u != "" {
		return str(v, "value") + u
	}
	if v.Kind == yaml.SequenceNode {
		var names []string
		for _, n := range v.Content {
			names = append(names, n.Value)
		}
		return strings.Join(names, ", ")
	}
	return v.Value
}

// themeTables lists the theme's tokens with their value in each mode, and
// its pairs of colours with their contrast in each.
func themeTables(d *doc, root *yaml.Node) {
	theme := get(root, "theme")
	d.heading(3, "Theme")
	var rows []string
	var walk func(group *yaml.Node, prefix, typ string)
	walk = func(group *yaml.Node, prefix, typ string) {
		if t := str(group, "$type"); t != "" {
			typ = t
		}
		for _, p := range pairsOf(group) {
			if strings.HasPrefix(p.Key.Value, "$") {
				continue
			}
			path := strings.TrimPrefix(prefix+"."+p.Key.Value, ".")
			if get(p.Value, "$value") == nil {
				walk(p.Value, path, typ)
				continue
			}
			t := typ
			if own := str(p.Value, "$type"); own != "" {
				t = own
			}
			row := fmt.Sprintf("| %s | %s | %s |", path, t, cell(tokenText(get(p.Value, "$value"))))
			for _, m := range pairs(theme, "modes") {
				row += " " + cell(tokenText(get(m.Value, path))) + " |"
			}
			rows = append(rows, row)
		}
	}
	walk(get(theme, "tokens"), "", "")
	modes := pairs(theme, "modes")
	head, rule := "| Token | Type | Value |", "|---|---|---|"
	for _, m := range modes {
		head += " " + m.Key.Value + " |"
		rule += "---|"
	}
	d.para("The design tokens, in the format of the W3C Design Tokens Community Group. A mode's column shows the value it gives a token, and is empty where the token keeps its own.")
	d.line("%s", head)
	d.line("%s", rule)
	for _, r := range rows {
		d.line("%s", r)
	}
	d.blank()
	contrasts, modeNames := validate.ThemeContrasts(root)
	if len(contrasts) == 0 {
		return
	}
	head, rule = "| Text | Background | Use | Contrast |", "|---|---|---|---|"
	for _, m := range modeNames {
		head += " " + m + " |"
		rule += "---|"
	}
	d.para("The pairs of colours shown together, with their contrast in each mode:")
	d.line("%s", head)
	d.line("%s", rule)
	for _, p := range contrasts {
		row := fmt.Sprintf("| %s | %s | %s |", p.Text, p.Background, p.Use)
		for _, r := range p.Ratios {
			row += " " + r + " |"
		}
		d.line("%s", row)
	}
	d.blank()
}
