// Package genbpmn writes the workflows of a specification as BPMN 2.0: the
// logic of the specarch-gen-bpmn plug-in. Each workflow is one process in a
// file of its own, with its diagram (BPMN DI) laid out by a fixed rule, and
// the same diagram as SVG for documents. The process uses the sequential
// subset the meta-model takes from BPMN (ADR-054), so specarch extract
// workflows reads it back to the same steps.
package genbpmn

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"

	"github.com/SpecArch/specarch/internal/ownership"
)

// Request is what specarch writes on a plug-in's standard input.
type Request struct {
	Specarch        string           `json:"specarch"`
	Target          string           `json:"target"`
	Root            string           `json:"root"`
	Specification   map[string]any   `json:"specification"`
	Implementations []Implementation `json:"implementations"`
	Output          string           `json:"output"`
	// Draft is true when no approval record covers the specification's
	// files as they are and the run was told to go on without one.
	Draft bool `json:"draft"`
	// Problems are the specification's warnings and open questions, in
	// the order of the problems file.
	Problems []Problem `json:"problems"`
}

// Implementation is one implementation file in the request.
type Implementation struct {
	File    string         `json:"file"`
	Content map[string]any `json:"content"`
}

// Problem is one problem of the specification, as a file marks it.
type Problem struct {
	ID       string `json:"id"`
	Severity string `json:"severity"`
	Rule     string `json:"rule"`
	Message  string `json:"message"`
	// Pointer leads into the merged specification, or is "" for a problem
	// outside it.
	Pointer string `json:"pointer"`
	// Blocks are what a question blocks, as it names them.
	Blocks []string `json:"blocks,omitempty"`
}

// File is one file the plug-in answers with.
type File struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// Diagnostic is one problem the plug-in reports, in the validator's fields.
type Diagnostic struct {
	File     string `json:"file"`
	Line     int    `json:"line"`
	Severity string `json:"severity"`
	Path     string `json:"path"`
	Rule     string `json:"rule"`
	Message  string `json:"message"`
}

// Response is what the plug-in writes on its standard output.
type Response struct {
	Files       []File       `json:"files"`
	Diagnostics []Diagnostic `json:"diagnostics"`
}

// Decode reads a request, keeping numbers as their text.
func Decode(data []byte) (*Request, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var r Request
	if err := dec.Decode(&r); err != nil {
		return nil, err
	}
	return &r, nil
}

// The namespaces of a BPMN 2.0 XML file: the semantic model, its diagram
// interchange, and the shapes and points the diagram is drawn with.
const (
	nsModel  = "http://www.omg.org/spec/BPMN/20100524/MODEL"
	nsBPMNDI = "http://www.omg.org/spec/BPMN/20100524/DI"
	nsDC     = "http://www.omg.org/spec/DD/20100524/DC"
	nsDI     = "http://www.omg.org/spec/DD/20100524/DI"
	nsXSI    = "http://www.w3.org/2001/XMLSchema-instance"
)

// Generate writes one BPMN file and one SVG file per workflow.
func Generate(r *Request) Response {
	spec := r.Specification
	owned := ownership.Owned{}
	for _, impl := range r.Implementations {
		for ptr, by := range ownership.Of(impl.Content) {
			owned[ptr] = by
		}
	}
	info := obj(spec["info"])
	header := fmt.Sprintf("Generated by specarch-gen-bpmn from %s, version %s; meta-model %s. Do not edit this file: change the YAML and generate again.",
		relRoot(r.Root, r.Output), text(info["version"]), r.Specarch)
	files := []File{}
	workflows := obj(spec["workflows"])
	for _, name := range sortedKeys(workflows) {
		if owned.Covers("#/workflows/" + ownership.Escape(name)) {
			continue
		}
		w := layout(spec, name, obj(workflows[name]))
		w.marks = marksOf(w, r.Problems)
		files = append(files,
			File{Path: name + ".bpmn", Content: w.bpmn(header, r.Draft)},
			File{Path: name + ".svg", Content: w.svg(header, r.Draft)})
	}
	return Response{Files: files, Diagnostics: []Diagnostic{}}
}

// relRoot is the root file's path from the output folder.
func relRoot(root, output string) string {
	absRoot, err1 := filepath.Abs(filepath.FromSlash(root))
	absOut, err2 := filepath.Abs(filepath.FromSlash(output))
	if err1 != nil || err2 != nil {
		return root
	}
	rel, err := filepath.Rel(absOut, absRoot)
	if err != nil {
		return root
	}
	return filepath.ToSlash(rel)
}

func obj(v any) map[string]any {
	m, _ := v.(map[string]any)
	return m
}

func list(v any) []any {
	l, _ := v.([]any)
	return l
}

func text(v any) string {
	switch x := v.(type) {
	case nil:
		return ""
	case string:
		return x
	case json.Number:
		return x.String()
	}
	return fmt.Sprint(v)
}

func sortedKeys(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
