// Generated by specarch-gen-ui-typescript from ../../../spec/specarch.yaml, version 0.1.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
import type { FormPageSchema } from "@/screens";

export const schema = {
  title: "member-form.title",
  permission: "members.write",
  submit: { operation: "createMember", method: "POST", path: "/members", fields: ["fullName", "email", "tier"] },
  layout: "page",
  sections: [
    {
      fields: [
        { type: "text", name: "fullName", label: "member-form.fields.fullName", required: true, minLength: 1, maxLength: 200 },
        { type: "email", name: "email", label: "member-form.fields.email", required: true, maxLength: 320 },
        { type: "select", name: "tier", label: "member-form.fields.tier", required: true, options: ["standard", "extended"] },
      ],
    },
  ],
  rows: [],
  checks: [],
  failed: [{ status: 409, problem: "email-taken", message: "member-form.failed.email-taken" }],
  events: [{ navigate: "member-view", with: { memberId: "id" }, message: "member-form.onSubmitted" }],
} satisfies FormPageSchema;
