// Generated by specarch-gen-ui-typescript from ../project/specarch.yaml, version 1.0.0; meta-model 0.1. Do not edit this file: change the YAML and generate again.
// Draft: the specification is not approved: there is no records/approvals/1.0.0.yaml beside the specification; this file is not the approved output.
// specarch-problem: warning: test_case_missing: page member-view has no red scenario for "not found memberId"; add under tests member-view-not-found-member-id: { page: member-view, scenario: red, covers: [not found memberId], given: "no record has that memberId", when: "the page member-view is opened for that memberId", then: "it says the record was not found" } [test_case_missing@specarch.yaml#/pages/member-view]
// specarch-problem: warning: test_golden_missing: page member-view has no golden scenario; add one under tests, for example member-view-succeeds: { page: member-view, scenario: golden, given: "any caller", when: "the page member-view is opened for a record that exists", then: "it shows the page" } [test_golden_missing@specarch.yaml#/pages/member-view]
import type { Metadata } from "next";
import { Guard, ViewPage } from "@/screens";
import { chosenLanguage } from "@/language";
import { stringOf, texts } from "@/strings";
import { schema } from "./page.schema";

export async function generateMetadata(): Promise<Metadata> {
  return { title: stringOf("member-view.title", await chosenLanguage()) };
}

const routes = {
};

export default async function Page({ params }: { readonly params: Promise<Record<string, string>> }) {
  const parameters = await params;
  const t = texts(schema, await chosenLanguage());
  return (
    <Guard permission={schema.permission} texts={t}>
      <ViewPage schema={schema} texts={t} routes={routes} parameters={parameters} />
    </Guard>
  );
}
